export default {
  "联系邮箱": "Adresse e-mail de contact",
  "代理商等级": "Niveau d'agent",
  "上级代理商": "Agent supérieur",
  "重置密码": "Réinitialiser le mot de passe",
  "新密码": "Nouveau mot de passe",
  "操作成功": "Opération réussie",
  "操作失败": "Opération échouée",
  "共n条记录": "{total} enregistrements au total",
  "是否前往": "Le compte a été ajouté avec succès, veuillez aller dans le \"Centre Client\" pour compléter les informations de base de l'agent.",
  "未添加无法登录": "Conseil : Si les informations de base de l'agent ne sont pas ajoutées, le compte ne pourra pas se connecter au système.",
  "立即前往": "Rendez-vous immédiatement",
  "查看账号": "Consulter les informations du compte",
  "生成新密码": "Cliquez ici pour générer un nouveau mot de passe",
  "随机密码": "Mot de passe aléatoire",
  "更换密码": "Changer le mot de passe",
  "复制密码": "Mot de passe copié",
  "已复制！": "Copié !",
  "图片裁剪": "Découpage d'image",
  "获取文件md5出错": "Erreur lors de l'obtention du MD5 du fichier",
  "oss删除文件失败": "La suppression du fichier OSS a échoué",
  "视频个数超出限额": "Le nombre de vidéos dépasse la limite autorisée.",
  "素材类型不正确": "Le format du matériel n'est pas correct.",
  "图片过大": "L'image est trop grande.",
  "视频过大": "La vidéo est trop volumineuse.",
  "分辨率超出": "La résolution dépasse {height}P",
  "账号不能包含空格": "Le compte ne peut pas contenir d'espaces.",
  "账号已存在": "Le compte existe déjà",
  "请设置密码": "Veuillez définir un mot de passe.",
  "密码规则": "Lettres majuscules et minuscules, chiffres, combinaison de trois types de caractères spéciaux.",
  "agent.store.info": "Seules les quantités de magasins développés par l'agent actuel sont comptabilisées, cela n'inclut pas le nombre de magasins des agents de niveau inférieur.",
  "account.noOrg.warning": "Le compte n'a pas complété les informations de l'agent, veuillez contacter la personne qui a créé votre compte pour le traitement.",
  "login.redirect": "Vous entrerez dans la page \"Plateforme de gestion commerciale\" après {keyProp} secondes.",
  "login.suc": "Connexion réussie",
  "login.fail": "Échec de la connexion",
  "enter.nowait": "Pas besoin d'attendre, cliquez pour entrer",
  "agent.type": "Types d'agents commerciaux",
  "请勿输入非法字符": "Veuillez ne pas entrer de caractères illégaux."
}