export default {
  "中国港澳台及海外地区": "Chine, Hong Kong, Macao, Taïwan et régions d'outre-mer",
  "中国大陆地区": "région continentale de la Chine",
  "代理商类型": "Types d'agents commerciaux",
  "类型": "type",
  "请选择代理商类型": "Veuillez sélectionner le type d'agent commercial.",
  "运营区域": "Région commercialisable",
  "请选择可销售的区域": "Veuillez sélectionner la région disponible à la vente.",
  "新增代理商": "Nouveau distributeur",
  "一级代理商": "Agent de premier niveau",
  "二级代理商": "Agent de second niveau",
  "一级": "Niveau un",
  "二级": "niveau deux",
  "代理账号": "Compte de mandataire",
  "公司所在地": "Siège social de l'entreprise",
  "注册时间": "Date d'inscription",
  "注册地区": "Région d'enregistrement",
  "销售区域": "Zone de vente",
  "上级代理商名称": "Nom de l'agent supérieur",
  "拓展门店数": "Expansion du nombre de magasins",
  "激活绑定数": "Nombre d'activations / Nombre d'appareils liés",
  "前往文件中心": "Rendez-vous au \"Centre de documents\"",
  "知道了": "Je sais.",
  "结束日期": "date de fin",
  "开始日期": "Date de début",
  "公司所在地不完整": "Le siège social de l'entreprise est incomplet.",
  "请输入纯数字": "Veuillez entrer le numéro de téléphone en chiffres uniquement."
}