export default {
  "open.platform.title": "Plateforme ouverte PUDU",
  "open.platform.desc": "La plateforme ouverte de Purdue peut fournir aux développeurs d'affaires de robots des services logiciels et matériels ouverts. Avec l'aide de la plateforme ouverte de Purdue, les développeurs peuvent pleinement utiliser toutes les fonctionnalités des robots, combiner les robots avec divers secteurs, et achever le développement des affaires de robots à partir de zéro, créant ainsi des possibilités infinies pour le projet.",
  "H-C.interaction": "Interaction homme-machine",
  "navigation.control": "Contrôle de navigation",
  "voice.play": "Annonce vocale",
  "full.amount.data": "Données complètes",
  "view.api.doc": "Consulter la documentation de l'API ouverte",
  "know.detail": "Comprendre les détails",
  "apply.sdk": "Demande de SDK de contrôle à distance",
  "apply.agent": "Demande de représentation",
  "apply.people": "Demandeur",
  "apply.email": "Adresse e-mail du demandeur",
  "apply.purpose": "Objectif de la demande",
  "device.id": "ID de l'équipement",
  "device.secret": "clé secrète",
  "app.secret": "Clé d'application",
  "apply.time": "Temps de demande",
  "applicant.info": "Informations sur le demandeur",
  "receive.email": "Boîte de réception des messages",
  "apply.app.info": "Demande d'informations sur l'application",
  "applicable.stores": "Magasins participants",
  "app.stores.tip": "Sélectionnez le magasin auquel appartient le robot à contrôler à distance.",
  "apply.functions": "Fonction de demande",
  "apply.desc": "Vous êtes en train de demander le \"SDK ouvert pour le contrôle à distance\", les développeurs peuvent utiliser les capacités ouvertes de ce SDK dans leur plateforme auto-développée pour appeler à distance les robots situés dans les magasins.",
  "api.doc.desc": "Kit de développement logiciel (SDK) pour le contrôle à distance",
  "api.sdk.download": "Après l'approbation de la vérification, vous pouvez télécharger.",
  "openplatform.email": "Boîte mail pour les questions des développeurs de Purdue",
  "email.input.tip": "Il est impératif de remplir correctement, pour recevoir la clé secrète et les informations SDK après l'acceptation de la demande.",
  "approved.tip": "L'édition des informations de l'application sera effective immédiatement, sans nécessité de révision répétée.",
  "regionId.diff.tip": "L'adresse source du magasin est différente",
  "voice.play.mgt": "Gestion de la synthèse vocale",
  "voice.play.subtitle": "Personnalisez la configuration de l'annonce vocale pour différents scénarios, tels que l'attraction de clients, la promotion et le racolage, pour faire du robot un expert en marketing encore plus professionnel.",
  "emoticon.interface.mgt": "Gestion de l'interface des émoticônes",
  "emoticon.interface.subtitle": "Des paramètres personnalisés avec des expressions de robot amusantes et intéressantes rendent le robot plus attrayant pour les clients.",
  "open.platform.subtitle": "Les capacités technologiques complètes des robots sont ouvertes, aidant les développeurs à réaliser des applications dans tous les scénarios industriels.",
  "emo.pack.name": "Nom du pack d'émoticônes",
  "emo.pack.create": "Création de packs d'émoticônes personnalisés",
  "apply.scope": "Champ d'application",
  "opr.steps": "Étapes opérationnelles",
  "opr.steps.sub": "Il est impératif de suivre les étapes, sinon la configuration échouera.",
  "steps.1": "Étape 1",
  "steps.1.desc": "Téléchargez le fichier actuel des émoticônes du robot.",
  "steps.2": "Étape 2",
  "steps.2.desc": "Remplacez les fichiers existants un par un avec de nouveaux fichiers d'émoticônes.",
  "steps.2.desc.ketty": "La calebasse comprend 2 ensembles d'émoticônes : \"double_eye\" et \"single_eye\". Choisissez de remplacer un ensemble d'émoticônes en utilisant le \"nouveau fichier d'émoticônes\" pour remplacer un ensemble d'émoticônes dans les dossiers \"animation\" et \"firstImage\".",
  "steps.2.ps1": "Le niveau hiérarchique, le nom et le nombre des dossiers et fichiers doivent être strictement maintenus inchangés.",
  "steps.2.ps2": "2. La résolution de l'image est de 1920*1200 pixels, le format est .png ; le format de l'émoticône est .mp4 ; le dossier entier ne doit pas dépasser 50 Mo.",
  "steps.2.ps2.ketty": "2. La résolution de la première image est de 1280*800, au format .png, avec une taille inférieure à 100 Ko ; le format de l'animation des émoticônes est .mp4, avec une résolution de 1280*800, et une taille inférieure à 4 Mo.",
  "steps.3": "Étape 3",
  "steps.3.desc": "Sélectionnez tous les fichiers d'émoticônes, compressez-les en un fichier .zip et téléchargez-les.",
  "steps.3.desc.ps": "Il ne faut pas compresser un dossier qui contient des sous-dossiers.",
  "emo.info": "Paquet d'émoticônes",
  "key.emo.use.tip": "Ce pack d'émoticônes est uniquement valable pour le modèle {key}.",
  "emo.upload": "Télécharger le pack d'émoticônes",
  "upload.del.confirm": "Le fichier sera supprimé de façon permanente, confirmez-vous ?",
  "scope.agent": "Tous les robots",
  "key.scope.agent": "Tous les robots {key}",
  "scope.store": "Tous les robots du magasin désigné",
  "scope.robot": "Robot désigné",
  "emo.upload.tip": "Veuillez télécharger un fichier zip, d'une taille totale inférieure à 50 Mo.",
  "emo.step.info.1": "Selon le dossier emo, remplacez progressivement les fichiers d'émoticônes.",
  "emo.step.info.2": "La hiérarchie des dossiers, les noms des dossiers et des fichiers ne peuvent pas être modifiés.",
  "emo.step.info.3": "Le fichier ne doit pas dépasser 50 Mo, la résolution de l'image doit être de 1920*1200 pixels, et le format des émoticônes doit être MP4.",
  "emo.step.info.4": "Fichiers d'expressions de joie, de colère, de tristesse, de plaisir, d'oreille gauche, d'oreille droite, etc., 14 MP4 + 1 PNG d'image de placeholder (l'absence d'image de placeholder peut entraîner un écran noir lors du changement d'expression)",
  "imp.robots.step1": "Télécharger le modèle",
  "imp.robots.step2": "Remplissez le MAC dans le modèle.",
  "not.in.stock": "Non en stock",
  "key.not": "Ce n'est pas {key}",
  "del.emoji.tip": "La suppression n'affectera pas les packs d'émoticônes déjà utilisés par le robot.",
  "store.list": "Liste des magasins",
  "robot.list": "Liste des robots",
  "name.repeat": "Nom dupliqué",
  "record.repeat": "Il y a des éléments répétés.",
  "zip.content.abnormal": "Le fichier d'émoticônes n'a pas été compressé conformément aux exigences.",
  "scop.tip1": "1, Tous : {key} sera poussé vers tous les robots sous l'agent. Les robots nouvellement liés obtiendront automatiquement {key}.",
  "scop.tip2": "2. Par magasin : {key} sera uniquement envoyé aux robots des magasins sélectionnés, et les nouveaux robots liés aux magasins sélectionnés obtiendront automatiquement {key}.",
  "scop.tip3": "3, Par machine : {key} ne sera poussé que vers les robots sélectionnés.",
  "emoji.pkg": "pack d'émoticônes",
  "voice.pkg": "pack de voix",
  "key.voice.use.tip": "Ce pack vocal est uniquement valable pour le modèle {key}.",
  "voice.del.tip": "Une fois supprimé, le contenu vocal ne sera plus diffusé dans ce scénario.",
  "batch.step1": "Téléchargez le tableau Excel de correspondance entre voiceID et les scénarios de synthèse vocale.",
  "batch.step2": "Selon le \"tableau de correspondance voiceID et scène\", renommez un par un les fichiers mp3 de voix personnalisés avec le voiceID correspondant.",
  "batch.step2.ps1": "1) Assurez-vous absolument que chaque fichier audio est nommé avec le bon voiceID, sinon le téléchargement échouera.",
  "batch.step3": "Après avoir placé toutes les voix personnalisées dans un dossier, sélectionnez le dossier pour un téléchargement en masse.",
  "batch.step3.ps1": "1) Attention à ne pas compresser le dossier",
  "batch.step3.ps2": "2) Un seul envoi peut contenir au maximum 300 fichiers audio, chaque fichier ne dépassant pas 3 Mo.",
  "batch.btn": "Sélectionnez le dossier à télécharger",
  "file.type.error": "Type de fichier incorrect",
  "count.limit": "Le nombre de documents dépasse la limite de {key}",
  "wrong.file.type": "Type de fichier incorrect",
  "file.size.exceeds": "La taille du fichier dépasse la limite de {key}",
  "voice.packing.tip": "Veuillez ne pas fermer la page, synthèse du pack vocal en cours...",
  "business.district.desc": "Configurer des robots dans le quartier commercial pour livrer les plats de plusieurs commerçants."
}