export default {
  "bd.account": "compte",
  "bd.username": "Prénom",
  "bd.role": "Personnage",
  "bd.name": "Nom du quartier commercial",
  "bd.numOfStores": "nombre de magasins",
  "bd.createtime": "Date de création",
  "bd.updatetime": "Heure de mise à jour",
  "bd.operation": "Opération",
  "bd.check": "Consulter",
  "bd.edit": "Éditeur",
  "bd.qrcode": "Télécharger le code QR",
  "bd.new": "Nouveau",
  "bd.goback": "retour",
  "bd.account.placeholder": "Veuillez entrer le compte",
  "bd.name.placeholder": "Veuillez entrer le nom du quartier d'affaires.",
  "bd.inquire": "Requête",
  "bd.reset": "Réinitialiser",
  "bd.store.tip": "Veuillez choisir un magasin",
  "bd.store.placeholder": "Veuillez entrer vos noms.",
  "bd.map.tip": "Veuillez sélectionner la carte",
  "bd.store.order": "Numéro de série",
  "bd.store.name": "Nom du magasin",
  "bd.store.label": "Sélectionner un magasin",
  "bd.map.label": "Sélectionner la carte",
  "bd.map.name": "Nom de la carte",
  "bd.map.uploadtype": "Type de téléchargement",
  "bd.map.association": "Nombre de produits associés",
  "bd.map.version": "version",
  "bd.map.using": "En cours d'utilisation",
  "bd.map.unused": "Non utilisé",
  "bd.map.uploadtype.apk": "Téléchargement d'APK",
  "bd.map.uploadtype.platform": "Plateforme de téléchargement",
  "bd.map.choose": "Sélection",
  "bd.store.industry": "secteur",
  "bd.store.address": "Adresse de la boutique",
  "bd.store.normal": "normal",
  "bd.store.logout": "Annulation",
  "bd.insiders.noOperatingAuthority": "Le personnel interne n'a pas l'autorisation d'opérer !",
  "bd.store.reminder": "Conseil amical : Seuls les magasins avec le statut \"normal\" sont pris en charge."
}