export default {
  "component.tagSelect.expand": "déployer",
  "component.tagSelect.collapse": "Replier",
  "component.tagSelect.all": "tous",
  "key.select.max": "Choisissez au maximum {key} robots.",
  "trial.period.day": "Période d'essai/jour",
  "lease.cycle.month": "Période de location/mois",
  "required.warn": "Vous avez des informations obligatoires à remplir.",
  "first.imp.time": "Date de première importation",
  "validate.robot.key.warn": "Veuillez entrer le SN (PID) complet ou le MAC.",
  "change.to.complex.query": "Basculer vers la recherche avancée",
  "change.to.simple.query": "Basculer vers la recherche simple",
  "openapi.docs": "Documentation de développement d'API",
  "customer.name": "Nom du commerçant",
  "key.template": "modèle",
  "confirm.file.upload": "Veuillez confirmer si le fichier a été complètement téléchargé.",
  "upload.fail": "Échec du téléchargement, veuillez réessayer.",
  "key.success": "Réussite",
  "key.fail": "échec",
  "import.result": "Résultats d'importation",
  "incompatibility.versions": "La nouvelle version n'est pas compatible avec l'ancienne version.",
  "auto.jump.available": "Redirection automatique vers une version disponible...",
  "import.maxcount.tip": "Il a été détecté que plus de {count} MAC ont été dépassés, le système n'a importé que les {count} premiers MAC, veuillez réimporter les MAC restants."
}