export default {
  "dc.total": "Total",
  "dc.yesterday": "hier",
  "dc.last7days": "Au cours des 7 derniers jours",
  "dc.last30days": "Au cours des 30 derniers jours",
  "dc.naturalDay": "jour naturel",
  "dc.natureWeek": "semaine naturelle",
  "dc.naturalMonth": "mois calendaire",
  "dc.chainRatio": "d'une période à l'autre",
  "dc.cumulativeNumber": "Nombre cumulé",
  "dc.activeRate": "Taux d'activité",
  "dc.robotOperationOverview": "Aperçu du fonctionnement de la machine",
  "dc.workTime": "Durée de travail",
  "dc.runningMileage": "kilométrage",
  "dc.taskTimes": "Exécuter la tâche suivante",
  "dc.robotRunningPeakTrend": "Tendance à la hausse de l'exploitation des robots",
  "dc.monthOnMonth": "Taux de croissance séquentiel et annuel",
  "dc.numberOfRobotRuns": "Le nombre de fonctionnement des robots",
  "dc.stages": "{num} appareils",
  "dc.robotOverview": "Aperçu de la machine",
  "dc.powerOnRobot": "Robot de démarrage",
  "dc.bindTheRobot": "Lier le robot",
  "dc.activateRobot": "Activer le robot",
  "dc.numberOfRobotsBound": "Nombre de machines liées",
  "dc.numberOfActiveRobots": "Nombre de machines activées",
  "dc.storeOverview": "Aperçu du magasin",
  "dc.numberOfActiveStores": "Nombre de magasins actifs",
  "dc.numberOfNewStores": "Nombre de nouveaux magasins",
  "dc.activeStore": "Magasin actif",
  "dc.silentStore": "Boutique du Silence",
  "dc.activeRobotPoweredOn": "Robot actif à l'allumage",
  "dc.downtime": "Durée de l'interruption",
  "dc.operatingHours": "Heures de fonctionnement",
  "dc.emptyActiveStore": "Aucun magasin actif pour le moment",
  "dc.emptySilentStore": "Boutique temporairement sans silence",
  "dc.export": "Exportation",
  "dc.addStore": "Nouveau magasin",
  "dc.cumulativeStores": "Magasins cumulés",
  "dc.storeName": "Nom du magasin",
  "dc.storeNamePlaceholder": "Veuillez entrer le nom du magasin",
  "dc.query": "Requête",
  "dc.activeRank": "Classement actif",
  "dc.creationTime": "Date de création",
  "dc.activeRobot": "Robot de démarrage",
  "dc.runTime": "Durée de fonctionnement",
  "dc.key.robot": "robot",
  "dc.key.boottime": "Heure de démarrage",
  "dc.key.starttime": "Heure de début d'exécution",
  "dc.task.number": "Nombre de tâches",
  "dc.robots.all": "Tous les robots",
  "dc.robot.select": "Veuillez sélectionner le robot.",
  "dc.tab.delivery": "Données de livraison",
  "dc.tab.cruise": "Données de croisière",
  "dc.tab.greeter": "Données de positionnement",
  "dc.tab.interaction": "Données d'interaction",
  "dc.tab.solicit": "Données sur l'attraction de clients",
  "dc.tab.grid": "Données de grille palatiale",
  "dc.tab.ad": "Données publicitaires",
  "dc.tab.recovery": "Données de contre-offre",
  "dc.mileage": "kilométrage",
  "dc.runtime": "Durée de fonctionnement",
  "dc.interactiveVisits": "Interactions utilisateur",
  "dc.interactionTime": "Durée d'interaction",
  "dc.greetings": "Nombre de salutations",
  "dc.reached": "Nombre de personnes atteintes",
  "dc.attract": "Attirer les visiteurs",
  "dc.voiceInteractions": "Nombre d'interactions vocales",
  "dc.voiceinteractionTime": "Durée d'interaction vocale",
  "dc.takeMeInCount": "\"Emmène-moi dans le magasin\" type de grille",
  "dc.featuredItemCount": "\"Grille de produits caractéristiques\"",
  "dc.favorablePromotionsCount": "\"Activité promotionnelle\" de type grille",
  "dc.guideToMenuCount": "\"Catégorie de grille de placement\"",
  "dc.posterCount": "\"Affiche\" de type grille palatiale",
  "dc.usherCount": "\"Grille de type 'guide de chemin'\"",
  "dc.danceCount": "\"Danse\" catégorie de grille",
  "dc.videoPosterCount": "\"Affiche vidéo\" de type grille palace",
  "dc.smallScreenExposureTime": "Durée de lecture sur petit écran",
  "dc.smallScreenExposures": "Nombre de lectures sur petit écran",
  "dc.bigScreenExposureTime": "Durée de lecture sur grand écran",
  "dc.bigScreenExposures": "Nombre de lectures sur grand écran",
  "dc.deliveryTables": "nombre de tables livrées",
  "dc.deliveryPlate": "Nombre de plateaux repas livrés",
  "dc.numberOfTieLessons": "Nombre de fois où le client a été accompagné à sa place",
  "dc.numberOfCleanTables": "Tables de nettoyage",
  "tip.export.nodata": "Aucune donnée à exporter pour le moment",
  "dc.robotOperationOverview.toolTip": "L'état de fonctionnement global du robot",
  "dc.robotOperationOverview.toolTip-1": "Durée de travail (h) : Nombre total d'heures de fonctionnement cumulées des robots liés à tous les magasins développés par l'agent pendant la période indiquée.",
  "dc.robotOperationOverview.toolTip-2": "Durée de travail (h) : Nombre total d'heures de fonctionnement cumulées des robots liés aux magasins développés par l'agent sur la période donnée.",
  "dc.robotOperationOverview.toolTip-3": "3. Nombre de tâches exécutées : Nombre cumulatif de tâches exécutées par tous les robots liés aux magasins développés par l'agent dans la plage de dates.",
  "dc.robotRunningPeakTrend.toolTip": "Tendance de pointe de fonctionnement des robots",
  "dc.robotRunningPeakTrend.toolTip-1": "1. Jour naturel : Il est possible de consulter le nombre de robots de chaque type en fonctionnement pendant les différentes plages horaires sur une période de 24 heures pour n'importe quel jour.",
  "dc.robotRunningPeakTrend.toolTip-2": "2. Semaine naturelle : il est possible de consulter le nombre de robots de chaque type en fonctionnement pour chaque jour de n'importe quelle semaine.",
  "dc.robotRunningPeakTrend.toolTip-3": "3. Mois naturel : il est possible de consulter le nombre de robots de chaque type en fonctionnement pour chaque jour d'un mois donné.",
  "dc.robotOverview.toolTip": "Activation et état actif des robots",
  "dc.robotOverview.toolTip-1": "1. Robots d'allumage : Nombre cumulé d'allumages des robots liés aux magasins développés par les agents dans la plage de dates.",
  "dc.robotOverview.toolTip-2": "2. Nombre cumulé : le nombre total de robots liés par l'agent depuis la première liaison d'un robot à un magasin jusqu'à la date limite de sélection.",
  "dc.robotOverview.toolTip-3": "3. Taux d'activité = pour la période donnée, (nombre de robots activés ÷ nombre total) * 100 %.",
  "dc.robotOverview.toolTip-4": "4. Robots liés : Nombre total cumulé de robots liés aux magasins par les agents commerciaux dans la plage de dates spécifiée.",
  "dc.robotOverview.toolTip-5": "5. Activation des robots : Nombre total de robots activés liés aux magasins par les agents dans la plage de dates.",
  "dc.storeOverview.toolTip": "Expansion des magasins actifs et de la situation des nouveaux magasins",
  "dc.storeOverview.toolTip-1": "Nombre de magasins actifs : Sur la période donnée, parmi les magasins développés par l'agent, ceux qui disposent d'un robot en fonctionnement sont comptés comme un magasin actif.",
  "dc.storeOverview.toolTip-2": "2. Nombre cumulé : Depuis la date de première liaison de l'agent avec le magasin jusqu'à la date limite de sélection, le nombre cumulé de magasins.",
  "dc.storeOverview.toolTip-3": "3. Taux d'activité = pour la période donnée, (nombre de magasins actifs ÷ nombre total) * 100 %.",
  "dc.storeOverview.toolTip-4": "4. Nombre de nouveaux magasins : Nombre total de magasins ajoutés pendant la période indiquée.",
  "dc.storeOverview.toolTip-5": "5. Top 10 des magasins actifs : Sur la période donnée, parmi les magasins développés par les agents, ceux où le taux d'utilisation des robots est le plus élevé et la durée de fonctionnement la plus longue, sont classés plus haut dans le classement de l'activité des magasins.",
  "dc.storeOverview.toolTip-6": "Top 10 des boutiques silencieuses : Sur la période donnée, parmi les boutiques développées par les agents, celles où le taux d'activité des robots est nul sont considérées comme des boutiques silencieuses. Plus il y a de robots désactivés et plus la période de silence est longue, plus le classement de silence est élevé.",
  "dc.activeStore.toolTip": "Durant la période indiquée, parmi les magasins développés par les agents, ceux qui disposent d'un robot en fonctionnement sont comptés comme un magasin actif.",
  "dc.silentStore.toolTip": "Tous les appareils liés dans le magasin qui n'ont pas été allumés pendant la période indiquée sont considérés comme 1 magasin silencieux.",
  "dc.addStore.toolTip": "Quantité totale de nouveaux magasins ajoutés pendant la période indiquée.",
  "dc.cumulativeStores.toolTip": "À partir de la date de la première liaison de l'agent avec le magasin, jusqu'à la date limite de sélection, le nombre total de magasins accumulés.",
  "robot.status.bind.tip": "1, Déjà dissocié : le robot est actuellement lié à un autre magasin, ces données correspondent à l'historique des données filtrées par date sous ce magasin.",
  "robot.status.unbind.tip": "2, Déjà lié : le robot est actuellement lié à ce magasin, ces données correspondent aux données d'exploitation du magasin pour la période sélectionnée.",
  "cruise.tip.run.mileage": "Dans la période spécifiée, le kilométrage total parcouru en patrouille par tous les robots liés aux magasins développés par l'agent.",
  "cruise.tip.run.duration": "Durant la période indiquée, le temps total de fonctionnement en patrouille de tous les robots liés sous les magasins étendus par l'agent.",
  "cruise.tip.interaction.times": "Au cours de la période spécifiée, le nombre total d'interactions pour tous les robots liés aux magasins étendus par l'agent.",
  "cruise.tip.interaction.duration": "Durant la période indiquée, la durée totale d'interaction de tous les robots liés sous l'agence élargissant les magasins.",
  "delivery.tip.run.mileage": "Durant la période indiquée, le kilométrage total parcouru pour les livraisons par tous les robots liés aux magasins étendus par l'agent.",
  "delivery.tip.run.duration": "Durant la période indiquée, le temps total de fonctionnement des livraisons pour tous les robots liés aux magasins étendus par l'agent.",
  "delivery.tip.task.num": "Au cours de la période spécifiée, le nombre total de tâches exécutées par tous les robots liés au magasin.",
  "delivery.tip.delivery.tables": "Dans la plage de dates, le nombre de tables desservies par tous les robots liés aux magasins étendus par l'agent.",
  "delivery.tip.delivery.plates": "Durant la période indiquée, le nombre de plateaux de livraison de repas pour tous les robots liés aux magasins étendus par l'agent.",
  "greeter.tip.run.mileage": "Durant la période indiquée, le kilométrage total parcouru par tous les robots liés sous l'extension de la boutique par l'agent.",
  "greeter.tip.run.duration": "Durant la période indiquée, le temps total de fonctionnement des robots assignés dans tous les magasins étendus par l'agent.",
  "greeter.tip.task.times": "Durant la période indiquée, augmenter le nombre de missions d'attribution de places pour tous les robots liés aux magasins de l'agent.",
  "interaction.tip.all.times": "Durant la période indiquée, comptabiliser le nombre d'interactions homme-machine (toucher, interaction vocale) générées par tous les robots liés aux magasins étendus par l'agent.",
  "interaction.tip.voice.times": "Au cours de la période spécifiée, le nombre d'interactions vocales avec tous les robots liés aux magasins étendus par l'agent.",
  "interaction.tip.duration": "Durant la période indiquée, le temps total cumulé des interactions vocales pour tous les robots liés aux magasins étendus par l'agent.",
  "solicit.tip.duration": "Durant la période indiquée, la durée totale de fonctionnement des robots de prospection liés à tous les magasins étendus par l'agent.",
  "solicit.tip.hello.times": "Dans la période indiquée, le nombre de fois que les robots liés à tous les magasins étendus par l'agent disent bonjour.",
  "solicit.tip.reached.times": "Dans la période indiquée, le nombre de fois que les utilisateurs ont été contactés par tous les robots liés aux magasins étendus par l'agent.",
  "solicit.tip.attach.times": "Durant la période indiquée, l'agent développe tous les robots liés aux magasins pour atteindre les utilisateurs, et le nombre de personnes qui s'arrêtent et restent.",
  "solicit.tip.interation.times": "Durant la période indiquée, le nombre de fois que tous les robots liés aux magasins étendus par l'agent ont été activés par les utilisateurs.",
  "grid.click.times": "Au cours de la période indiquée, le nombre de fois où cette fonction a été cliquée parmi tous les robots liés aux magasins étendus par l'agent.",
  "ad.tiny.play.duration": "Durant la période indiquée, la durée de diffusion des publicités sur les petits écrans parmi tous les robots liés aux magasins étendus par l'agent.",
  "ad.tiny.play.times": "Durant la période indiquée, le nombre de fois où les publicités sur petit écran ont été diffusées sur tous les robots liés aux magasins étendus par l'agent.",
  "ad.large.play.duration": "Durant la période indiquée, pour toutes les machines robotiques liées sous les magasins élargis par l'agent, la durée de diffusion des publicités sur grand écran.",
  "ad.large.play.times": "Durant la période indiquée, le nombre de fois que les publicités sur grand écran ont été diffusées sur tous les robots liés aux magasins développés par l'agent.",
  "recycle.tip.mileage": "Durant la période indiquée, le kilométrage total parcouru par les robots liés dans tous les magasins développés par l'agent.",
  "recycle.tip.duration": "Durant la période indiquée, la durée totale de fonctionnement des robots liés à tous les magasins étendus par l'agent.",
  "recycle.tip.tables": "Au cours de la période indiquée, comptabiliser le nombre de fois que les tables ont été nettoyées par les robots liés dans tous les magasins étendus par l'agent.",
  "by.key": "Appuyez sur {touche}",
  "by.store": "Selon le magasin",
  "by.robot": "Selon la machine",
  "by.day": "selon le jour",
  "by.hour": "à l'heure",
  "export.config": "Exporter la configuration",
  "timeby.config.label": "Règles de configuration pour l'exportation des données par période de temps",
  "robot.sn_mac": "Numéro de série/MAC du robot",
  "dc.clean.area.total": "Surface totale à nettoyer (m²)",
  "dc.clean.area.total.tip": "Durant la période indiquée, la surface totale cumulée nettoyée par tous les robots liés aux magasins développés par l'agent.",
  "dc.clean.time.total": "Durée totale de nettoyage (h)",
  "dc.clean.time.total.tip": "Plage de dates, durée totale cumulée de nettoyage de tous les robots liés aux magasins développés par l'agent.",
  "dc.clean.task.number": "Nombre de tâches de nettoyage",
  "dc.clean.task.number.tip": "Durant la période indiquée, le nombre total de tâches de nettoyage effectuées par tous les robots liés aux magasins développés par l'agent.",
  "dc.power.consumption": "Consommation d'énergie (kWh)",
  "dc.power.consumption.tip": "Plage de dates, consommation d'électricité cumulée de tous les robots liés aux magasins développés par l'agent.",
  "dc.water.consumption": "Consommation d'eau (ml)",
  "dc.water.consumption.tip": "Durant la période indiquée, la consommation d'eau cumulée de tous les robots liés aux magasins développés par l'agent.",
  "dc.tab.all": "Tous les modes",
  "dc.tab.scrubbing": "mode de lavage du sol",
  "dc.tab.sweeping": "mode de balayage",
  "dc.sweep.vacuuming": "Tapis d'aspiration",
  "dc.sweep.dustpush": "Balai à poussière silencieux",
  "dc.delivery": "Livraison",
  "dc.clean": "Nettoyage",
  "dc.time": "temps",
  "dc.基本数据": "Données de base",
  "dc.清洁任务分布": "Tâches de nettoyage réparties",
  "dc.清洁任务分布描述": "Durant la période sélectionnée, le total des tâches exécutées par tous les robots liés au magasin, cumulé par heure de chaque jour naturel. (Exemple : si la période choisie est du 1er janvier au 2 janvier, et que des tâches sont exécutées de 1h00 à 2h00 le 1er janvier et à 1h00 le 2 janvier, alors le décompte des tâches pour 1h00 sera de 2, et pour 2h00 sera de 1.)",
  "dc.robot.delivery.tip": "Cette machine n'est pas un modèle de distribution.",
  "dc.robot.clean.tip": "Cette machine n'est pas un appareil de nettoyage.",
  "dc.store.unknow": "Désolé, le magasin n'a pas été trouvé.",
  "dc.mileage.tip": "Le kilométrage parcouru inclut uniquement les données de fonctionnement des robots de livraison et n'inclut pas les données de fonctionnement des robots de nettoyage.",
  "input.name.search": "Veuillez entrer {key} pour rechercher"
}