export default {
  "log.boot": "Démarrage de l'auto-test",
  "log.abnormal": "Défaillance anormale",
  "log.charge": "Journal de charge",
  "log.battery": "État de santé de la batterie",
  "production.date": "Date de création",
  "boot.status": "état",
  "boot.undetected": "Non détecté",
  "boot.normal": "normal",
  "boot.abnormal": "anormal",
  "key.no": "Numéro de série",
  "log.production.time": "Heure de création du journal",
  "log.push.time": "Heure de migration du journal vers le cloud",
  "boot.description": "description",
  "boot.check_module": "Module d'autocontrôle de l'état",
  "poweron.ratio": "Pourcentage de stockage (%)",
  "robot.softVer": "version du logiciel",
  "robot.hardVer": "Version du firmware",
  "common.systemid": "version du système d'exploitation",
  "common.battery": "Niveau de batterie actuel",
  "check.abnormal": "Présence d'anomalie",
  "check.normal": "Aucune anomalie",
  "error.category": "Type de panne",
  "error.detail": "Détails de la panne",
  "error.grade": "Niveau de panne",
  "error.list": "Liste des pannes",
  "error.ID": "ID de panne",
  "filter.more": "Plus de filtres",
  "charge.count_battery": "Quantité de charge électrique",
  "charge.count_time": "Durée de charge",
  "soh.battery_sn": "Numéro de série de la batterie",
  "soh.full": "Capacité de la batterie (mAh)",
  "soh.remaining": "Capacité restante (mAh)",
  "soh.battery_voltage": "Tension de la batterie (mV)",
  "soh.soh": "Indice de santé de la batterie",
  "soh.cycle": "Nombre de cycles",
  "soh.battery_type": "Type de batterie",
  "tip.soh": "Le journal sera rapporté uniquement lorsque ce champ change.",
  "key.clip": "Copie en un clic",
  "collapse": "Replier",
  "please.select": "Veuillez choisir",
  "please.input": "Veuillez entrer",
  "cycle.range.tip": "La plage de boucle n'a pas de données."
}