export default {
  "menu.dataCenter": "Centre de données",
  "menu.dataCenter.dashBoard": "Tableau de bord",
  "menu.dataCenter.operationAnalysis": "Analyse opérationnelle",
  "menu.dataCenter.operationAnalysis.aStoreOperations": "Classement des opérations en magasin",
  "menu.dataCenter.operationAnalysis.bStoreProduct": "Classement des opérations de produit",
  "menu.dataCenter.operationAnalysis.cAtiveProduct": "Analyse des produits actifs",
  "menu.dataCenter.operationAnalysis.sProductRoom": "Statistiques des tâches de livraison de produits",
  "menu.dataCenter.operationAnalysis.eProductBackPlate": "Statistiques des tâches de contre-offre de produits",
  "menu.dataCenter.operationAnalysis.fProductDisinfect": "Statistiques des tâches de désinfection des produits",
  "menu.dataCenter.operationAnalysis.gProductRunning": "Aperçu de l'exploitation du produit",
  "menu.dataCenter.operationAnalysis.hProductDaily": "Données quotidiennes moyennes du produit",
  "menu.dataCenter.operationAnalysis.iShopOperation": "Statistiques opérationnelles des magasins par créneau horaire",
  "menu.dataCenter.operationAnalysis.jProductGrameTime": "Statistiques opérationnelles par période de produit",
  "menu.dataCenter.operationAnalysis.kShopEverydayOperation": "Statistiques quotidiennes d'exploitation du magasin",
  "menu.dataCenter.operationAnalysis.LShopSevenOperation": "Statistiques opérationnelles moyennes sur sept jours des magasins",
  "menu.dataCenter.operationAnalysis.mProductEverydayOperation": "Statistiques quotidiennes d'exploitation du produit",
  "menu.dataCenter.operationAnalysis.nProductSevenOperation": "Statistiques des données opérationnelles du produit sept",
  "menu.dataCenter.operationAnalysis.VRobotTaskAnalysis": "Analyse des tâches des robots",
  "menu.reportLog": "Journal de rapport",
  "menu.reportLog.foodDelivery": "Mission de livraison de repas",
  "menu.reportLog.recycleDish": "Tâche de contre-offre",
  "menu.reportLog.disInfect": "Tâche de désinfection",
  "menu.reportLog.flashDelivery": "Tâche de livraison en chambre",
  "menu.reportLog.powerOn": "Démarrage de l'auto-test",
  "menu.reportLog.charge": "Journal de charge",
  "menu.reportLog.failure": "Défaillance anormale",
  "menu.reportLog.upgrade": "Rapport de mise à niveau",
  "menu.reportLog.batteryHealth": "État de santé de la batterie",
  "menu.reportLog.AbnormalIPAddr": "Enregistrement d'adresse IP anormale",
  "menu.reportLog.about2fall_report": "Journal de prévention des chutes",
  "menu.valueAdded": "Services à valeur ajoutée",
  "menu.valueAdded.custom": "Voix personnalisée V1.1",
  "menu.valueAdded.customV1": "Voix personnalisée V1.0",
  "menu.valueAdded.software": "Fonctionnalités du logiciel",
  "menu.valueAdded.tts": "Réponse TTS",
  "menu.valueAdded.sip": "Configuration du service de téléphonie SIP",
  "menu.account": "Gestion de compte",
  "menu.account.accountConfig": "Configuration du compte",
  "menu.systemManage.AccountOperationHistory": "Historique des opérations",
  "menu.AccountOperationHistory": "Historique des opérations",
  "menu.systemManage": "Gestion du système",
  "menu.systemManage.dictionaryManagement": "Gestion du dictionnaire",
  "menu.systemManage.messageNotification": "Notification de message",
  "menu.openPlatform": "Plateforme ouverte",
  "menu.openPlatform.applicationCenter": "Centre de demande",
  "menu.openPlatform.developDoc": "Document de développement",
  "menu.returnManage": "Retour à la gestion",
  "menu.returnManage.record": "Enregistrement de retour",
  "menu.returnManage.useReturn": "Utilisation du retour",
  "menu.customerCenter": "Centre de service clientèle",
  "menu.customerCenter.storeManagement": "Gestion de magasin",
  "menu.customerCenter.storeDetail": "Détails du magasin",
  "menu.customerCenter.bindRobots": "Lier le robot",
  "menu.customerCenter.bindARobot": "Ajouter un robot",
  "menu.customerCenter.storeRobotManagement": "Boutique de machines",
  "menu.customerCenter.activeCodeManagement": "Code d'activation",
  "menu.customerCenter.financialInstitution": "institution financière",
  "menu.customerCenter.financialDetail": "Détails de l'institution financière",
  "menu.customerCenter.agent": "Gestion des agents commerciaux",
  "menu.customerCenter.agentDetail": "Détails de l'agent",
  "menu.productCenter": "Centre de produits",
  "menu.productCenter.productArchives": "Dossier du produit",
  "menu.fileCenter": "Centre de documentation",
  "menu.fileCenter.mapFile": "Fichier de carte",
  "menu.fileCenter.formFile": "Document de réception",
  "menu.fileCenter.downloadFile": "Téléchargement de fichier",
  "menu.equipmentCenter": "Centre de produits",
  "menu.equipmentCenter.productArchives": "Dossier du produit",
  "menu.equipmentCenter.productLibrary": "Bibliothèque de produits mécaniques",
  "menu.equipmentCenter.outboundProducts": "Produits sortis de l'entrepôt pour les agents subalternes",
  "menu.equipmentCenter.viewProductInfo": "Voir les informations du produit",
  "menu.equipmentCenter.productEdit": "Informations de l'éditeur",
  "menu.equipmentCenter.installedProduct": "Produit installé",
  "menu.equipmentCenter.installedProducts": "Produit installé",
  "menu.equipmentCenter.flowCard": "Produit de carte de données liée",
  "menu.equipmentCenter.productDetail": "Détails du produit",
  "menu.equipmentCenter.productChangeRecord": "Registre des modifications du produit",
  "menu.equipmentCenter.product-change-records": "Enregistrement des modifications d'équipement",
  "menu.equipmentCenter.flowCardChangeRecord": "Enregistrement de modification de la carte de données",
  "menu.equipmentCenter.assignedProduct": "Produit de maintenance attribué",
  "menu.equipmentCenter.unallocatedProduct": "Produit de maintenance non attribué",
  "menu.equipmentCenter.antiSmuggling": "Contrôle des risques de fuite de marchandises",
  "menu.equipmentCenter.accessories": "Gestion des accessoires",
  "menu.welcome": "Bienvenue",
  "menu.more-blocks": "Plus de blocs",
  "menu.home": "Page d'accueil",
  "menu.admin": "Page de gestion",
  "menu.admin.sub-page": "Page de gestion de niveau deux",
  "menu.login": "Connexion",
  "menu.register": "Inscription",
  "menu.register.result": "Résultat de l'inscription",
  "menu.dashboard.analysis": "Page d'analyse",
  "menu.dashboard.monitor": "Page de surveillance",
  "menu.dashboard.workplace": "établi",
  "menu.exception.403": "403",
  "menu.exception.404": "404",
  "menu.exception.500": "cinq cents",
  "menu.form": "Page de formulaire",
  "menu.form.basic-form": "Formulaire de base",
  "menu.form.step-form": "Formulaire en plusieurs étapes",
  "menu.form.step-form.info": "Formulaire en plusieurs étapes (remplir les informations de virement)",
  "menu.form.step-form.confirm": "Formulaire en étapes (Confirmation des informations de virement)",
  "menu.form.step-form.result": "Formulaire en plusieurs étapes (Terminé)",
  "menu.form.advanced-form": "Formulaire avancé",
  "menu.list": "Page de liste",
  "menu.list.table-list": "Formulaire de requête",
  "menu.list.basic-list": "Liste standard",
  "menu.list.card-list": "Liste des cartes",
  "menu.list.search-list": "Liste de recherche",
  "menu.list.search-list.articles": "Liste de recherche (articles)",
  "menu.list.search-list.projects": "Liste de recherche (projets)",
  "menu.list.search-list.applications": "Liste de recherche (applications)",
  "menu.profile": "Page de détails",
  "menu.profile.basic": "Page de détails de base",
  "menu.profile.advanced": "Page de détails avancée",
  "menu.result": "Page de résultats",
  "menu.result.success": "Page de succès",
  "menu.result.fail": "Page d'échec",
  "menu.exception": "Page anormale",
  "menu.exception.not-permission": "403",
  "menu.exception.not-find": "404",
  "menu.exception.server-error": "cinq cents",
  "menu.exception.trigger": "Déclenchement d'une erreur",
  "menu.account.center": "Centre personnel",
  "menu.account.settings": "Paramètres personnels",
  "menu.account.trigger": "Déclenchement d'une erreur",
  "menu.account.logout": "Se déconnecter",
  "menu.editor": "Éditeur graphique",
  "menu.editor.flow": "Éditeur de processus",
  "menu.editor.mind": "Éditeur de carte mentale",
  "menu.editor.koni": "Éditeur topologique",
  "menu.test": "test",
  "menu.dataCenter.operationAnalysis.oFoodDelivery": "Service de livraison de produits Statistiques des données de table de restaurant",
  "menu.dataCenter.operationAnalysis.pReturnPlate": "Service de contre-offre de produits pour les statistiques de données de tables de restaurant",
  "menu.dataCenter.operationAnalysis.RCruiseMode": "Mode de croisière des données statistiques du produit",
  "menu.dataCenter.operationAnalysis.TSolicitCustomersMode": "Modèle d'attraction de clients pour les données statistiques du produit",
  "menu.dataCenter.operationAnalysis.SLeadmode": "Modèle de leadership produit pour la statistique des données",
  "menu.dataCenter.operationAnalysis.UAdPlayMode": "Statistiques de diffusion des publicités",
  "menu.customerCenter.rcagent": "Agent associé",
  "menu.customerCenter.equipment": "Équipement appartenant à",
  "menu.customerCenter.financialInfo": "Détails de l'institution de financement",
  "menu.reportLog.SIMCardLog": "Carte SIM de données",
  "menu.SIMCardMgr": "Gestion de la carte SIM de données",
  "menu.SIMCardMgr.ActivedCardMgr": "Carte SIM de données activée",
  "menu.SIMCardMgr.ExpiredCardMgr": "Avertissement d'expiration de la carte de données",
  "menu.BusinessDistrictMgr": "Gestion de zone commerciale",
  "menu.BusinessDistrictMgr.Add": "Nouveau",
  "menu.BusinessDistrictMgr.Edit": "Éditeur",
  "menu.BusinessDistrictMgr.Detail": "Consulter",
  "menu.dataCenter.dataOverview": "Aperçu des données",
  "menu.dataCenter.storeAnalysis": "Analyse du magasin",
  "menu.dataCenter.robotOperationAnalysis": "Analyse du fonctionnement des robots",
  "menu.dataCenter.robotTaskAnalysis": "Données de livraison par robot",
  "menu.dataCenter.cleanRobotData": "Nettoyage des données par robot",
  "menu.app-center": "Centre d'applications",
  "menu.app-center.emoticon-mgmt": "Gestion des expressions des robots",
  "menu.app-center.emoticon-add": "Création d'un pack d'émoticônes",
  "menu.app-center.emoticon-edit": "Éditer le pack d'émoticônes",
  "menu.app-center.voice-mgmt": "Gestion de la voix du robot",
  "menu.app-center.voice-add": "Création de packs de voix personnalisés",
  "menu.app-center.voice-edit": "Édition de packs de voix personnalisés",
  "menu.app-center.voice-auth": "Pack d'autorisation vocale",
  "menu.app-center.open-platform": "Plateforme ouverte",
  "menu.app-center.open-platform-detail": "Consulter",
  "menu.app-center.open-platform-add": "Demande d'application",
  "menu.app-center.open-platform-edit": "Éditer l'application",
  "menu.log-center": "Centre de journalisation",
  "menu.log-center.robot-logs": "Journal de robot",
  "menu.message-center": "Centre de notifications",
  "menu.message-center.message-detail": "Détails du message"
}