export default {
  "exception.monitor": "Surveillance des anomalies",
  "key.whitelist": "{key} liste blanche",
  "risk.control.settings": "Paramètres de contrôle des risques",
  "robot.run.district": "Zone d'exploitation",
  "robot.report.time.latest": "Dernière heure de rapport",
  "robot.lock.confirm": "Après l'exécution de l'opération de verrouillage, le robot ne pourra plus être utilisé, ni délié ni reassocié à un magasin.",
  "robot.lock.remark": "Informations de remarque sur le verrouillage de l'appareil",
  "robot.unlock.confirm": "Après avoir effectué l'opération de déverrouillage, le robot annulera l'alerte et reprendra un fonctionnement normal.",
  "robot.exception.view": "Consulter les détails de l'anomalie",
  "robot.info": "Informations sur le robot",
  "shop.info": "Informations sur le magasin",
  "robot.category": "Type de robot",
  "robot.smuggling.warning": "Alerte anormale, risque de marchandises en fuite.",
  "robot.run.location": "Position de fonctionnement",
  "key.remove": "Suppression",
  "time.add": "Ajouter l'heure",
  "use.instructions": "Mode d'emploi",
  "confirm.remove": "Après l'exécution de l'opération de suppression, la machine activera le mécanisme de contrôle des risques de \"protection contre la fuite de marchandises\".",
  "device.add": "Ajouter un appareil",
  "use.instruction.reason": "La raison pour laquelle la machine a été ajoutée à la liste blanche",
  "query.result": "Résultats de la recherche",
  "query.byMac": "Recherche d'adresse MAC",
  "base.version.No": "Numéro de version de référence",
  "key.auto.lock": "Verrouillage automatique {clé}",
  "district.china.mainland.outside": "Hong Kong, Macao, Taiwan et l'étranger",
  "district.china.mainland": "continent chinois",
  "key.enable": "Mise en service",
  "edit.risk.control.settings": "Modifier les paramètres de contrôle des risques",
  "robot.status.locked": "Appareil verrouillé",
  "robot.status.unlock": "Déverrouillé",
  "robot.sn/pid": "Numéro de série de l'équipement (PID)",
  "key.status": "{clé} état",
  "risk.control": "Contrôle des risques",
  "status.risk.control": "État du contrôle des risques",
  "status.robot": "État du robot",
  "status.abnormal.watning": "Alerte anormale",
  "datatype.nomal": "Données normales",
  "datatype.nomal.tip": "Inclus : les robots ajoutés à la liste blanche, les robots déverrouillés et les robots qui n'ont jamais déclenché de contrôle de risque de contrebande.",
  "datatype.abnomal": "données anormales",
  "opr.area": "{clé} zone d'exploitation",
  "goto.check": "Aller vérifier",
  "risk.control.notify": "Notification de contrôle des risques",
  "risk.control.warntip": "Les robots qui fonctionnent dans des zones non autorisées seront verrouillés après plusieurs déclenchements.",
  "abnormal.waning.robots": "Dispositif d'alerte d'anomalie",
  "etc.": "attendre",
  "robot.lock.switch": "Interrupteur de verrouillage",
  "robot.lock.auto": "Verrouillage automatique",
  "robot.lock.manual": "Verrouillage manuel",
  "abnormal.lock.robots": "Dispositif de verrouillage de contrôle du vent",
  "robot.lock.tip": "Déclenchement du contrôle des risques de marchandises en fuite, l'appareil est actuellement verrouillé, en cas de doute, veuillez contacter le personnel du service Purdu.",
  "warning.send.email": "Alerte de prévision d'anomalie par e-mail",
  "input.email.multiple": "Plusieurs adresses e-mail entrées sur des lignes séparées",
  "input.forExample": "Exemple :",
  "email.invalid": "Adresse e-mail non conforme",
  "PuduBot": "Plaisir d'offrir",
  "BellaBot": "Bella",
  "HolaBot": "D'accord",
  "Puductor": "Joie de consommer",
  "Puductor2": "Joyeux Pop 2",
  "KettyBot": "gourde",
  "FlashBot": "Boîte Éclair",
  "PuduCC1": "Hors de la poussière",
  "SwiftBot": "Livraison Astucieuse",
  "PuduBot2": "Joie 2",
  "PuduSH1": "lion-tigre"
}