export default {
  "productListIframe.无记录": "Aucun enregistrement",
  "productListIframe.厂测中": "En cours de test en usine",
  "productListIframe.厂测过期": "Date de péremption de l'usine",
  "productListIframe.已入库": "Déjà en stock",
  "productListIframe.未绑定": "Non lié",
  "productListIframe.未激活": "Non activé",
  "productListIframe.已激活": "Activé",
  "productListIframe.已冻结": "Gelé",
  "productListIframe.换板待验证": "Changement de carte en attente de vérification",
  "productListIframe.保内": "Préservation interne",
  "productListIframe.保外": "Hors de la garantie",
  "productListIframe.产品名称": "Nom du produit",
  "productListIframe.所属门店": "Magasin affilié",
  "productListIframe.所属代理": "Agence d'appartenance",
  "productListIframe.产品状态": "État du produit",
  "productListIframe.首次激活时间": "Date de première activation",
  "productListIframe.最新安装时间": "Dernière heure d'installation",
  "productListIframe.代理维保状态": "Statut de maintenance par procuration",
  "productListIframe.终端维保状态": "État de maintenance du terminal",
  "productListIframe.设备地址": "Adresse de l'appareil",
  "productListIframe.关闭": "Fermé",
  "productListIframe.没有更多了": "Il n'y a plus rien.",
  "productListIframe.加载中": "Chargement en cours",
  "productListIframe.请选择机器": "Veuillez choisir la machine.",
  "productListIframe.搜索": "Recherche",
  "productListIframe.清除筛选": "Effacer le filtre",
  "productListIframe.查看更多": "Voir plus",
  "productListIframe.完成": "Terminé"
}