export default {
  "请输入": "Veuillez entrer",
  "选择": "Sélection",
  "返回": "retour",
  "未绑定": "Non lié",
  "已安装": "Installé",
  "导入时间": "Heure d'importation",
  "代理名称": "Nom de l'agent",
  "所属代理": "Agence d'appartenance",
  "出库撤回": "Retrait du stock",
  "出库撤回说明": "Explication du retrait de l'inventaire",
  "撤回后下级代理": "Après la révocation, cet agent subalterne ne pourra plus voir ni opérer ce robot.",
  "出库撤回失败": "Échec du retrait de l'inventaire",
  "该代理已将机器人绑定门店": "L'agent a déjà lié le robot au magasin.",
  "出库至下级代理": "Sortie vers l'agent de niveau inférieur",
  "未选择下级代理商": "Non sélectionné d'agent subalterne",
  "没有出库产品": "Aucun produit n'a été sorti du stock.",
  "确定出库": "Confirmation de sortie",
  "出库说明": "Instructions de sortie",
  "选择未出库产品": "Sélectionner les produits non sortis du stock",
  "选择下级代理商": "Sélectionner un agent commercial subalterne",
  "代理商帐号": "Compte d'agent commercial",
  "注册地址": "adresse d'enregistrement",
  "销售区域": "Zone de vente",
  "注册时间": "Date d'inscription",
  "一级": "Niveau un",
  "二级": "niveau deux",
  "已损坏": "Endommagé",
  "已锁机": "Appareil verrouillé",
  "冻结中": "En cours de gel",
  "过期": "La vérification en usine a expiré.",
  "未激活": "Non activé",
  "激活": "Activation",
  "已激活": "Activé",
  "已入库": "Déjà en stock",
  "厂测中": "En cours de test en usine",
  "无记录": "Aucun enregistrement",
  "全部": "tous",
  "产品信息": "Informations sur le produit",
  "维保信息": "Informations de maintenance",
  "服务信息": "Informations sur le service",
  "产品操作记录": "Enregistrement d'opération du produit",
  "换板待验证": "Changement de carte en attente de vérification",
  "待验证": "À vérifier",
  "所属门店": "Magasin affilié",
  "所属代理商": "Agent affilié",
  "激活时间": "Date d'activation",
  "昵称": "surnom",
  "SN": "SN (PID)",
  "MAC": "MAC",
  "软件版本": "version du logiciel",
  "固件版本": "Version du firmware",
  "现场用途": "Utilisation sur site",
  "机器分组": "Groupe de machines",
  "用机类型": "type d'appareil",
  "保修时长": "Durée de la garantie",
  "实施工程师": "Ingénieur de mise en œuvre",
  "运维工程师": "Ingénieur de maintenance",
  "首次导入代理": "Première importation de proxy :",
  "绑定代理": "Liaison d'agent :",
  "的门店": "des magasins :",
  "从门店": "Depuis le magasin :",
  "解绑返回代理": "Dissocier, retourner au mandataire :",
  "代理": "Agent :",
  "出库产品到下级代理": "Produits sortis de l'entrepôt pour les agents subalternes :",
  "从下级代理": "Depuis l'agent subalterne :",
  "出库撤回到代理": "Sortie de stock retirée à l'agent :",
  "操作说明": "Instructions d'utilisation :",
  "操作人": "Opérateur :",
  "机器产品库使用提示": "La bibliothèque de produits mécaniques comprend les produits retournés à l'entrepôt après avoir été dissociés des magasins des commerçants ; ainsi que les produits déjà vendus et associés aux magasins des commerçants. Vous pouvez également expédier les produits \"non associés\" à vos agents de niveau inférieur.",
  "未綁定状态": "État non lié : robots qui ne sont pas liés à un magasin de commerçants et qui se trouvent encore dans l'état de l'entrepôt.",
  "功能介绍": "Présentation des fonctionnalités :",
  "冻结": "gelé",
  "取消冻结": "Annulation du gel",
  "未绑定状态描述": "Non lié : État où les produits sont sortis de l'entrepôt de l'entreprise Purdue vers l'inventaire de l'agent sans être vendus ou liés à un magasin spécifique.",
  "未激活状态描述": "Non activé : état dans lequel le robot est vendu et lié à un magasin physique par l'agent, mais le robot n'a pas été mis en marche et activé.",
  "已激活状态描述": "Activé : L'état dans lequel l'agent active les robots liés aux magasins pour les mettre en marche et les utiliser.",
  "已冻结状态描述": "Gelé : État du robot après que l'agent l'ait gelé, dans cet état, le robot ne pourra plus être utilisé.",
  "换板待验证状态描述": "En attente de vérification du changement de carte mère : état pendant le processus de remplacement lorsque la carte mère du robot est endommagée.",
  "还剩": "Il reste",
  "个月": "mois",
  "系统操作": "Opération du système",
  "租赁时长": "Durée de location",
  "试用时长": "durée d'essai",
  "试用截止时间": "Date limite d'essai",
  "门店安装时间": "Heure d'installation du magasin",
  "备件信息": "Informations sur les composants",
  "备件类型": "Type de pièce détachée",
  "导出全部": "Exporter tout",
  "供应商": "fournisseur",
  "型号": "modèle",
  "上报时间": "Heure de rapport",
  "电池": "batterie",
  "雷达": "radar",
  "相机": "appareil photo",
  "核心板": "Carte mère",
  "屏幕": "écran",
  "充电器": "Chargeur",
  "功能板": "Version fonctionnelle",
  "上位机": "Ordinateur hôte"
}