export default {
  "app.setting.pagestyle": "Configuration du style général",
  "app.setting.pagestyle.dark": "Style de menu sombre",
  "app.setting.pagestyle.light": "Style de menu aux couleurs vives",
  "app.setting.content-width": "Zone de largeur de contenu",
  "app.setting.content-width.fixed": "largeur fixe",
  "app.setting.content-width.fluid": "fluide",
  "app.setting.themecolor": "Couleur principale",
  "app.setting.themecolor.dust": "Crépuscule",
  "app.setting.themecolor.volcano": "volcan",
  "app.setting.themecolor.sunset": "Crépuscule",
  "app.setting.themecolor.cyan": "Bleu Ming",
  "app.setting.themecolor.green": "aurore verte",
  "app.setting.themecolor.daybreak": "Bleu aube (par défaut)",
  "app.setting.themecolor.geekblue": "Geek Bleu",
  "app.setting.themecolor.purple": "sauce pourpre",
  "app.setting.navigationmode": "Mode de navigation",
  "app.setting.sidemenu": "Disposition du menu latéral",
  "app.setting.topmenu": "Disposition du menu supérieur",
  "app.setting.fixedheader": "En-tête fixe",
  "app.setting.fixedsidebar": "Menu latéral fixe",
  "app.setting.fixedsidebar.hint": "La disposition du menu latéral peut être configurée",
  "app.setting.hideheader": "Masquer l'en-tête lors du défilement vers le bas",
  "app.setting.hideheader.hint": "Configuration possible lors de la fixation de l'en-tête",
  "app.setting.othersettings": "Autres paramètres",
  "app.setting.weakmode": "Mode faible en couleurs",
  "app.setting.copy": "Paramètres de copie",
  "app.setting.copyinfo": "Copie réussie, veuillez remplacer la configuration par défaut dans src/defaultSettings.js",
  "app.setting.production.hint": "La barre de configuration est utilisée uniquement pour l'aperçu dans l'environnement de développement et ne sera pas affichée dans l'environnement de production, veuillez copier et modifier manuellement le fichier de configuration après."
}