export default {
  "app.settings.menuMap.basic": "Paramètres de base",
  "app.settings.menuMap.security": "Paramètres de sécurité",
  "app.settings.menuMap.binding": "Compte lié",
  "app.settings.menuMap.notification": "Nouvelle notification de message",
  "app.settings.basic.avatar": "Avatar",
  "app.settings.basic.change-avatar": "Changer l'avatar",
  "app.settings.basic.email": "boîte mail",
  "app.settings.basic.email-message": "Veuillez entrer votre adresse e-mail !",
  "app.settings.basic.nickname": "surnom",
  "app.settings.basic.nickname-message": "Veuillez entrer votre surnom !",
  "app.settings.basic.profile": "Profil personnel",
  "app.settings.basic.profile-message": "Veuillez entrer une brève description de vous-même !",
  "app.settings.basic.profile-placeholder": "Profil personnel",
  "app.settings.basic.country": "Pays/Région",
  "app.settings.basic.country-message": "Veuillez entrer votre pays ou région !",
  "app.settings.basic.geographic": "province ou ville de résidence",
  "app.settings.basic.geographic-message": "Veuillez entrer votre province et ville !",
  "app.settings.basic.address": "Adresse de la rue",
  "app.settings.basic.address-message": "Veuillez entrer votre adresse de rue !",
  "app.settings.basic.phone": "numéro de contact",
  "app.settings.basic.phone-message": "Veuillez entrer votre numéro de téléphone !",
  "app.settings.basic.update": "Mettre à jour les informations de base",
  "app.settings.security.strong": "fort",
  "app.settings.security.medium": "milieu",
  "app.settings.security.weak": "faible",
  "app.settings.security.password": "mot de passe du compte",
  "app.settings.security.password-description": "La force du mot de passe actuel",
  "app.settings.security.phone": "téléphone de sécurité",
  "app.settings.security.phone-description": "Téléphone déjà lié",
  "app.settings.security.question": "Question de sécurité",
  "app.settings.security.question-description": "Les questions de sécurité ne sont pas définies, elles peuvent protéger efficacement la sécurité de votre compte.",
  "app.settings.security.email": "Adresse e-mail secondaire",
  "app.settings.security.email-description": "Adresse e-mail déjà liée",
  "app.settings.security.mfa": "Dispositif MFA",
  "app.settings.security.mfa-description": "Appareil MFA non lié, une fois lié, vous pourrez effectuer une confirmation secondaire.",
  "app.settings.security.modify": "Modification",
  "app.settings.security.set": "Paramètres",
  "app.settings.security.bind": "Liaison",
  "app.settings.binding.taobao": "Liaison avec Taobao",
  "app.settings.binding.taobao-description": "Actuellement, aucun compte Taobao n'est lié.",
  "app.settings.binding.alipay": "Lier Alipay",
  "app.settings.binding.alipay-description": "Actuellement, aucun compte Alipay n'est lié.",
  "app.settings.binding.dingding": "Lier DingTalk",
  "app.settings.binding.dingding-description": "Actuellement, aucun compte DingTalk n'est lié.",
  "app.settings.binding.bind": "Liaison",
  "app.settings.notification.password": "mot de passe du compte",
  "app.settings.notification.password-description": "Les messages des autres utilisateurs vous seront notifiés sous forme de message interne.",
  "app.settings.notification.messages": "Message système",
  "app.settings.notification.messages-description": "Les messages système seront notifiés sous forme de message interne.",
  "app.settings.notification.todo": "Tâches à faire",
  "app.settings.notification.todo-description": "Les tâches à faire seront notifiées sous forme de message interne.",
  "app.settings.open": "ouvert",
  "app.settings.close": "clé",
  "robot.check.blacklist": "L'adresse MAC a été ajoutée à la liste noire, veuillez contacter la société Purdue pour le traitement."
}