export default {
  "language.select.label": "Sélectionner la langue",
  "voice.add": "Ajouter de la voix",
  "voice.category": "Catégorisation vocale",
  "voice.mp3": "Fichier audio vocal",
  "voice.mp3.del.confirm": "En supprimant cette voix, les packs de voix personnalisés ajoutés par la suite n'incluront plus la voix de cette scène.",
  "voice.language": "langue parlée",
  "voice.id.correct.tip": "Veuillez remplir le bon VoiceID de robot, sinon il ne pourra pas être diffusé.",
  "voice.display.scene.desc": "Scénario de synthèse vocale",
  "voice.display.content": "Contenu du texte de l'annonce vocale",
  "voice.upload.limit": "Prise en charge de l'envoi de fichiers MP3 jusqu'à 1 Mo.",
  "voice.pkg.desc": "Description du pack vocal",
  "voice.access": "Robot autorisé",
  "voice.pkg.auth": "Pack d'autorisation vocale",
  "key.agent.name": "agent commercial",
  "key.auth.add": "Ajouter une autorisation",
  "key.batch.replace": "Remplacement en masse",
  "key.robot.category": "Type de robot",
  "key.robot.No": "robots numériques",
  "voice.all": "Tous les audios",
  "voice.merge.submit": "Synthèse vocale et accomplissement",
  "voice.merge.submit.failed": "La mise à jour du pack vocal a échoué",
  "voice.change.mp3": "Remplacer l'audio",
  "voice.validity.period.tip": "Veuillez sélectionner la date d'expiration",
  "voice.authorized.mac.tip": "Attribuer ce pack vocal au robot {robot} ci-dessous.",
  "voice.authorized.store.tip": "Attribuer ce pack vocal aux robots {robot} des magasins suivants",
  "voice.authorized.agent.tip": "Attribuer ce pack vocal à tous les magasins sous l'agence pour le robot {robot}.",
  "voice.voiceid.notmatch": "Le nom du fichier ne correspond à aucun VoiceID.",
  "voice.filesize.exceed": "La taille du fichier dépasse la limite autorisée.",
  "voice.upload.warning1": "Il est nécessaire de compresser les fichiers à l'intérieur du dossier, pas besoin de compresser le dossier lui-même.",
  "voice.upload.warning2": "Le nom de l'audio doit être l'ID vocal correspondant au type de produit robotique.",
  "voice.upload.warning3": "Prend en charge jusqu'à 200 fichiers audio mp3 et ne dépasse pas 200 Mo.",
  "voice.upload.warning4": "En raison de la taille importante du fichier, il est interdit de quitter pendant le processus de téléchargement.",
  "not.your.robot": "Ce n'est pas le robot de votre inventaire.",
  "key.limit.import.count": "Limitez à {key} individus.",
  "navBar.lang": "langage"
}