export default {
  "联系邮箱": "Kontakt-E-Mail",
  "代理商等级": "Agenturstufe",
  "上级代理商": "Oberagent",
  "重置密码": "Passwort zurücksetzen",
  "新密码": "Neues Passwort",
  "操作成功": "Vorgang erfolgreich",
  "操作失败": "Betriebsfehler",
  "共n条记录": "Insgesamt {total} Einträge",
  "是否前往": "Konto erfolgreich hinzugefügt, bitte gehen Sie zum \"Kundencenter\", um die Grundinformationen des Agenten zu ergänzen.",
  "未添加无法登录": "Tipps: Wenn die Basisinformationen des Agenten nicht hinzugefügt wurden, kann das Konto nicht verwendet werden, um sich in das System einzuloggen.",
  "立即前往": "Sofort hingehen",
  "查看账号": "Kontoinformationen überprüfen",
  "生成新密码": "Klicken Sie hier, um ein neues Passwort zu generieren.",
  "随机密码": "Zufälliges Passwort",
  "更换密码": "Passwort ändern",
  "复制密码": "Kopieren Sie das Passwort",
  "已复制！": "Bereits kopiert!",
  "图片裁剪": "Bildzuschneiden",
  "获取文件md5出错": "Die MD5-Datei konnte nicht abgerufen werden.",
  "oss删除文件失败": "Löschen der Datei in OSS fehlgeschlagen",
  "视频个数超出限额": "Die Anzahl der Videos überschreitet das Limit.",
  "素材类型不正确": "Das Format des Materials ist nicht korrekt.",
  "图片过大": "Das Bild ist zu groß.",
  "视频过大": "Das Video ist zu groß.",
  "分辨率超出": "Die Auflösung übersteigt {height}P",
  "账号不能包含空格": "Das Konto darf keine Leerzeichen enthalten.",
  "账号已存在": "Das Konto existiert bereits.",
  "请设置密码": "Bitte legen Sie ein Passwort fest.",
  "密码规则": "Groß- und Kleinbuchstaben, Zahlen, Kombination aus drei beliebigen Sonderzeichen",
  "agent.store.info": "Es wird nur die Anzahl der von dem aktuellen Vertreter erweiterten Filialen gezählt, nicht die Anzahl der Filialen von untergeordneten Vertretern.",
  "account.noOrg.warning": "Das Konto hat keine Informationen zum Vertriebspartner ergänzt, bitte kontaktieren Sie den Ersteller Ihres Kontos, um dies zu bearbeiten.",
  "login.redirect": "Sie werden nach {keyProp} Sekunden zur Seite \"Händlerverwaltungsplattform\" weitergeleitet.",
  "login.suc": "Anmeldung erfolgreich",
  "login.fail": "Anmeldefehler",
  "enter.nowait": "Kein Warten erforderlich, klicken Sie hier, um einzutreten.",
  "agent.type": "Agenturtypen",
  "请勿输入非法字符": "Bitte geben Sie keine illegalen Zeichen ein."
}