export default {
  "中国港澳台及海外地区": "China, Hongkong, Macau, Taiwan und Überseegebiete",
  "中国大陆地区": "Festlandchina",
  "代理商类型": "Agenturtypen",
  "类型": "Typ",
  "请选择代理商类型": "Bitte wählen Sie den Typ des Handelsvertreters aus.",
  "运营区域": "Verkaufsbereich",
  "请选择可销售的区域": "Bitte wählen Sie den verfügbaren Verkaufsbereich aus.",
  "新增代理商": "Neuer Vertriebspartner",
  "一级代理商": "Hauptvertreter",
  "二级代理商": "Sekundärhändler",
  "一级": "Erstklassig",
  "二级": "Sekundär",
  "代理账号": "Agentenkonto",
  "公司所在地": "Firmensitz",
  "注册时间": "Registrierungszeit",
  "注册地区": "Registrierungsgebiet",
  "销售区域": "Verkaufsgebiet",
  "上级代理商名称": "Name des übergeordneten Vertriebspartners",
  "拓展门店数": "Erweiterung der Anzahl der Filialen",
  "激活绑定数": "Aktivierte Anzahl/Gebundene Geräteanzahl",
  "前往文件中心": "Gehe zum \"Dokumentenzentrum\"",
  "知道了": "Ich habe verstanden.",
  "结束日期": "Enddatum",
  "开始日期": "Startdatum",
  "公司所在地不完整": "Die Adresse des Unternehmens ist unvollständig.",
  "请输入纯数字": "Bitte geben Sie die Telefonnummer als reine Ziffern ein."
}