export default {
  "open.platform.title": "PUDU Offene Plattform",
  "open.platform.desc": "Die Purdue-Open-Plattform kann Entwicklern von Roboter-Geschäften offene Software- und Hardware-Dienste zur Verfügung stellen. Mit Hilfe der Purdue-Open-Plattform können Entwickler die vollen Funktionen von Robotern nutzen, Roboter mit verschiedenen Branchen kombinieren, von Grund auf mit der Entwicklung von Roboter-Geschäften beginnen und unbegrenzte Möglichkeiten für Projekte schaffen.",
  "H-C.interaction": "Mensch-Maschine-Interaktion",
  "navigation.control": "Navigationskontrolle",
  "voice.play": "Sprachausgabe",
  "full.amount.data": "Gesamtdatenmenge",
  "view.api.doc": "Betrachten Sie die offene API-Dokumentation.",
  "know.detail": "Verstehen Sie die Details",
  "apply.sdk": "Bewerbung um Remote Control SDK",
  "apply.agent": "Bewerbung als Vertreter",
  "apply.people": "Antragsteller",
  "apply.email": "Antragsteller E-Mail",
  "apply.purpose": "Bewerbungszweck",
  "device.id": "Geräte-ID",
  "device.secret": "Schlüssel",
  "app.secret": "Anwendungsschlüssel",
  "apply.time": "Bewerbungszeitraum",
  "applicant.info": "Antragstellerinformationen",
  "receive.email": "Empfangspostfach",
  "apply.app.info": "Anwendungsinformationen beantragen",
  "applicable.stores": "Anwendbare Geschäfte",
  "app.stores.tip": "Wählen Sie das Geschäft aus, zu dem der fernzusteuernde Roboter gehört.",
  "apply.functions": "Anwendungsfunktion",
  "apply.desc": "Sie bewerben sich um das \"Remote Control Open SDK\", mit dem Entwickler auf ihrer eigenen Plattform die offenen Fähigkeiten dieses SDKs nutzen können, um Roboter in den Filialen aus der Ferne zu steuern.",
  "api.doc.desc": "Fernsteuerung Open-SDK-Dokumentation",
  "api.sdk.download": "Nach der Überprüfung kann heruntergeladen werden.",
  "openplatform.email": "Purdue Entwickler-Fragen E-Mail",
  "email.input.tip": "Bitte unbedingt korrekt ausfüllen, wird verwendet, um den Schlüssel und SDK-Informationen nach Genehmigung der Anwendung zu erhalten.",
  "approved.tip": "Die Bearbeitung der App-Informationen wird direkt wirksam, eine erneute Überprüfung ist nicht erforderlich.",
  "regionId.diff.tip": "Die Ursprungsadresse des Geschäfts ist unterschiedlich.",
  "voice.play.mgt": "Sprachausgabe-Verwaltung",
  "voice.play.subtitle": "Individuelle Konfiguration der Sprachansagen für verschiedene Szenarien, wie Kundengewinnung, Promotion und Kundenbindung, macht den Roboter zu einem professionelleren Marketingexperten.",
  "emoticon.interface.mgt": "Emoticon-Oberflächenverwaltung",
  "emoticon.interface.subtitle": "Individuelle Einstellungen für verschiedene interessante und unterhaltsame Roboter-Emojis, um den Roboter für Kunden attraktiver zu machen.",
  "open.platform.subtitle": "Roboter-Vollketten-Technologiefähigkeiten werden geöffnet, um Entwicklern zu helfen, Anwendungen in allen Branchenszenarien zu realisieren.",
  "emo.pack.name": "Emoticon-Paketname",
  "emo.pack.create": "Erstellen eines benutzerdefinierten Emoticon-Pakets",
  "apply.scope": "Anwendungsbereich",
  "opr.steps": "Bedienungsschritte",
  "opr.steps.sub": "Es ist unbedingt erforderlich, die Schritte zu befolgen, sonst wird die Einrichtung fehlschlagen.",
  "steps.1": "Schritt 1",
  "steps.1.desc": "Laden Sie die aktuelle Emoji-Paketdatei des Roboters herunter",
  "steps.2": "Schritt 2",
  "steps.2.desc": "Ersetzen Sie die vorhandenen Dateien nacheinander durch neue Emoji-Dateien.",
  "steps.2.desc.ketty": "Kürbis beinhaltet 2 Gruppen von Emoticons: \"double_eye\" und \"single_eye\". Wählen Sie eine Gruppe von Emoticons aus, um sie zu ersetzen, und verwenden Sie die \"neue Emoticon-Datei\", um eine Gruppe von Emoticons in den Ordnern \"animation\" und \"firstImage\" zu ersetzen.",
  "steps.2.ps1": "Die Hierarchie, Benennung und Anzahl der Ordner und Dateien müssen streng beibehalten werden.",
  "steps.2.ps2": "2. Die Bildauflösung beträgt 1920*1200 Pixel, das Format ist .png; das Format für Emojis ist .mp4; der gesamte Ordner darf nicht größer als 50MB sein.",
  "steps.2.ps2.ketty": "2. Das erste Bild hat eine Auflösung von 1280*800, ist im .png-Format und unter 100KB; das Format der Emoticon-Animation ist .mp4, mit einer Auflösung von 1280*800 und unter 4MB.",
  "steps.3": "Schritt 3",
  "steps.3.desc": "Alle Emoticon-Dateien auswählen, zu einer .zip-Datei komprimieren und hochladen.",
  "steps.3.desc.ps": "Es dürfen keine übergeordneten Ordner zum Komprimieren eingebettet werden.",
  "emo.info": "Emoticon-Paketinformationen",
  "key.emo.use.tip": "Dieser Sticker-Pack ist nur für das {key} Modell gültig.",
  "emo.upload": "Hochladen von Emoticon-Paketen",
  "upload.del.confirm": "Die Datei wird dauerhaft gelöscht. Möchten Sie das bestätigen?",
  "scope.agent": "Alle Roboter",
  "key.scope.agent": "Alle {key} Roboter",
  "scope.store": "Ausgewählte Filialen aller Roboter",
  "scope.robot": "Bestimmter Roboter",
  "emo.upload.tip": "Bitte laden Sie eine ZIP-Datei hoch, die insgesamt 50 MB oder weniger umfasst.",
  "emo.step.info.1": "Gemäß dem emo-Ordner schrittweise die Emoticon-Dateien ersetzen.",
  "emo.step.info.2": "Die Hierarchie der Ordner, die Namen der Ordner und Dateien dürfen nicht geändert werden.",
  "emo.step.info.3": "Die Datei darf nicht größer als 50 MB sein, die Bildauflösung beträgt 1920*1200 Pixel, das Format für Emoticons ist MP4.",
  "emo.step.info.4": "Emoticon-Dateien für Freude, Ärger, Trauer, Vergnügen, linkes und rechtes Ohr usw., insgesamt 14 MP4 + 1 PNG-Platzhalterbild (ohne Platzhalterbild kann das Wechseln der Emoticons zu einem schwarzen Bildschirm führen)",
  "imp.robots.step1": "Vorlage herunterladen",
  "imp.robots.step2": "MAC in die Vorlage einfügen",
  "not.in.stock": "Nicht auf Lager",
  "key.not": "Nicht {key}",
  "del.emoji.tip": "Nach dem Löschen wird das von dem Roboter bereits verwendete Stickerpaket nicht beeinträchtigt.",
  "store.list": "Ladenliste",
  "robot.list": "Roboterliste",
  "name.repeat": "Name doppelt",
  "record.repeat": "Es gibt doppelte Einträge.",
  "zip.content.abnormal": "Die Emoticon-Paketdatei wurde nicht wie gefordert komprimiert.",
  "scop.tip1": "1. Alle: {key} wird an alle Roboter unter dem Agenten gepusht. Neu gebundene Roboter erhalten automatisch {key}.",
  "scop.tip2": "2. Nach Geschäft: {key} wird nur an Roboter gesendet, die dem ausgewählten Geschäft zugeordnet sind. Wenn ein neuer Roboter an das ausgewählte Geschäft gebunden wird, erhält dieser automatisch {key}.",
  "scop.tip3": "3. Nach Maschine: {key} wird nur an ausgewählte Roboter gesendet.",
  "emoji.pkg": "Emoticon-Pack",
  "voice.pkg": "Sprachpaket",
  "key.voice.use.tip": "Dieses Sprachpaket ist nur für das {key} Modell gültig.",
  "voice.del.tip": "Nach dem Löschen wird in diesem Szenario kein Sprachinhalt mehr abgespielt.",
  "batch.step1": "Herunterladen der VoiceID und der Excel-Tabelle zum Abgleich von Sprachausgabeszenarien",
  "batch.step2": "Gemäß der \"VoiceID- und Szenenvergleichstabelle\" benennen Sie die benutzerdefinierten Sprach-MP3-Dateinamen nacheinander in die entsprechende VoiceID um.",
  "batch.step2.ps1": "1) Stellen Sie unbedingt sicher, dass jede Sprachdatei den richtigen VoiceID-Namen hat, sonst wird das Hochladen fehlschlagen.",
  "batch.step3": "Nachdem alle benutzerdefinierten Sprachdateien in einen Ordner gelegt wurden, wählen Sie den Ordner für das Hochladen im Batch aus.",
  "batch.step3.ps1": "1) Achten Sie darauf, den Ordner nicht zu komprimieren.",
  "batch.step3.ps2": "2) Es können maximal 300 Audiodateien pro Upload hochgeladen werden, jede Datei darf nicht größer als 3MB sein.",
  "batch.btn": "Wählen Sie den Upload-Ordner aus",
  "file.type.error": "Falscher Dateityp",
  "count.limit": "Die Anzahl der Dokumente überschreitet das {key}-Limit.",
  "wrong.file.type": "Falscher Dateityp",
  "file.size.exceeds": "Die Dateigröße überschreitet das {key}-Limit.",
  "voice.packing.tip": "Bitte schließen Sie die Seite nicht, die Sprachpaketsynthese läuft...",
  "business.district.desc": "Roboter, die in Geschäftsvierteln eingesetzt werden, können Speisen von mehreren Geschäften liefern."
}