export default {
  "bd.account": "Konto",
  "bd.username": "Name",
  "bd.role": "Charakter",
  "bd.name": "Geschäftsviertelname",
  "bd.numOfStores": "Anzahl der Filialen",
  "bd.createtime": "Erstellungszeit",
  "bd.updatetime": "Aktualisierungszeit",
  "bd.operation": "Bedienung",
  "bd.check": "Betrachten",
  "bd.edit": "Redakteur",
  "bd.qrcode": "Laden Sie den QR-Code herunter",
  "bd.new": "Neuzugang",
  "bd.goback": "Rückkehr",
  "bd.account.placeholder": "Bitte geben Sie das Konto ein.",
  "bd.name.placeholder": "Bitte geben Sie den Namen des Geschäftsviertels ein.",
  "bd.inquire": "Anfrage",
  "bd.reset": "Zurücksetzen",
  "bd.store.tip": "Bitte wählen Sie ein Geschäft aus.",
  "bd.store.placeholder": "Bitte geben Sie Ihren Namen ein.",
  "bd.map.tip": "Bitte wählen Sie die Karte.",
  "bd.store.order": "Seriennummer",
  "bd.store.name": "Geschäftsname",
  "bd.store.label": "Auswahl des Geschäfts",
  "bd.map.label": "Auswahl der Karte",
  "bd.map.name": "Kartenname",
  "bd.map.uploadtype": "Hochladetyp",
  "bd.map.association": "Verwandte Produktanzahl",
  "bd.map.version": "Version",
  "bd.map.using": "In Benutzung",
  "bd.map.unused": "Nicht verwendet",
  "bd.map.uploadtype.apk": "APK-Upload",
  "bd.map.uploadtype.platform": "Plattform-Upload",
  "bd.map.choose": "Auswahl",
  "bd.store.industry": "Branche",
  "bd.store.address": "Ladenadresse",
  "bd.store.normal": "Normal",
  "bd.store.logout": "Abmeldung",
  "bd.insiders.noOperatingAuthority": "Interne Mitarbeiter haben keine Betriebsberechtigung!",
  "bd.store.reminder": "Hinweis: Es wird nur die Auswahl von Geschäften im \"normalen\" Zustand unterstützt."
}