export default {
  "component.tagSelect.expand": "Entfalten",
  "component.tagSelect.collapse": "Einklappen",
  "component.tagSelect.all": "Alles",
  "key.select.max": "Wählen Sie maximal {key} Roboter aus",
  "trial.period.day": "Probephase/Tage",
  "lease.cycle.month": "Mietdauer/Monat",
  "required.warn": "Sie müssen erforderliche Angaben ausfüllen.",
  "first.imp.time": "Erstmaliges Importdatum",
  "validate.robot.key.warn": "Bitte geben Sie die vollständige SN (PID) oder MAC ein.",
  "change.to.complex.query": "Wechseln Sie zur erweiterten Suche.",
  "change.to.simple.query": "Wechseln Sie zur einfachen Suche.",
  "openapi.docs": "API-Entwicklungsdokumentation",
  "customer.name": "Händlername",
  "key.template": "Vorlage",
  "confirm.file.upload": "Bitte bestätigen Sie, ob die Datei vollständig hochgeladen wurde.",
  "upload.fail": "Hochladen fehlgeschlagen, bitte versuchen Sie es erneut.",
  "key.success": "Erfolg",
  "key.fail": "Versagen",
  "import.result": "Importergebnis",
  "incompatibility.versions": "Die neue Version ist nicht mit der alten Version kompatibel.",
  "auto.jump.available": "Wird automatisch auf verfügbare Version umgeleitet...",
  "import.maxcount.tip": "Es wurden mehr als {count} MAC-Adressen erkannt. Das System hat nur die ersten {count} MAC-Adressen importiert. Bitte importieren Sie die restlichen MAC-Adressen erneut."
}