export default {
  "dc.total": "Insgesamt",
  "dc.yesterday": "Gestern",
  "dc.last7days": "In den letzten 7 Tagen",
  "dc.last30days": "In den letzten 30 Tagen",
  "dc.naturalDay": "Natürlicher Tag",
  "dc.natureWeek": "Natürliche Woche",
  "dc.naturalMonth": "Kalendermonat",
  "dc.chainRatio": "Monat zu Monat",
  "dc.cumulativeNumber": "Kumulierte Anzahl",
  "dc.activeRate": "Aktivitätsrate",
  "dc.robotOperationOverview": "Überblick über den Maschinenbetrieb",
  "dc.workTime": "Arbeitszeit",
  "dc.runningMileage": "Betriebskilometer",
  "dc.taskTimes": "Ausführung von Aufgaben",
  "dc.robotRunningPeakTrend": "Roboterbetrieb Hochkonjunkturtrend",
  "dc.monthOnMonth": "Gleichzeitiger Monat-zu-Monat Vergleich",
  "dc.numberOfRobotRuns": "Roboterbetriebszahlen",
  "dc.stages": "{num} Geräte",
  "dc.robotOverview": "Maschinenübersicht",
  "dc.powerOnRobot": "Einschalten des Roboters",
  "dc.bindTheRobot": "Gebundener Roboter",
  "dc.activateRobot": "Aktiviere den Roboter",
  "dc.numberOfRobotsBound": "Gebundene Maschinenanzahl",
  "dc.numberOfActiveRobots": "Aktivierte Maschinenanzahl",
  "dc.storeOverview": "Geschäftsübersicht",
  "dc.numberOfActiveStores": "Aktive Geschäftsanzahl",
  "dc.numberOfNewStores": "Neue Filialanzahl",
  "dc.activeStore": "Aktive Geschäfte",
  "dc.silentStore": "Stilles Geschäft",
  "dc.activeRobotPoweredOn": "Einschalten des aktiven Roboters",
  "dc.downtime": "Betriebsdauer einstellen",
  "dc.operatingHours": "Betriebsstunden",
  "dc.emptyActiveStore": "Derzeit keine aktiven Filialen",
  "dc.emptySilentStore": "Vorübergehend keine Silent-Filialen",
  "dc.export": "Exportieren",
  "dc.addStore": "Neueröffnung des Geschäfts",
  "dc.cumulativeStores": "Akkumulierte Filialen",
  "dc.storeName": "Geschäftsname",
  "dc.storeNamePlaceholder": "Bitte geben Sie den Namen des Geschäfts ein.",
  "dc.query": "Anfrage",
  "dc.activeRank": "Aktive Rangliste",
  "dc.creationTime": "Erstellungszeit",
  "dc.activeRobot": "Einschalten des Roboters",
  "dc.runTime": "Betriebsdauer",
  "dc.key.robot": "Roboter",
  "dc.key.boottime": "Einschaltzeit",
  "dc.key.starttime": "Beginn der Laufzeit",
  "dc.task.number": "Aufgabenanzahl",
  "dc.robots.all": "Alle Roboter",
  "dc.robot.select": "Bitte wählen Sie den Roboter aus.",
  "dc.tab.delivery": "Lieferdaten",
  "dc.tab.cruise": "Kreuzfahrtdaten",
  "dc.tab.greeter": "Platzierungsdaten",
  "dc.tab.interaction": "Interaktionsdaten",
  "dc.tab.solicit": "Kundendaten",
  "dc.tab.grid": "Palastgitter-Daten",
  "dc.tab.ad": "Werbungsdaten",
  "dc.tab.recovery": "Gegenangebot Daten",
  "dc.mileage": "Betriebskilometer",
  "dc.runtime": "Betriebsdauer",
  "dc.interactiveVisits": "Interaktionshäufigkeit",
  "dc.interactionTime": "Interaktionsdauer",
  "dc.greetings": "Begrüßungsanzahl",
  "dc.reached": "Berührungspunkte",
  "dc.attract": "Anziehungskraft",
  "dc.voiceInteractions": "Sprachinteraktionsanzahl",
  "dc.voiceinteractionTime": "Sprachinteraktionsdauer",
  "dc.takeMeInCount": "\"Bring mich in den Laden\" Art von Raster",
  "dc.featuredItemCount": "\"Besondere Produkte\" Kategorie Raster",
  "dc.favorablePromotionsCount": "\"Angebotsaktionen\" Kategorie Raster",
  "dc.guideToMenuCount": "\"Platzanweisung\"-Art von Raster",
  "dc.posterCount": "\"Plakat\"-Stil Gitter",
  "dc.usherCount": "\"Leitweg\" Kategorie Gitter",
  "dc.danceCount": "\"Tanzen\"-Kategorie Schachbrettfeld",
  "dc.videoPosterCount": "\"Video-Poster\" Art Gitter",
  "dc.smallScreenExposureTime": "Kleine Bildschirmwiedergabedauer",
  "dc.smallScreenExposures": "Kleine Bildschirmwiedergabeanzahl",
  "dc.bigScreenExposureTime": "Großbildschirm-Wiedergabedauer",
  "dc.bigScreenExposures": "Großbildschirm-Wiedergabeanzahl",
  "dc.deliveryTables": "Ausgelieferte Tische",
  "dc.deliveryPlate": "Ausgelieferte Essensplatten",
  "dc.numberOfTieLessons": "Anzahl der Gästebegleitungen zum Platz",
  "dc.numberOfCleanTables": "Sauberkeitstischzahl",
  "tip.export.nodata": "Es sind keine Daten zum Exportieren verfügbar.",
  "dc.robotOperationOverview.toolTip": "Der Gesamtzustand des Roboters",
  "dc.robotOperationOverview.toolTip-1": "Arbeitsstunden (h): Die kumulierten Betriebsstunden aller von dem Agenten während des Datumsbereichs akquirierten Geschäfte mit gebundenen Robotern.",
  "dc.robotOperationOverview.toolTip-2": "Arbeitsstunden (h): Die kumulierte Betriebsstundenzahl aller von dem Agenten während des Datumsbereichs akquirierten Geschäfte mit gebundenen Robotern.",
  "dc.robotOperationOverview.toolTip-3": "3. Anzahl der ausgeführten Aufgaben: Kumulative Anzahl der von den Agenten innerhalb des Datumsbereichs erweiterten Geschäfte, die alle gebundenen Roboter für die Ausführung von Aufgaben nutzen.",
  "dc.robotRunningPeakTrend.toolTip": "Roboterbetrieb Hochkonjunktur Trendsituation",
  "dc.robotRunningPeakTrend.toolTip-1": "1. Natürlicher Tag: Es kann die Anzahl der in Betrieb genommenen Roboter verschiedener Typen innerhalb von 24 Stunden an einem beliebigen Tag abgefragt werden.",
  "dc.robotRunningPeakTrend.toolTip-2": "2. Natürliche Woche: Es kann jede beliebige Woche abgefragt werden, um die Anzahl der täglich in Betrieb genommenen Roboter verschiedener Kategorien zu ermitteln.",
  "dc.robotRunningPeakTrend.toolTip-3": "3. Kalendermonat: Es kann jeder beliebige Monat abgefragt werden, um die Anzahl der täglich in Betrieb genommenen Roboter verschiedener Kategorien zu ermitteln.",
  "dc.robotOverview.toolTip": "Roboteraktivierung und -aktivität",
  "dc.robotOverview.toolTip-1": "Einschaltquote der Roboter: Die kumulative Anzahl der Einschaltvorgänge aller Roboter, die an Geschäfte gebunden sind, welche innerhalb des Datumsbereichs von Vertriebspartnern erweitert wurden.",
  "dc.robotOverview.toolTip-2": "2. Kumulierte Anzahl: Die Gesamtzahl der gebundenen Roboter von der ersten Bindung eines Roboters an einen Laden durch den Agenten bis zum Stichtag des ausgewählten Zeitraums.",
  "dc.robotOverview.toolTip-3": "3. Aktivitätsrate = Im Zeitraum, (Anzahl der eingeschalteten Roboter ÷ kumulierte Anzahl) * 100%.",
  "dc.robotOverview.toolTip-4": "4. Gebundene Roboter: Die kumulierte Anzahl der Roboter, die innerhalb des Datumsbereichs von einem Agenten an einen Laden gebunden wurden.",
  "dc.robotOverview.toolTip-5": "5. Aktivierung von Robotern: Innerhalb des Datumsbereichs die kumulative Anzahl der bereits aktivierten Roboter, die von Agenten an die Geschäfte gebunden wurden.",
  "dc.storeOverview.toolTip": "Erweiterung der Filialaktivitäten und neue Situationen",
  "dc.storeOverview.toolTip-1": "Aktive Filialanzahl: Innerhalb des Datumsbereichs zählt jede vom Agenten entwickelte Filiale, in der ein Roboter betrieben wird, als eine aktive Filiale.",
  "dc.storeOverview.toolTip-2": "2. Kumulierte Anzahl: Die Gesamtzahl der Filialen, die seit dem ersten Bindungsdatum des Agenten an die Filiale bis zum ausgewählten Stichtag akkumuliert wurden.",
  "dc.storeOverview.toolTip-3": "3. Aktivitätsrate = Im Zeitraum, (Anzahl aktiver Geschäfte ÷ kumulierte Anzahl) * 100%.",
  "dc.storeOverview.toolTip-4": "4. Anzahl neuer Filialen: Die kumulierte Anzahl der neuen Filialen innerhalb des Datumsbereichs.",
  "dc.storeOverview.toolTip-5": "5. Top 10 der aktiven Geschäfte: Innerhalb des Datumsbereichs werden die von den Agenten entwickelten Geschäfte nach der Nutzungshäufigkeit und der Betriebsdauer der Roboter bewertet. Je höher die Nutzung und je länger der Betrieb, desto höher ist das Geschäft in der Rangliste der Aktivität.",
  "dc.storeOverview.toolTip-6": "Top 10 der stillgelegten Geschäfte: Innerhalb des Datumsbereichs wird ein Geschäft, das von einem Agenten erweitert wurde und dessen Roboteraktivität auf 0 gestoppt wurde, als ein stillgelegtes Geschäft gezählt. Je mehr Roboter stillgelegt sind und je länger die Stilllegung andauert, desto höher ist die Position in der Rangliste der Stille.",
  "dc.activeStore.toolTip": "Innerhalb des Datumsbereichs wird ein Geschäft, in dem Roboter betrieben werden, das von einem Agenten entwickelt wurde, als ein aktives Geschäft gezählt.",
  "dc.silentStore.toolTip": "Alle an das Geschäft gebundenen Maschinen wurden im Zeitraum nicht eingeschaltet und gelten als ein stillgelegtes Geschäft.",
  "dc.addStore.toolTip": "Innerhalb des Datumsbereichs die kumulative Anzahl neu hinzugefügter Geschäfte.",
  "dc.cumulativeStores.toolTip": "Von dem Datum der ersten Bindung des Geschäfts durch den Agenten bis zum ausgewählten Stichtag, die kumulierte Anzahl der Geschäfte.",
  "robot.status.bind.tip": "1. Bereits entbunden: Der Roboter ist derzeit an ein anderes Geschäft gebunden, und diese Daten sind historische Daten, die nach Datum für das Geschäft gefiltert wurden.",
  "robot.status.unbind.tip": "2. Bereits gebunden: Der Roboter ist derzeit mit diesem Geschäft verbunden, und diese Daten sind die Betriebsdaten des Geschäfts für das ausgewählte Datum.",
  "cruise.tip.run.mileage": "Im angegebenen Zeitraum die Gesamtkilometerzahl der Patrouillenfahrten aller an die Filialen des Agenten gebundenen Roboter erweitern.",
  "cruise.tip.run.duration": "Innerhalb des Datumsbereichs die Gesamtdauer des Patrouillenbetriebs aller an die Filiale gebundenen Roboter durch den Agenten erweitern.",
  "cruise.tip.interaction.times": "Innerhalb des Datumsbereichs die Gesamtzahl der Interaktionen aller an die Filiale gebundenen Roboter durch den Agenten erweitern.",
  "cruise.tip.interaction.duration": "Innerhalb des Datumsbereichs die gesamte Interaktionsdauer aller an die Filiale gebundenen Roboter durch den Agenten erweitern.",
  "delivery.tip.run.mileage": "Im angegebenen Zeitraum die Gesamtkilometerzahl der Lieferstrecken aller an die Filialen gebundenen Roboter durch den Agenten erweitern.",
  "delivery.tip.run.duration": "Innerhalb des Datumsbereichs die Gesamtbetriebsdauer der Lieferroboter, die an alle Geschäfte des Agenten gebunden sind, erweitern.",
  "delivery.tip.task.num": "Innerhalb des Datumsbereichs die kumulierte Anzahl der ausgeführten Aufgaben aller an den Laden gebundenen Roboter.",
  "delivery.tip.delivery.tables": "Innerhalb des Datumsbereichs erweitert der Agent die Anzahl der Lieferungstische für alle an die Filiale gebundenen Roboter.",
  "delivery.tip.delivery.plates": "Innerhalb des Datumsbereichs die Anzahl der ausgelieferten Essensplatten aller an die Filialen des Agenten gebundenen Roboter erweitern.",
  "greeter.tip.run.mileage": "Im angegebenen Zeitraum die Gesamtkilometerleistung aller an die Filialen gebundenen Roboter für die Platzierung durch den Agenten erweitern.",
  "greeter.tip.run.duration": "Innerhalb des Datumsbereichs die Gesamtlaufzeit der Platzierungsbetriebs von allen an die Filiale gebundenen Robotern durch den Agenten erweitern.",
  "greeter.tip.task.times": "Innerhalb des Datumsbereichs die Anzahl der Führungsaufgaben für alle an die Filiale gebundenen Roboter durch den Agenten erweitern.",
  "interaction.tip.all.times": "Innerhalb des Datumsbereichs die Anzahl der Mensch-Roboter-Interaktionen (Berührung, Sprachinteraktion) aller an die Filiale gebundenen Roboter erfassen.",
  "interaction.tip.voice.times": "Innerhalb des Datumsbereichs die Anzahl der Sprachinteraktionen mit allen an die Filiale gebundenen Robotern durch den Agenten erweitern.",
  "interaction.tip.duration": "Innerhalb des Datumsbereichs die gesamte akkumulierte Dauer der Sprachinteraktionen aller an die Filiale gebundenen Roboter erweitern.",
  "solicit.tip.duration": "Im angegebenen Zeitraum die Gesamtbetriebsdauer der Kundenakquise aller an die Filialen gebundenen Roboter durch den Agenten erweitern.",
  "solicit.tip.hello.times": "Innerhalb des Datumsbereichs, die Anzahl der Begrüßungen durch alle an die Filiale gebundenen Roboter erweitern.",
  "solicit.tip.reached.times": "Innerhalb des Datumsbereichs, die Anzahl der erreichten Nutzerkontakte für alle an die Filiale gebundenen Roboter durch den Agenten erweitern.",
  "solicit.tip.attach.times": "Im angegebenen Zeitraum erreichen die Agenten alle mit Robotern verbundenen Benutzer in den erweiterten Geschäften und die Anzahl der Personen, die verweilen.",
  "solicit.tip.interation.times": "Innerhalb des Datumsbereichs die Anzahl der Male, dass alle an die Filiale gebundenen Roboter durch Benutzer geweckt wurden.",
  "grid.click.times": "Innerhalb des Datumsbereichs die Anzahl der Klicks auf diese Funktion bei allen gebundenen Robotern unter den erweiterten Filialen des Agenten.",
  "ad.tiny.play.duration": "Innerhalb des Datumsbereichs umfasst die Agenturerweiterung die Dauer der Wiedergabe von Werbung auf kleinen Bildschirmen bei allen an die Filialen gebundenen Robotern.",
  "ad.tiny.play.times": "Während des Datumsbereichs, die Anzahl der Wiedergaben von Werbung auf kleinen Bildschirmen in allen gebundenen Robotern unter den erweiterten Filialen des Agenten.",
  "ad.large.play.duration": "Während des Datumsbereichs, die Dauer der Wiedergabe von Großbildschirmwerbung in allen an die Filialen des Agenten gebundenen Robotern.",
  "ad.large.play.times": "Während des Datumsbereichs, die Anzahl der Wiedergaben von Werbung auf Großbildschirmen aller an die Filialen gebundenen Roboter, die durch den Agenten erweitert wurden.",
  "recycle.tip.mileage": "Im angegebenen Zeitraum die Gesamtkilometerleistung aller an die Filialen des Agenten gebundenen Roboter bei der Rückspielung erweitern.",
  "recycle.tip.duration": "Im angegebenen Zeitraum die Gesamtlaufzeit der Rückspielbetriebs aller an die Filialen des Agenten gebundenen Roboter erweitern.",
  "recycle.tip.tables": "Innerhalb des Datumsbereichs die Anzahl der Tischreinigungsrückläufe aller an die Filialen des Agenten gebundenen Roboter erfassen.",
  "by.key": "Drücken Sie {Taste}",
  "by.store": "Gemäß Filiale",
  "by.robot": "nach Maschine",
  "by.day": "nach Tag",
  "by.hour": "pro Stunde",
  "export.config": "Exportkonfiguration",
  "timeby.config.label": "Zeitabschnittsdaten Exportregelkonfiguration",
  "robot.sn_mac": "Roboter SN/MAC",
  "dc.clean.area.total": "Reinigungsgesamtfläche (m²)",
  "dc.clean.area.total.tip": "Im angegebenen Zeitraum beträgt die gesamte kumulierte Reinigungsfläche aller von den Agenten erweiterten Geschäfte mit gebundenen Robotern.",
  "dc.clean.time.total": "Gesamtreinigungsdauer (h)",
  "dc.clean.time.total.tip": "Zeitraum, in dem die von den Agenten entwickelten Geschäfte die kumulative Gesamtreinigungsdauer aller gebundenen Roboter aufweisen.",
  "dc.clean.task.number": "Reinigungsaufgabenanzahl",
  "dc.clean.task.number.tip": "Im angegebenen Zeitraum die Gesamtzahl der Reinigungsaufgaben, die von allen an die Filialen der Agenten gebundenen Robotern ausgeführt wurden.",
  "dc.power.consumption": "Stromverbrauch (kWh)",
  "dc.power.consumption.tip": "Im angegebenen Zeitraum die kumulative Stromverbrauchsmenge aller an die von den Agenten erweiterten Geschäfte gebundenen Roboter.",
  "dc.water.consumption": "Wasserverbrauch (ml)",
  "dc.water.consumption.tip": "Im angegebenen Zeitraum ist der kumulierte Wasserverbrauch aller an die von den Agenten erweiterten Geschäfte gebundenen Roboter.",
  "dc.tab.all": "Alle Modi",
  "dc.tab.scrubbing": "Bodenwaschmodus",
  "dc.tab.sweeping": "Kehrmodus",
  "dc.sweep.vacuuming": "Teppichstaubsaugen",
  "dc.sweep.dustpush": "Staubdrücker in Stille",
  "dc.delivery": "Lieferung",
  "dc.clean": "Sauberkeit",
  "dc.time": "Zeit",
  "dc.基本数据": "Grunddaten",
  "dc.清洁任务分布": "Reinigungsaufgabenverteilung",
  "dc.清洁任务分布描述": "Im angegebenen Datumsbereich ist dies die Summe der Aufgaben, die von allen im Geschäft gebundenen Robotern stündlich an jedem Kalendertag ausgeführt werden. (Beispiel: Wenn das Datum vom 1. Januar bis zum 2. Januar gewählt wird und Aufgaben von 1:00 bis 2:00 am 1. Januar und um 1:00 am 2. Januar ausgeführt werden, dann zeigt die Aufgabenverteilungsstatistik für 1:00 Uhr zwei Aufgaben und für 2:00 Uhr eine Aufgabe an.)",
  "dc.robot.delivery.tip": "Dieser Automat ist kein Lieferautomat.",
  "dc.robot.clean.tip": "Dieses Gerät ist kein Reinigungsgerät.",
  "dc.store.unknow": "Es tut uns leid, das Geschäft wurde nicht gefunden.",
  "dc.mileage.tip": "Die Laufleistung beinhaltet nur die Betriebsdaten der Lieferroboter und nicht die Betriebsdaten der Reinigungsroboter.",
  "input.name.search": "Bitte geben Sie {key} ein, um zu suchen."
}