export default {
  "log.boot": "Einschalt-Selbsttest",
  "log.abnormal": "Außergewöhnliche Störung",
  "log.charge": "Ladeprotokoll",
  "log.battery": "Batteriezustand",
  "production.date": "Erstellungsdatum",
  "boot.status": "Zustand",
  "boot.undetected": "Nicht erkannt",
  "boot.normal": "Normal",
  "boot.abnormal": "Ausnahme",
  "key.no": "Nummer",
  "log.production.time": "Protokollerstellungszeit",
  "log.push.time": "Protokollierungszeit in der Cloud",
  "boot.description": "Beschreibung",
  "boot.check_module": "Selbstprüfungsmodulstatus",
  "poweron.ratio": "Speicheranteil (%)",
  "robot.softVer": "Softwareversion",
  "robot.hardVer": "Firmware-Version",
  "common.systemid": "Betriebssystemversion",
  "common.battery": "Aktueller Batteriestand",
  "check.abnormal": "Es liegt eine Anomalie vor.",
  "check.normal": "Keine Anomalien",
  "error.category": "Störungsart",
  "error.detail": "Störungsdetails",
  "error.grade": "Störungsgrad",
  "error.list": "Störungsliste",
  "error.ID": "Störungs-ID",
  "filter.more": "Mehr Filter",
  "charge.count_battery": "Lademenge",
  "charge.count_time": "Ladedauer",
  "soh.battery_sn": "Batterie-SN",
  "soh.full": "Batteriekapazität (mAh)",
  "soh.remaining": "Restkapazität (mAh)",
  "soh.battery_voltage": "Batteriespannung (mV)",
  "soh.soh": "Batteriegesundheitsindex",
  "soh.cycle": "Zyklusanzahl",
  "soh.battery_type": "Batterietyp",
  "tip.soh": "Das Protokoll wird nur übermittelt, wenn sich dieses Feld ändert.",
  "key.clip": "Ein-Klick-Kopieren",
  "collapse": "Einklappen",
  "please.select": "Bitte wählen Sie aus",
  "please.input": "Bitte geben Sie ein",
  "cycle.range.tip": "Der Zyklusbereich hat keine Daten."
}