export default {
  "menu.dataCenter": "Datenzentrum",
  "menu.dataCenter.dashBoard": "Armaturenbrett",
  "menu.dataCenter.operationAnalysis": "Betriebsanalyse",
  "menu.dataCenter.operationAnalysis.aStoreOperations": "Geschäftsbetriebs-Rangliste",
  "menu.dataCenter.operationAnalysis.bStoreProduct": "Produktbetriebs-Rangliste",
  "menu.dataCenter.operationAnalysis.cAtiveProduct": "Aktive Produktanalyse",
  "menu.dataCenter.operationAnalysis.sProductRoom": "Produktlieferaufgabenstatistik",
  "menu.dataCenter.operationAnalysis.eProductBackPlate": "Produktrücklauf-Aufgabenstatistik",
  "menu.dataCenter.operationAnalysis.fProductDisinfect": "Produktdesinfektionsaufgaben Statistik",
  "menu.dataCenter.operationAnalysis.gProductRunning": "Produktbetriebsübersicht",
  "menu.dataCenter.operationAnalysis.hProductDaily": "Produktdurchschnittsdaten pro Tag",
  "menu.dataCenter.operationAnalysis.iShopOperation": "Ladenöffnungszeiten Betriebsstatistik",
  "menu.dataCenter.operationAnalysis.jProductGrameTime": "Produktzeitraum-Betriebsstatistik",
  "menu.dataCenter.operationAnalysis.kShopEverydayOperation": "Tägliche Betriebsdatenstatistik der Filiale",
  "menu.dataCenter.operationAnalysis.LShopSevenOperation": "Geschäftsdatenstatistik der letzten sieben Tage",
  "menu.dataCenter.operationAnalysis.mProductEverydayOperation": "Produkt tägliche Betriebsdatenstatistik",
  "menu.dataCenter.operationAnalysis.nProductSevenOperation": "Produkt Sieben Betriebsdatenstatistik",
  "menu.dataCenter.operationAnalysis.VRobotTaskAnalysis": "Roboter-Aufgabenanalyse",
  "menu.reportLog": "Meldeprotokoll",
  "menu.reportLog.foodDelivery": "Lieferaufgabe",
  "menu.reportLog.recycleDish": "Gegenangebot Aufgabe",
  "menu.reportLog.disInfect": "Desinfektionsaufgabe",
  "menu.reportLog.flashDelivery": "Zimmerlieferungsaufgabe",
  "menu.reportLog.powerOn": "Einschalt-Selbsttest",
  "menu.reportLog.charge": "Ladeprotokoll",
  "menu.reportLog.failure": "Außergewöhnliche Störung",
  "menu.reportLog.upgrade": "Aufstiegsbericht",
  "menu.reportLog.batteryHealth": "Batteriezustand",
  "menu.reportLog.AbnormalIPAddr": "IP-Adressen-Ausnahmebericht",
  "menu.reportLog.about2fall_report": "Sturzpräventionsprotokoll",
  "menu.valueAdded": "Mehrwertdienste",
  "menu.valueAdded.custom": "Maßgeschneiderte Sprachversion V1.1",
  "menu.valueAdded.customV1": "Maßgeschneiderte Sprachversion V1.0",
  "menu.valueAdded.software": "Software-Funktionspaket",
  "menu.valueAdded.tts": "TTS-Fragen und Antworten",
  "menu.valueAdded.sip": "SIP-Telefondienst-Einstellungen",
  "menu.account": "Kontoverwaltung",
  "menu.account.accountConfig": "Kontokonfiguration",
  "menu.systemManage.AccountOperationHistory": "Betriebshistorie",
  "menu.AccountOperationHistory": "Betriebshistorie",
  "menu.systemManage": "Systemverwaltung",
  "menu.systemManage.dictionaryManagement": "Wörterbuchverwaltung",
  "menu.systemManage.messageNotification": "Nachrichtenbenachrichtigung",
  "menu.openPlatform": "Offene Plattform",
  "menu.openPlatform.applicationCenter": "Antragszentrum",
  "menu.openPlatform.developDoc": "Entwicklungsdokumentation",
  "menu.returnManage": "Rücksendeverwaltung",
  "menu.returnManage.record": "Rückgabeprotokoll",
  "menu.returnManage.useReturn": "Verwendung der Rückgabe",
  "menu.customerCenter": "Kundenzentrum",
  "menu.customerCenter.storeManagement": "Ladengeschäft-Management",
  "menu.customerCenter.storeDetail": "Ladendetails",
  "menu.customerCenter.bindRobots": "Gebundener Roboter",
  "menu.customerCenter.bindARobot": "Hinzufügen eines Roboters",
  "menu.customerCenter.storeRobotManagement": "Ladengerät",
  "menu.customerCenter.activeCodeManagement": "Aktivierungscode",
  "menu.customerCenter.financialInstitution": "Finanzinstitut",
  "menu.customerCenter.financialDetail": "Finanzinstitut Details",
  "menu.customerCenter.agent": "Agenturmanagement",
  "menu.customerCenter.agentDetail": "Agentendetails",
  "menu.productCenter": "Produktzentrum",
  "menu.productCenter.productArchives": "Produktakte",
  "menu.fileCenter": "Dokumentenzentrum",
  "menu.fileCenter.mapFile": "Kartendatei",
  "menu.fileCenter.formFile": "Abnahmeschein Dokument",
  "menu.fileCenter.downloadFile": "Dokument herunterladen",
  "menu.equipmentCenter": "Produktzentrum",
  "menu.equipmentCenter.productArchives": "Produktakte",
  "menu.equipmentCenter.productLibrary": "Maschinenproduktkatalog",
  "menu.equipmentCenter.outboundProducts": "Ausgelieferte Produkte an nachgeordnete Vertreter",
  "menu.equipmentCenter.viewProductInfo": "Produktinformationen anzeigen",
  "menu.equipmentCenter.productEdit": "Redaktionsinformation",
  "menu.equipmentCenter.installedProduct": "Installiertes Produkt",
  "menu.equipmentCenter.installedProducts": "Installiertes Produkt",
  "menu.equipmentCenter.flowCard": "Bereits gebundene Datenkartenprodukte",
  "menu.equipmentCenter.productDetail": "Produktdetails",
  "menu.equipmentCenter.productChangeRecord": "Produktänderungsprotokoll",
  "menu.equipmentCenter.product-change-records": "Geräteänderungsprotokoll",
  "menu.equipmentCenter.flowCardChangeRecord": "Datenverkehrskarten-Änderungsprotokoll",
  "menu.equipmentCenter.assignedProduct": "Bereits zugewiesenes Betriebsprodukt",
  "menu.equipmentCenter.unallocatedProduct": "Unzugewiesenes Betriebsprodukt",
  "menu.equipmentCenter.antiSmuggling": "Prävention von Warenunterschlagung Risikokontrolle",
  "menu.equipmentCenter.accessories": "Ersatzteilmanagement",
  "menu.welcome": "Willkommen",
  "menu.more-blocks": "Mehr Blöcke",
  "menu.home": "Startseite",
  "menu.admin": "Verwaltungsseite",
  "menu.admin.sub-page": "Sekundäre Verwaltungsseite",
  "menu.login": "Anmeldung",
  "menu.register": "Registrierung",
  "menu.register.result": "Registrierungsergebnis",
  "menu.dashboard.analysis": "Analyse-Seite",
  "menu.dashboard.monitor": "Überwachungsseite",
  "menu.dashboard.workplace": "Arbeitstisch",
  "menu.exception.403": "403",
  "menu.exception.404": "404",
  "menu.exception.500": "fünfhundert",
  "menu.form": "Formularseite",
  "menu.form.basic-form": "Grundformular",
  "menu.form.step-form": "Schritt-für-Schritt-Formular",
  "menu.form.step-form.info": "Schritt-für-Schritt-Formular (Überweisungsinformationen ausfüllen)",
  "menu.form.step-form.confirm": "Schritt-für-Schritt-Formular (Bestätigung der Überweisungsinformationen)",
  "menu.form.step-form.result": "Schritt-für-Schritt-Formular (abgeschlossen)",
  "menu.form.advanced-form": "Fortgeschrittenes Formular",
  "menu.list": "Listen-Seite",
  "menu.list.table-list": "Abfrageformular",
  "menu.list.basic-list": "Standardliste",
  "menu.list.card-list": "Kartenliste",
  "menu.list.search-list": "Suchliste",
  "menu.list.search-list.articles": "Suchliste (Artikel)",
  "menu.list.search-list.projects": "Suchliste (Projekte)",
  "menu.list.search-list.applications": "Suchliste (Anwendungen)",
  "menu.profile": "Produktdetailseite",
  "menu.profile.basic": "Grundlegende Detailseite",
  "menu.profile.advanced": "Fortgeschrittene Detailseite",
  "menu.result": "Ergebnisseite",
  "menu.result.success": "Erfolgsseite",
  "menu.result.fail": "Fehlerseite",
  "menu.exception": "Ausnahmeseite",
  "menu.exception.not-permission": "403",
  "menu.exception.not-find": "404",
  "menu.exception.server-error": "fünfhundert",
  "menu.exception.trigger": "Auslösen eines Fehlers",
  "menu.account.center": "Persönliches Zentrum",
  "menu.account.settings": "Persönliche Einstellungen",
  "menu.account.trigger": "Auslösen eines Fehlers",
  "menu.account.logout": "Abmelden",
  "menu.editor": "Grafikeditor",
  "menu.editor.flow": "Prozesseditor",
  "menu.editor.mind": "Gehirnkarten-Editor",
  "menu.editor.koni": "Topologie-Editor",
  "menu.test": "Test",
  "menu.dataCenter.operationAnalysis.oFoodDelivery": "Produktlieferdienst Tischdatenstatistik",
  "menu.dataCenter.operationAnalysis.pReturnPlate": "Produktrücklaufservice Tischdatenstatistik",
  "menu.dataCenter.operationAnalysis.RCruiseMode": "Produkt-Kreuzfahrtmodus-Datenstatistik",
  "menu.dataCenter.operationAnalysis.TSolicitCustomersMode": "Produktakquise-Modell-Datenstatistik",
  "menu.dataCenter.operationAnalysis.SLeadmode": "Produktführungsmodus-Datenstatistik",
  "menu.dataCenter.operationAnalysis.UAdPlayMode": "Werbewiedergabe-Datenstatistik",
  "menu.customerCenter.rcagent": "Verknüpfte Agenten",
  "menu.customerCenter.equipment": "Eigentumsgerät",
  "menu.customerCenter.financialInfo": "Finanzierungsinstitut Details",
  "menu.reportLog.SIMCardLog": "Datentarifkarte",
  "menu.SIMCardMgr": "Datenkartenverwaltung",
  "menu.SIMCardMgr.ActivedCardMgr": "Aktivierte Datenkarte",
  "menu.SIMCardMgr.ExpiredCardMgr": "Verfallsbenachrichtigung für Datenkarte",
  "menu.BusinessDistrictMgr": "Geschäftsviertelverwaltung",
  "menu.BusinessDistrictMgr.Add": "Neuzugang",
  "menu.BusinessDistrictMgr.Edit": "Redakteur",
  "menu.BusinessDistrictMgr.Detail": "Betrachten",
  "menu.dataCenter.dataOverview": "Datenüberblick",
  "menu.dataCenter.storeAnalysis": "Geschäftsanalyse",
  "menu.dataCenter.robotOperationAnalysis": "Roboterbetriebsanalyse",
  "menu.dataCenter.robotTaskAnalysis": "Roboter-Lieferdaten",
  "menu.dataCenter.cleanRobotData": "Roboter reinigen Daten",
  "menu.app-center": "Anwendungszentrum",
  "menu.app-center.emoticon-mgmt": "Roboter-Gesichtsausdruck-Management",
  "menu.app-center.emoticon-add": "Erstellung von Emoticon-Paketen",
  "menu.app-center.emoticon-edit": "Bearbeiten von Emoticon-Paketen",
  "menu.app-center.voice-mgmt": "Roboter-Sprachverwaltung",
  "menu.app-center.voice-add": "Erstellung eines benutzerdefinierten Sprachpakets",
  "menu.app-center.voice-edit": "Benutzerdefiniertes Sprachpaket bearbeiten",
  "menu.app-center.voice-auth": "Sprachpaket-Lizenz",
  "menu.app-center.open-platform": "Offene Plattform",
  "menu.app-center.open-platform-detail": "Betrachten",
  "menu.app-center.open-platform-add": "Bewerbung um eine Anwendung",
  "menu.app-center.open-platform-edit": "Redakteur-Anwendung",
  "menu.log-center": "Tagebuchzentrum",
  "menu.log-center.robot-logs": "Roboterprotokoll",
  "menu.message-center": "Nachrichtenzentrum",
  "menu.message-center.message-detail": "Nachrichtendetails"
}