export default {
  "请输入": "Bitte geben Sie ein",
  "选择": "Auswahl",
  "返回": "Rückkehr",
  "未绑定": "Nicht gebunden",
  "已安装": "Bereits installiert",
  "导入时间": "Importzeit",
  "代理名称": "Agenturname",
  "所属代理": "Zugehörige Agentur",
  "出库撤回": "Lagerentnahme zurückziehen",
  "出库撤回说明": "Lagerentnahme Rücknahmeerklärung",
  "撤回后下级代理": "Nach dem Widerruf wird der untergeordnete Agent nicht in der Lage sein, den Roboter zu bedienen oder einzusehen.",
  "出库撤回失败": "Lagerabzug Rücknahme fehlgeschlagen",
  "该代理已将机器人绑定门店": "Der Agent hat den Roboter bereits an den Laden gebunden.",
  "出库至下级代理": "Auslieferung an den nachgeordneten Vertreter",
  "未选择下级代理商": "Es wurde kein untergeordneter Vertriebspartner ausgewählt.",
  "没有出库产品": "Keine ausgehenden Produkte",
  "确定出库": "Bestätigung der Auslagerung",
  "出库说明": "Auslagerungshinweis",
  "选择未出库产品": "Auswahl von Produkten, die noch nicht ausgelagert wurden",
  "选择下级代理商": "Wählen Sie einen untergeordneten Vertriebspartner.",
  "代理商帐号": "Agentenkonto",
  "注册地址": "Registrierungsadresse",
  "销售区域": "Verkaufsgebiet",
  "注册时间": "Registrierungszeit",
  "一级": "Erstklassig",
  "二级": "Sekundär",
  "已损坏": "Beschädigt",
  "已锁机": "Bereits gesperrt",
  "冻结中": "Eingefroren",
  "过期": "Die Werkstestung ist abgelaufen.",
  "未激活": "Nicht aktiviert",
  "激活": "Aktivierung",
  "已激活": "Bereits aktiviert",
  "已入库": "Bereits eingelagert",
  "厂测中": "Fabriktest läuft",
  "无记录": "Keine Aufzeichnung",
  "全部": "Alles",
  "产品信息": "Produktinformation",
  "维保信息": "Wartungsinformationen",
  "服务信息": "Dienstleistungsinformationen",
  "产品操作记录": "Produktbetriebsprotokoll",
  "换板待验证": "Platte auswechseln, Verifizierung ausstehend",
  "待验证": "In Überprüfung",
  "所属门店": "Zugehörige Filiale",
  "所属代理商": "Zugehöriger Vertriebspartner",
  "激活时间": "Aktivierungszeit",
  "昵称": "Spitzname",
  "SN": "SN(PID)",
  "MAC": "MAC",
  "软件版本": "Softwareversion",
  "固件版本": "Firmware-Version",
  "现场用途": "Vor-Ort-Verwendung",
  "机器分组": "Maschinengruppierung",
  "用机类型": "Maschinentyp",
  "保修时长": "Garantiedauer",
  "实施工程师": "Projektingenieur",
  "运维工程师": "Wartungsingenieur",
  "首次导入代理": "Erstmaliger Import von Proxy:",
  "绑定代理": "Gebundener Vertreter:",
  "的门店": "von Geschäften:",
  "从门店": "Aus dem Geschäft:",
  "解绑返回代理": "Entbindung, zurück zum Agenten:",
  "代理": "Vertreter:",
  "出库产品到下级代理": "Produkte aus dem Lager an nachgeordnete Vertreter:",
  "从下级代理": "Vom untergeordneten Agenten:",
  "出库撤回到代理": "Auslagerung zurück an den Agenten:",
  "操作说明": "Bedienungsanleitung:",
  "操作人": "Bediener:",
  "机器产品库使用提示": "Produktlager für Maschinen, das Produkte umfasst, die von Händlergeschäften entbunden und an das Lager zurückgesendet wurden; sowie Produkte, die bereits an die mit Händlern verbundenen Geschäfte verkauft wurden. Gleichzeitig können \"nicht gebundene\" Produkte aus dem Lager an Ihre untergeordneten Vertriebspartner ausgegeben werden.",
  "未綁定状态": "Ungebundener Zustand: Roboter, die noch nicht an Geschäfte gebunden sind und sich im Lager befinden.",
  "功能介绍": "Funktionsvorstellung:",
  "冻结": "Einfrieren",
  "取消冻结": "Aufhebung der Sperre",
  "未绑定状态描述": "Nicht gebunden: Zustand, in dem die Ware vom Lager des Purdue-Unternehmens zum Lager des Agenten ausgelagert wird, ohne dass der Agent an einen bestimmten Laden verkauft hat.",
  "未激活状态描述": "Nicht aktiviert: Zustand, in dem der Händler den Roboter verkauft und an ein physisches Geschäft bindet, aber der Roboter nicht eingeschaltet und aktiviert ist.",
  "已激活状态描述": "Aktiviert: Der Zustand, in dem der Agent die mit dem Geschäft verbundenen Roboter einschaltet und aktiviert.",
  "已冻结状态描述": "Eingefroren: Der Status eines Roboters nach der Einfrierung durch den Agenten, in diesem Zustand kann der Roboter nicht mehr verwendet werden.",
  "换板待验证状态描述": "Platine ausstehend auf Verifizierung: Der Zustand während des Austauschprozesses, wenn das Hauptboard des Roboters beschädigt ist.",
  "还剩": "Es bleibt noch übrig",
  "个月": "Monat",
  "系统操作": "Systembetrieb",
  "租赁时长": "Mietdauer",
  "试用时长": "Probelaufzeit",
  "试用截止时间": "Probefrist",
  "门店安装时间": "Ladeninstallationszeit",
  "备件信息": "Teileinformationen",
  "备件类型": "Bauteiltyp",
  "导出全部": "Exportieren Sie alles",
  "供应商": "Lieferant",
  "型号": "Modell",
  "上报时间": "Meldezeit",
  "电池": "Batterie",
  "雷达": "Radar",
  "相机": "Kamera",
  "核心板": "Hauptplatine",
  "屏幕": "Bildschirm",
  "充电器": "Ladegerät",
  "功能板": "Funktionsversion",
  "上位机": "Übergeordnete Steuerung"
}