export default {
  "exception.monitor": "Außergewöhnliche Überwachung",
  "key.whitelist": "{key} Weiße Liste",
  "risk.control.settings": "Risikokontrolleinstellungen",
  "robot.run.district": "Betriebsgebiet",
  "robot.report.time.latest": "Letzte Berichtszeit",
  "robot.lock.confirm": "Nach Durchführung der Sperrvorgänge wird der Roboter nicht mehr benutzbar sein und kann weder entbunden noch an einen anderen Laden gebunden werden.",
  "robot.lock.remark": "Sperrhinweis für das Gerät",
  "robot.unlock.confirm": "Nach Durchführung der Entsperrvorgänge wird der Roboter die Warnungen aufheben und wieder normal funktionieren.",
  "robot.exception.view": "Betrachten Sie die Details der Anomalie",
  "robot.info": "Roboterinformation",
  "shop.info": "Ladeninformationen",
  "robot.category": "Roboterarten",
  "robot.smuggling.warning": "Außergewöhnliche Warnung, es besteht das Risiko von Schmuggelware.",
  "robot.run.location": "Betriebsposition",
  "key.remove": "Entfernen",
  "time.add": "Hinzugefügte Zeit",
  "use.instructions": "Gebrauchsanweisung",
  "confirm.remove": "Nach Durchführung der Entfernungsoperation wird der \"Anti-Schmuggel-Risikokontroll\"-Mechanismus des Geräts aktiviert.",
  "device.add": "Gerät hinzufügen",
  "use.instruction.reason": "Gründe für das Hinzufügen der Maschine zur Weißen Liste",
  "query.result": "Abfrageergebnis",
  "query.byMac": "MAC-Adressabfrage",
  "base.version.No": "Referenzversionsnummer",
  "key.auto.lock": "Automatische Verriegelung{key}",
  "district.china.mainland.outside": "Hongkong, Macau, Taiwan und das Ausland",
  "district.china.mainland": "Festlandchina",
  "key.enable": "Inbetriebnahme",
  "edit.risk.control.settings": "Bearbeitung der Risikokontrolleinstellungen",
  "robot.status.locked": "Bereits gesperrt",
  "robot.status.unlock": "Bereits entsperrt",
  "robot.sn/pid": "Geräte-SN (PID)",
  "key.status": "{key} Status",
  "risk.control": "Risikokontrolle",
  "status.risk.control": "Risikokontrollstatus",
  "status.robot": "Roboterstatus",
  "status.abnormal.watning": "Außergewöhnliche Warnung",
  "datatype.nomal": "Normale Daten",
  "datatype.nomal.tip": "Eingeschlossen: Roboter auf der weißen Liste, entsperrte Roboter und Roboter, die nie die Risikokontrolle für Schmuggelware ausgelöst haben.",
  "datatype.abnomal": "Außergewöhnliche Daten",
  "opr.area": "{key} Betriebsbereich",
  "goto.check": "Gehe nachschauen.",
  "risk.control.notify": "Risikokontrollmitteilung",
  "risk.control.warntip": "Roboter, die im Nicht-Agenten-Bereich betrieben werden, werden bei mehrmaliger Auslösung gesperrt.",
  "abnormal.waning.robots": "Außergewöhnliches Warnsystem",
  "etc.": "gleich",
  "robot.lock.switch": "Sperrschalter",
  "robot.lock.auto": "Automatische Verriegelung",
  "robot.lock.manual": "Manuelles Sperren",
  "abnormal.lock.robots": "Risikokontroll-Sperrvorrichtung",
  "robot.lock.tip": "Auslösung der Risikokontrolle für unerlaubte Warenbewegungen, das Gerät ist derzeit gesperrt. Bei Fragen wenden Sie sich bitte an das Servicepersonal von Purdue.",
  "warning.send.email": "Außergewöhnliche Warnhinweise per E-Mail",
  "input.email.multiple": "Mehrere E-Mail-Adressen zeilenweise eingeben",
  "input.forExample": "Beispiel:",
  "email.invalid": "Unzulässige E-Mail-Adresse",
  "PuduBot": "Fröhliche Lieferung",
  "BellaBot": "Bella",
  "HolaBot": "Alles klar",
  "Puductor": "Fröhliches Löschen",
  "Puductor2": "Frohes Eliminieren 2",
  "KettyBot": "Kürbis",
  "FlashBot": "Blitzkasten",
  "PuduCC1": "Aus dem Staub",
  "SwiftBot": "Pfiffige Lieferung",
  "PuduBot2": "Fröhliche Lieferung 2",
  "PuduSH1": "Löwe Tiger"
}