export default {
  "productListIframe.无记录": "Keine Aufzeichnung",
  "productListIframe.厂测中": "Fabriktest läuft",
  "productListIframe.厂测过期": "Fabriktest abgelaufen",
  "productListIframe.已入库": "Bereits eingelagert",
  "productListIframe.未绑定": "Nicht gebunden",
  "productListIframe.未激活": "Nicht aktiviert",
  "productListIframe.已激活": "Bereits aktiviert",
  "productListIframe.已冻结": "Bereits eingefroren",
  "productListIframe.换板待验证": "Platte auswechseln, Verifizierung ausstehend",
  "productListIframe.保内": "Innenschutz",
  "productListIframe.保外": "Haftentlassung auf Bewährung",
  "productListIframe.产品名称": "Produktname",
  "productListIframe.所属门店": "Zugehörige Filiale",
  "productListIframe.所属代理": "Zugehörige Agentur",
  "productListIframe.产品状态": "Produktstatus",
  "productListIframe.首次激活时间": "Erstmaliges Aktivierungsdatum",
  "productListIframe.最新安装时间": "Neueste Installationszeit",
  "productListIframe.代理维保状态": "Stellvertretender Wartungszustand",
  "productListIframe.终端维保状态": "Endgerät-Wartungsstatus",
  "productListIframe.设备地址": "Geräteadresse",
  "productListIframe.关闭": "Geschlossen",
  "productListIframe.没有更多了": "Es gibt nicht mehr.",
  "productListIframe.加载中": "Laden läuft",
  "productListIframe.请选择机器": "Bitte wählen Sie die Maschine.",
  "productListIframe.搜索": "Suche",
  "productListIframe.清除筛选": "Filter löschen",
  "productListIframe.查看更多": "Mehr ansehen",
  "productListIframe.完成": "Erledigt"
}