export default {
  "app.settings.menuMap.basic": "Grundeinstellungen",
  "app.settings.menuMap.security": "Sicherheitseinstellungen",
  "app.settings.menuMap.binding": "Kontobindung",
  "app.settings.menuMap.notification": "Neue Nachrichtenbenachrichtigung",
  "app.settings.basic.avatar": "Profilbild",
  "app.settings.basic.change-avatar": "Profilbild ändern",
  "app.settings.basic.email": "E-Mail-Box",
  "app.settings.basic.email-message": "Bitte geben Sie Ihre E-Mail-Adresse ein!",
  "app.settings.basic.nickname": "Spitzname",
  "app.settings.basic.nickname-message": "Bitte geben Sie Ihren Spitznamen ein!",
  "app.settings.basic.profile": "Persönliches Profil",
  "app.settings.basic.profile-message": "Bitte geben Sie eine persönliche Vorstellung ein!",
  "app.settings.basic.profile-placeholder": "Persönliches Profil",
  "app.settings.basic.country": "Land/Region",
  "app.settings.basic.country-message": "Bitte geben Sie Ihr Land oder Ihre Region ein!",
  "app.settings.basic.geographic": "In welcher Provinz/Stadt",
  "app.settings.basic.geographic-message": "Bitte geben Sie Ihre Provinz und Stadt ein!",
  "app.settings.basic.address": "Straßenadresse",
  "app.settings.basic.address-message": "Bitte geben Sie Ihre Straßenadresse ein!",
  "app.settings.basic.phone": "Kontakttelefonnummer",
  "app.settings.basic.phone-message": "Bitte geben Sie Ihre Telefonnummer ein!",
  "app.settings.basic.update": "Aktualisieren Sie die grundlegenden Informationen.",
  "app.settings.security.strong": "stark",
  "app.settings.security.medium": "Mitte",
  "app.settings.security.weak": "Schwach",
  "app.settings.security.password": "Kontopasswort",
  "app.settings.security.password-description": "Aktuelle Passwortstärke",
  "app.settings.security.phone": "Sicherheitshandy",
  "app.settings.security.phone-description": "Bereits gebundenes Handy",
  "app.settings.security.question": "Sicherheitsfrage",
  "app.settings.security.question-description": "Es wurden keine Sicherheitsfragen festgelegt. Sicherheitsfragen können effektiv zum Schutz der Kontosicherheit beitragen.",
  "app.settings.security.email": "Ersatz-E-Mail-Adresse",
  "app.settings.security.email-description": "Bereits gebundene E-Mail",
  "app.settings.security.mfa": "MFA-Gerät",
  "app.settings.security.mfa-description": "Nicht an MFA-Gerät gebunden, nach der Bindung kann eine zweite Bestätigung durchgeführt werden.",
  "app.settings.security.modify": "Änderung",
  "app.settings.security.set": "Einstellung",
  "app.settings.security.bind": "Gebunden",
  "app.settings.binding.taobao": "Gebunden an Taobao",
  "app.settings.binding.taobao-description": "Derzeit ist kein Taobao-Konto verknüpft.",
  "app.settings.binding.alipay": "Gebunden an Alipay",
  "app.settings.binding.alipay-description": "Derzeit ist kein Alipay-Konto verknüpft.",
  "app.settings.binding.dingding": "Gebunden an DingTalk",
  "app.settings.binding.dingding-description": "Derzeit ist kein DingTalk-Konto verknüpft.",
  "app.settings.binding.bind": "Gebunden",
  "app.settings.notification.password": "Kontopasswort",
  "app.settings.notification.password-description": "Die Nachrichten anderer Benutzer werden in Form von internen Nachrichten benachrichtigt.",
  "app.settings.notification.messages": "Systemnachricht",
  "app.settings.notification.messages-description": "Systemnachrichten werden in Form von internen Nachrichten benachrichtigt.",
  "app.settings.notification.todo": "Zu erledigende Aufgaben",
  "app.settings.notification.todo-description": "Zu erledigende Aufgaben werden in Form von internen Nachrichten mitgeteilt.",
  "app.settings.open": "öffnen",
  "app.settings.close": "Schlüssel",
  "robot.check.blacklist": "Die MAC-Adresse wurde zur schwarzen Liste hinzugefügt, bitte kontaktieren Sie die Purdue Company zur Bearbeitung."
}