export default {
  "app.setting.pagestyle": "Gesamte Stileinstellung",
  "app.setting.pagestyle.dark": "Dunkles Menüdesign",
  "app.setting.pagestyle.light": "Helle Menü-Stil",
  "app.setting.content-width": "Inhaltsbereich Breite",
  "app.setting.content-width.fixed": "Festbreite",
  "app.setting.content-width.fluid": "Fließ-",
  "app.setting.themecolor": "Hauptfarbe",
  "app.setting.themecolor.dust": "Dämmerung",
  "app.setting.themecolor.volcano": "Vulkan",
  "app.setting.themecolor.sunset": "Abenddämmerung",
  "app.setting.themecolor.cyan": "Helles Blaugrün",
  "app.setting.themecolor.green": "Polarlichtgrün",
  "app.setting.themecolor.daybreak": "Morgendämmerung Blau (Standard)",
  "app.setting.themecolor.geekblue": "Geek Blau",
  "app.setting.themecolor.purple": "Sojasoße",
  "app.setting.navigationmode": "Navigationsmodus",
  "app.setting.sidemenu": "Seitenmenü-Layout",
  "app.setting.topmenu": "Oberes Menü-Layout",
  "app.setting.fixedheader": "Fester Header",
  "app.setting.fixedsidebar": "Festes Seitenmenü",
  "app.setting.fixedsidebar.hint": "Seitenmenü-Layout kann konfiguriert werden",
  "app.setting.hideheader": "Beim Herunterscrollen Header ausblenden",
  "app.setting.hideheader.hint": "Feststehender Header kann konfiguriert werden",
  "app.setting.othersettings": "Andere Einstellungen",
  "app.setting.weakmode": "Farbschwachmodus",
  "app.setting.copy": "Kopiereinstellungen",
  "app.setting.copyinfo": "Kopieren erfolgreich, bitte ersetzen Sie die Standardkonfiguration in src/defaultSettings.js",
  "app.setting.production.hint": "Die Konfigurationsleiste wird nur in der Entwicklumgebung zur Vorschau verwendet und ist in der Produktionsumgebung nicht sichtbar. Bitte kopieren Sie sie und ändern Sie die Konfigurationsdatei manuell."
}