export default {
  "language.select.label": "Sprachauswahl",
  "voice.add": "Hinzufügen von Sprachnachrichten",
  "voice.category": "Sprachklassifizierung",
  "voice.mp3": "Sprachaudio",
  "voice.mp3.del.confirm": "Nach dem Löschen dieser Sprachaufnahme werden neu hinzugefügte benutzerdefinierte Sprachpakete diese Szenenaufnahme nicht mehr enthalten.",
  "voice.language": "Sprachtyp",
  "voice.id.correct.tip": "Bitte geben Sie die korrekte VoiceID des Roboters ein, sonst kann keine Sprachausgabe erfolgen.",
  "voice.display.scene.desc": "Szenario der Sprachausgabe",
  "voice.display.content": "Der Inhalt des gesprochenen Manuskripts",
  "voice.upload.limit": "Unterstützt das Hochladen von MP3-Dateien bis zu einer maximalen Größe von 1MB.",
  "voice.pkg.desc": "Sprachpaketbeschreibung",
  "voice.access": "Autorisierter Roboter",
  "voice.pkg.auth": "Sprachpaket-Lizenz",
  "key.agent.name": "Agent",
  "key.auth.add": "Hinzufügen einer Berechtigung",
  "key.batch.replace": "Massenersatz",
  "key.robot.category": "Roboterarten",
  "key.robot.No": "Roboteranzahl",
  "voice.all": "Alle Sprachnachrichten",
  "voice.merge.submit": "Synthetisierte Sprachausgabe und abgeschlossen",
  "voice.merge.submit.failed": "Das Update des Sprachpakets ist fehlgeschlagen.",
  "voice.change.mp3": "Austausch der Audio",
  "voice.validity.period.tip": "Bitte wählen Sie das Gültigkeitsdatum.",
  "voice.authorized.mac.tip": "Dieses Sprachpaket wird für die folgenden {robot} Roboter lizenziert.",
  "voice.authorized.store.tip": "Dieses Sprachpaket wird für die {robot} Roboter der folgenden Geschäfte lizenziert.",
  "voice.authorized.agent.tip": "Dieses Sprachpaket wird für alle Filialen des Agenten für den {robot} Roboter lizenziert.",
  "voice.voiceid.notmatch": "Der Dateiname stimmt mit keiner VoiceID überein.",
  "voice.filesize.exceed": "Die Dateigröße überschreitet das erlaubte Limit.",
  "voice.upload.warning1": "Die Dateien im Ordner müssen komprimiert werden, der Ordner selbst jedoch nicht.",
  "voice.upload.warning2": "Die Benennung der Audiodatei muss die voiceID des entsprechenden Robotertyps sein.",
  "voice.upload.warning3": "Es werden maximal 200 MP3-Audiodateien unterstützt, die nicht größer als 200 MB sind.",
  "voice.upload.warning4": "Da die Datei ziemlich groß ist, dürfen Sie den Upload-Prozess nicht verlassen.",
  "not.your.robot": "Nicht der Roboter in Ihrem Lager.",
  "key.limit.import.count": "Begrenzung auf {key} Stück",
  "navBar.lang": "Sprache"
}