export default {
  "联系邮箱": "Indirizzo email di contatto",
  "代理商等级": "Livello dell'agente",
  "上级代理商": "Agente di livello superiore",
  "重置密码": "Reimposta la password",
  "新密码": "nuova password",
  "操作成功": "Operazione riuscita",
  "操作失败": "Operazione fallita",
  "共n条记录": "Totale di {total} record",
  "是否前往": "L'account è stato aggiunto con successo, si prega di andare al \"Centro Clienti\" per completare le informazioni di base dell'agente.",
  "未添加无法登录": "Suggerimenti: Se non vengono aggiunte le informazioni di base dell'agente, l'account non potrà accedere al sistema.",
  "立即前往": "Procedi immediatamente",
  "查看账号": "Visualizza le informazioni dell'account",
  "生成新密码": "Clicca qui per generare una nuova password",
  "随机密码": "Password casuale",
  "更换密码": "Cambia la password",
  "复制密码": "Copia la password",
  "已复制！": "Già copiato!",
  "图片裁剪": "Ritaglio dell'immagine",
  "获取文件md5出错": "Ottenere l'errore md5 del file",
  "oss删除文件失败": "Eliminazione del file OSS fallita",
  "视频个数超出限额": "Il numero di video ha superato il limite consentito.",
  "素材类型不正确": "Il formato del materiale non è corretto.",
  "图片过大": "L'immagine è troppo grande.",
  "视频过大": "Il video è troppo grande.",
  "分辨率超出": "La risoluzione supera i {height}P",
  "账号不能包含空格": "Il nome utente non può contenere spazi.",
  "账号已存在": "L'account esiste già",
  "请设置密码": "Si prega di impostare una password.",
  "密码规则": "Lettere maiuscole e minuscole, numeri, caratteri speciali combinati in qualsiasi modo tra i tre.",
  "agent.store.info": "Si conta solo il numero di negozi espansi dall'agente attuale, escluso il numero di negozi degli agenti di livello inferiore.",
  "account.noOrg.warning": "L'account non ha completato le informazioni dell'agente, si prega di contattare il creatore dell'account per gestire la situazione.",
  "login.redirect": "Entrerete nella pagina \"Piattaforma di gestione commercianti\" dopo {keyProp} secondi.",
  "login.suc": "Accesso riuscito",
  "login.fail": "Accesso fallito",
  "enter.nowait": "Nessuna attesa, clicca per entrare",
  "agent.type": "Tipi di agenti",
  "请勿输入非法字符": "Si prega di non inserire caratteri illegali."
}