export default {
  "中国港澳台及海外地区": "Cina, Hong Kong, Macao, Taiwan e aree d'oltremare",
  "中国大陆地区": "regione della Cina continentale",
  "代理商类型": "Tipi di agenti",
  "类型": "tipo",
  "请选择代理商类型": "Si prega di selezionare il tipo di agente.",
  "运营区域": "Area di vendita autorizzata",
  "请选择可销售的区域": "Si prega di selezionare l'area vendibile.",
  "新增代理商": "Nuovo agente",
  "一级代理商": "Agente di primo livello",
  "二级代理商": "Agente di secondo livello",
  "一级": "Primo livello",
  "二级": "secondo livello",
  "代理账号": "Conto rappresentante",
  "公司所在地": "Sede della società",
  "注册时间": "data di registrazione",
  "注册地区": "Regione di registrazione",
  "销售区域": "Area di vendita",
  "上级代理商名称": "Nome dell'agente di livello superiore",
  "拓展门店数": "Espandere il numero di negozi",
  "激活绑定数": "Numero di attivazioni/Numero di dispositivi collegati",
  "前往文件中心": "Vai al \"Centro Documenti\"",
  "知道了": "Capito",
  "结束日期": "data di conclusione",
  "开始日期": "Data di inizio",
  "公司所在地不完整": "La sede dell'azienda non è completa.",
  "请输入纯数字": "Inserisci il numero di telefono in cifre."
}