export default {
  "open.platform.title": "Piattaforma Aperta PUDU",
  "open.platform.desc": "La piattaforma aperta di Purdue può fornire servizi software e hardware aperti per gli sviluppatori di business dei robot. Con l'aiuto della piattaforma aperta di Purdue, gli sviluppatori possono sfruttare appieno tutte le funzionalità dei robot, combinare i robot con varie industrie, completare lo sviluppo del business dei robot da zero e creare possibilità infinite per il progetto.",
  "H-C.interaction": "Interazione uomo-macchina",
  "navigation.control": "Controllo di navigazione",
  "voice.play": "Riproduzione vocale",
  "full.amount.data": "Dati completi",
  "view.api.doc": "Consultare la documentazione API aperta",
  "know.detail": "Comprendere i dettagli",
  "apply.sdk": "Richiesta di SDK per il controllo remoto",
  "apply.agent": "Richiesta di rappresentanza",
  "apply.people": "Richiedente",
  "apply.email": "Indirizzo email del richiedente",
  "apply.purpose": "Scopo della domanda",
  "device.id": "ID dell'attrezzatura",
  "device.secret": "Chiave segreta",
  "app.secret": "Chiave applicativa",
  "apply.time": "Tempo di domanda",
  "applicant.info": "Informazioni sul richiedente",
  "receive.email": "Casella di posta per la ricezione delle informazioni",
  "apply.app.info": "Domanda di informazioni sull'applicazione",
  "applicable.stores": "Negozi applicabili",
  "app.stores.tip": "Seleziona il negozio di appartenenza del robot che necessita del controllo remoto.",
  "apply.functions": "Funzione di richiesta",
  "apply.desc": "Stai facendo domanda per il \"SDK aperto per il controllo remoto\", gli sviluppatori possono utilizzare le capacità aperte di questo SDK nella loro piattaforma autonoma per chiamare a distanza i robot nei negozi.",
  "api.doc.desc": "Documentazione SDK per il controllo remoto aperto",
  "api.sdk.download": "Dopo l'approvazione, è possibile scaricare.",
  "openplatform.email": "E-mail per le domande degli sviluppatori di Purdue",
  "email.input.tip": "È essenziale compilare correttamente per ricevere la chiave segreta e le informazioni SDK dopo l'approvazione della domanda.",
  "approved.tip": "Modificare le informazioni dell'applicazione sarà immediatamente effettivo, senza la necessità di una nuova verifica.",
  "regionId.diff.tip": "L'indirizzo di origine del negozio è diverso.",
  "voice.play.mgt": "Gestione della riproduzione vocale",
  "voice.play.subtitle": "Configurazione personalizzata dell'annuncio vocale per diversi scenari, come attrarre clientela, promozione e accaparramento di clienti, rendendo il robot un esperto di marketing ancora più professionale.",
  "emoticon.interface.mgt": "Interfaccia di gestione delle espressioni",
  "emoticon.interface.subtitle": "Impostazioni personalizzate di diverse espressioni di robot interessanti e divertenti, rendendo il robot più attraente per i clienti.",
  "open.platform.subtitle": "Le capacità tecnologiche complete dei robot sono aperte, aiutando gli sviluppatori a realizzare applicazioni in tutti i settori industriali.",
  "emo.pack.name": "Nome della faccina",
  "emo.pack.create": "Creare pacchetti di emoticon personalizzati",
  "apply.scope": "Ambito di applicazione",
  "opr.steps": "Passaggi Operativi",
  "opr.steps.sub": "È essenziale eseguire le operazioni secondo le istruzioni, altrimenti l'impostazione fallirà.",
  "steps.1": "Passo 1",
  "steps.1.desc": "Scarica il file della raccolta di emoji del robot attuale.",
  "steps.2": "Passo 2",
  "steps.2.desc": "Sostituire uno per uno i file originali con i nuovi file delle espressioni.",
  "steps.2.desc.ketty": "La zucca include 2 gruppi di emoji: \"double_eye\" e \"single_eye\". Scegli di sostituire uno dei gruppi di emoji, utilizza il \"nuovo file emoji\" per sostituire un gruppo di emoji nelle cartelle \"animazione\" e \"prima immagine\".",
  "steps.2.ps1": "La gerarchia, la denominazione e il numero delle cartelle e dei file devono essere mantenuti rigorosamente invariati.",
  "steps.2.ps2": "2. La risoluzione dell'immagine è di 1920*1200 pixel, il formato è .png; il formato delle emoticon è .mp4; la cartella intera non deve superare i 50MB.",
  "steps.2.ps2.ketty": "2. La risoluzione dell'immagine del primo fotogramma è 1280*800, in formato .png, entro 100KB; il formato dell'animazione delle emoticon è .mp4, con risoluzione 1280*800, entro 4MB.",
  "steps.3": "Passaggio 3",
  "steps.3.desc": "Seleziona tutti i file delle emoticon, comprimili in un pacchetto file .zip e procedi con il caricamento.",
  "steps.3.desc.ps": "Non comprimere le cartelle annidate esternamente.",
  "emo.info": "Pacchetto di emoticon",
  "key.emo.use.tip": "Questo pacchetto di emoticon è valido solo per il modello {key}",
  "emo.upload": "Carica il pacchetto di emoticon",
  "upload.del.confirm": "Eliminerai definitivamente il file, confermi?",
  "scope.agent": "Tutti i robot",
  "key.scope.agent": "Tutti i robot {key}",
  "scope.store": "Tutti i robot del negozio designato",
  "scope.robot": "Robot designato",
  "emo.upload.tip": "Si prega di caricare il file zip, la dimensione totale deve essere inferiore a 50 MB.",
  "emo.step.info.1": "Sostituisci gradualmente i file delle espressioni seguendo la cartella emo.",
  "emo.step.info.2": "La struttura delle cartelle, i nomi delle cartelle e dei file non possono essere modificati.",
  "emo.step.info.3": "Il file non deve superare i 50M, la risoluzione dell'immagine deve essere di 1920*1200 pixel, il formato delle emoticon deve essere MP4.",
  "emo.step.info.4": "File di espressioni di gioia, rabbia, tristezza e felicità, orecchie sinistra e destra, ecc., 14 MP4 + 1 PNG come immagine segnaposto (senza l'immagine segnaposto si verificherà uno schermo nero durante il cambio di espressione)",
  "imp.robots.step1": "Scarica il modello",
  "imp.robots.step2": "Inserisci il MAC nel modello",
  "not.in.stock": "Non disponibile in magazzino",
  "key.not": "Non è {key}",
  "del.emoji.tip": "Dopo l'eliminazione, non influisce sui pacchetti di emoticon già utilizzati dal robot.",
  "store.list": "Elenco dei negozi",
  "robot.list": "Lista dei robot",
  "name.repeat": "Nome duplicato",
  "record.repeat": "Ci sono voci duplicate.",
  "zip.content.abnormal": "Non è stato compresso il file della raccolta di emoji come richiesto.",
  "scop.tip1": "1. Tutto: {key} verrà inviato a tutti i robot sotto l'agente. I nuovi robot associati otterranno automaticamente {key}.",
  "scop.tip2": "2. Per negozio: {key} verrà inviato solo ai robot sotto il negozio selezionato, i nuovi robot legati al negozio selezionato otterranno automaticamente {key}.",
  "scop.tip3": "3. In base alla macchina: {key} verrà inviato solo ai robot selezionati.",
  "emoji.pkg": "pacchetto di emoticon",
  "voice.pkg": "Pacchetto vocale",
  "key.voice.use.tip": "Questo pacchetto vocale è valido solo per il modello {key}",
  "voice.del.tip": "Dopo l'eliminazione, non verrà più riprodotto alcun contenuto vocale in questo scenario.",
  "batch.step1": "Scarica il foglio Excel di confronto tra voiceID e scene di narrazione vocale.",
  "batch.step2": "Secondo la \"tabella di corrispondenza tra voiceID e scene\", rinomina uno per uno i nomi dei file mp3 delle voci personalizzate con il rispettivo voiceID.",
  "batch.step2.ps1": "1) Assicurati che ogni file audio sia nominato con il corretto voiceID, altrimenti il caricamento fallirà.",
  "batch.step3": "Dopo aver inserito tutte le voci personalizzate in una cartella, seleziona la cartella per un caricamento batch.",
  "batch.step3.ps1": "1) Attenzione a non comprimere la cartella",
  "batch.step3.ps2": "2) È possibile caricare fino a un massimo di 300 file audio per volta, con ciascun file che non superi i 3MB.",
  "batch.btn": "Seleziona la cartella da caricare",
  "file.type.error": "Tipo di file errato",
  "count.limit": "Il numero di documenti supera il limite di {key}",
  "wrong.file.type": "Tipo di file errato",
  "file.size.exceeds": "La dimensione del file supera il limite di {key}",
  "voice.packing.tip": "Non chiudere la pagina, pacchetto vocale in fase di sintesi...",
  "business.district.desc": "I robot posizionati nelle aree commerciali possono consegnare i pasti di più ristoranti."
}