export default {
  "bd.account": "conto",
  "bd.username": "Nome",
  "bd.role": "personaggio",
  "bd.name": "Nome del distretto commerciale",
  "bd.numOfStores": "Numero di negozi",
  "bd.createtime": "Data di creazione",
  "bd.updatetime": "Tempo di aggiornamento",
  "bd.operation": "operazione",
  "bd.check": "Controlla",
  "bd.edit": "redattore",
  "bd.qrcode": "Scarica il codice QR",
  "bd.new": "Nuovo",
  "bd.goback": "ritorno",
  "bd.account.placeholder": "Inserisci il numero dell'account",
  "bd.name.placeholder": "Inserisci il nome del distretto commerciale",
  "bd.inquire": "Richiesta",
  "bd.reset": "Reimpostazione",
  "bd.store.tip": "Si prega di selezionare il negozio",
  "bd.store.placeholder": "Inserisci i vostri nomi",
  "bd.map.tip": "Si prega di selezionare la mappa",
  "bd.store.order": "Numero di serie",
  "bd.store.name": "Nome del negozio",
  "bd.store.label": "Scegli il negozio",
  "bd.map.label": "Scegli la mappa",
  "bd.map.name": "Nome della mappa",
  "bd.map.uploadtype": "Tipo di caricamento",
  "bd.map.association": "Numero di prodotti correlati",
  "bd.map.version": "versione",
  "bd.map.using": "In uso",
  "bd.map.unused": "Non utilizzato",
  "bd.map.uploadtype.apk": "Caricamento APK",
  "bd.map.uploadtype.platform": "Caricamento sulla piattaforma",
  "bd.map.choose": "selezione",
  "bd.store.industry": "settore",
  "bd.store.address": "Indirizzo del negozio",
  "bd.store.normal": "normale",
  "bd.store.logout": "Annullamento",
  "bd.insiders.noOperatingAuthority": "Il personale interno non ha il permesso di operare!",
  "bd.store.reminder": "Suggerimento: È possibile selezionare solo i negozi nello stato \"normale\"."
}