export default {
  "component.tagSelect.expand": "sviluppare",
  "component.tagSelect.collapse": "Ritirare",
  "component.tagSelect.all": "tutto",
  "key.select.max": "Scegli al massimo {key} robot.",
  "trial.period.day": "Periodo di prova/giorni",
  "lease.cycle.month": "Periodo di locazione/mese",
  "required.warn": "Deve compilare i campi obbligatori.",
  "first.imp.time": "Data della prima importazione",
  "validate.robot.key.warn": "Inserisci l'intero SN (PID) o il MAC",
  "change.to.complex.query": "Passa alla ricerca avanzata",
  "change.to.simple.query": "Passa alla ricerca semplice",
  "openapi.docs": "Documentazione per lo sviluppo di API",
  "customer.name": "Nome del commerciante",
  "key.template": "modello",
  "confirm.file.upload": "Si prega di confermare se il file è stato caricato completamente.",
  "upload.fail": "Caricamento fallito, si prega di riprovare.",
  "key.success": "successo",
  "key.fail": "fallimento",
  "import.result": "Risultato dell'importazione",
  "incompatibility.versions": "La nuova versione non è compatibile con la vecchia versione.",
  "auto.jump.available": "Verrà reindirizzato automaticamente alla versione disponibile...",
  "import.maxcount.tip": "È stato rilevato che sono stati superati i {count} MAC, il sistema importerà solo i primi {count} MAC, gli altri MAC dovranno essere importati nuovamente."
}