export default {
  "dc.total": "Totale",
  "dc.yesterday": "Ieri",
  "dc.last7days": "Negli ultimi 7 giorni",
  "dc.last30days": "Negli ultimi 30 giorni",
  "dc.naturalDay": "giorno naturale",
  "dc.natureWeek": "Settimana naturale",
  "dc.naturalMonth": "mese solare",
  "dc.chainRatio": "confronto sequenziale",
  "dc.cumulativeNumber": "numero cumulativo",
  "dc.activeRate": "Tasso di attività",
  "dc.robotOperationOverview": "Panoramica del funzionamento della macchina",
  "dc.workTime": "Durata del lavoro",
  "dc.runningMileage": "chilometraggio in esercizio",
  "dc.taskTimes": "Esecuzione del compito",
  "dc.robotRunningPeakTrend": "Tendenza di picco operativo dei robot",
  "dc.monthOnMonth": "Confronto anno su anno e confronto mese su mese",
  "dc.numberOfRobotRuns": "robot in esecuzione",
  "dc.stages": "{num} dispositivi",
  "dc.robotOverview": "Panoramica della macchina",
  "dc.powerOnRobot": "Robot all'avvio",
  "dc.bindTheRobot": "Legare il robot",
  "dc.activateRobot": "Attiva il robot",
  "dc.numberOfRobotsBound": "Numero di macchine collegate",
  "dc.numberOfActiveRobots": "Numero di macchine attivate",
  "dc.storeOverview": "Panoramica del negozio",
  "dc.numberOfActiveStores": "Numero di negozi attivi",
  "dc.numberOfNewStores": "Numero di nuovi negozi",
  "dc.activeStore": "Negozi attivi",
  "dc.silentStore": "Negozio Silenzioso",
  "dc.activeRobotPoweredOn": "Robot attivo all'accensione",
  "dc.downtime": "Durata della sospensione",
  "dc.operatingHours": "ore di funzionamento",
  "dc.emptyActiveStore": "Nessun negozio attivo al momento",
  "dc.emptySilentStore": "Nessun negozio Silent temporaneamente",
  "dc.export": "Esportare",
  "dc.addStore": "Nuovo punto vendita",
  "dc.cumulativeStores": "Negozi accumulati",
  "dc.storeName": "Nome del negozio",
  "dc.storeNamePlaceholder": "Inserisci il nome del negozio",
  "dc.query": "Richiesta",
  "dc.activeRank": "Classifica Attiva",
  "dc.creationTime": "Data di creazione",
  "dc.activeRobot": "Robot all'avvio",
  "dc.runTime": "durata di funzionamento",
  "dc.key.robot": "robot",
  "dc.key.boottime": "Tempo di accensione",
  "dc.key.starttime": "Orario di inizio funzionamento",
  "dc.task.number": "Numero di compiti",
  "dc.robots.all": "Tutti i robot",
  "dc.robot.select": "Si prega di selezionare il robot.",
  "dc.tab.delivery": "Dati di spedizione",
  "dc.tab.cruise": "Dati di crociera",
  "dc.tab.greeter": "Dati di posizionamento",
  "dc.tab.interaction": "Dati di interazione",
  "dc.tab.solicit": "Dati sui clienti",
  "dc.tab.grid": "Dati della griglia del palazzo",
  "dc.tab.ad": "Dati pubblicitari",
  "dc.tab.recovery": "Dati di controfferta",
  "dc.mileage": "chilometraggio in esercizio",
  "dc.runtime": "durata di funzionamento",
  "dc.interactiveVisits": "Interazioni utente",
  "dc.interactionTime": "Durata dell'interazione",
  "dc.greetings": "Numero di saluti",
  "dc.reached": "Contatti utente",
  "dc.attract": "Attrarre visitatori",
  "dc.voiceInteractions": "Numero di interazioni vocali",
  "dc.voiceinteractionTime": "Durata dell'interazione vocale",
  "dc.takeMeInCount": "\"Portami in negozio\" tipo di schema a griglia",
  "dc.featuredItemCount": "\"Griglia di prodotti caratteristici\"",
  "dc.favorablePromotionsCount": "\"Promozione\" Categoria Griglia",
  "dc.guideToMenuCount": "\"Classi di posti a sedere\"",
  "dc.posterCount": "\"Poster\" di tipo griglia regale",
  "dc.usherCount": "\"Tipo di schema a griglia 'Guida la strada'\"",
  "dc.danceCount": "\"Quadrato di ballo\"",
  "dc.videoPosterCount": "\"Poster video\" a griglia",
  "dc.smallScreenExposureTime": "Durata della riproduzione su schermo piccolo",
  "dc.smallScreenExposures": "Numero di riproduzioni su schermo piccolo",
  "dc.bigScreenExposureTime": "Durata della riproduzione su grande schermo",
  "dc.bigScreenExposures": "Numero di riproduzioni su grande schermo",
  "dc.deliveryTables": "numero di tavoli da consegnare",
  "dc.deliveryPlate": "Numero di piatti consegnati",
  "dc.numberOfTieLessons": "Numero di volte che si accompagna il cliente al tavolo",
  "dc.numberOfCleanTables": "Pulire il numero dei tavoli",
  "tip.export.nodata": "Non ci sono dati da esportare.",
  "dc.robotOperationOverview.toolTip": "Le condizioni operative generali del robot",
  "dc.robotOperationOverview.toolTip-1": "Durata del lavoro (h): nell'intervallo di date, il numero totale di ore di funzionamento accumulate dai robot associati ai negozi espansi dall'agente.",
  "dc.robotOperationOverview.toolTip-2": "Durata del lavoro (h): nell'intervallo di date, il numero totale di ore di funzionamento accumulate dai robot associati ai negozi espansi dall'agente.",
  "dc.robotOperationOverview.toolTip-3": "3. Numero di esecuzioni del compito: nel periodo di tempo specificato, il numero totale di esecuzioni del compito accumulate dai robot associati ai negozi sviluppati dall'agente.",
  "dc.robotRunningPeakTrend.toolTip": "Tendenza di picco operativo dei robot",
  "dc.robotRunningPeakTrend.toolTip-1": "1. Giorno naturale: è possibile consultare il numero di unità operative di robot di varie categorie in qualsiasi intervallo di 24 ore di un giorno qualsiasi.",
  "dc.robotRunningPeakTrend.toolTip-2": "2. Settimana naturale: è possibile interrogare il numero di unità operative di vari robot per ogni giorno di una qualsiasi settimana.",
  "dc.robotRunningPeakTrend.toolTip-3": "3. Mese naturale: è possibile consultare qualsiasi mese, il numero di unità operative di vari tipi di robot per ogni giorno.",
  "dc.robotOverview.toolTip": "Attivazione e stato attivo del robot",
  "dc.robotOverview.toolTip-1": "Robot di avvio: il numero cumulativo di avvio di tutti i robot legati ai negozi espansi dagli agenti nel periodo di tempo specificato.",
  "dc.robotOverview.toolTip-2": "2. Numero cumulativo: il numero totale di robot collegati dall'agente dall'inizio del primo collegamento del robot al negozio fino alla data di fine del periodo di selezione.",
  "dc.robotOverview.toolTip-3": "3. Tasso di attività = Nel periodo di tempo specificato, (numero di robot attivi ÷ numero totale) * 100%.",
  "dc.robotOverview.toolTip-4": "4. Associazione robot: numero totale di robot associati all'agente nel negozio entro l'intervallo di date.",
  "dc.robotOverview.toolTip-5": "5. Attivazione dei robot: numero totale di robot attivati legati ai negozi dall'agente entro l'intervallo di date.",
  "dc.storeOverview.toolTip": "Espansione dei negozi attivi e nuove aperture",
  "dc.storeOverview.toolTip-1": "Numero di negozi attivi: nel periodo specificato, i negozi sviluppati dall'agente, in cui è presente un robot in funzione, sono considerati come un singolo negozio attivo.",
  "dc.storeOverview.toolTip-2": "2. Numero cumulativo: dalla data del primo collegamento dell'agente al negozio, fino alla data di scadenza del filtro, il numero totale di negozi accumulati.",
  "dc.storeOverview.toolTip-3": "3. Tasso di attività = Nel periodo di riferimento, (Numero di negozi attivi ÷ Numero cumulativo) * 100%.",
  "dc.storeOverview.toolTip-4": "4. Numero di nuovi negozi: nel periodo specificato, il numero totale di nuovi negozi aggiunti.",
  "dc.storeOverview.toolTip-5": "5. Top 10 dei negozi più attivi: nell'intervallo di date, tra i negozi sviluppati dall'agente, quelli con un tasso di utilizzo dei robot più alto e un tempo di funzionamento più lungo avranno una posizione più alta nella classifica dell'attività del negozio.",
  "dc.storeOverview.toolTip-6": "Top 10 dei negozi inattivi: nel periodo specificato, i negozi sviluppati dall'agente, nei quali l'attività dei robot è cessata e l'attività è pari a zero, sono considerati negozi inattivi. Più robot sono disattivati e più lungo è il periodo di inattività, più alta sarà la posizione del negozio nella classifica degli inattivi.",
  "dc.activeStore.toolTip": "Nell'intervallo di date, tra i negozi sviluppati dall'agente, quelli che dispongono di robot in funzione sono considerati come 1 negozio attivo.",
  "dc.silentStore.toolTip": "Tutte le macchine collegate all'interno del negozio non sono state accese durante l'intervallo di date, considerato come un negozio silenzioso.",
  "dc.addStore.toolTip": "Numero totale di nuovi negozi aggiunti nell'intervallo di date.",
  "dc.cumulativeStores.toolTip": "Dalla data del primo collegamento dell'agente con il negozio, fino alla data di scadenza del filtro, il numero totale dei negozi accumulati.",
  "robot.status.bind.tip": "1. Già scollegato: il robot è attualmente collegato ad un altro negozio, questi dati sono i dati storici del negozio filtrati per la data selezionata.",
  "robot.status.unbind.tip": "2, Già collegato: il robot è attualmente collegato a questo negozio, questi dati sono i dati operativi del negozio per le date selezionate.",
  "cruise.tip.run.mileage": "Nell'intervallo di date, il totale dei chilometri percorsi in crociera da tutti i robot legati ai negozi espansi dall'agente.",
  "cruise.tip.run.duration": "Nell'intervallo di date, la durata totale del funzionamento in crociera di tutti i robot legati sotto il negozio espanso dall'agente.",
  "cruise.tip.interaction.times": "Nell'intervallo di date, il numero totale di interazioni di tutti i robot collegati sotto il negozio espanso dall'agente.",
  "cruise.tip.interaction.duration": "Nell'intervallo di date, la durata totale dell'interazione di tutti i robot collegati sotto l'agenzia che espande i negozi.",
  "delivery.tip.run.mileage": "Nell'intervallo di date, il totale dei chilometri percorsi per le consegne di tutti i robot legati ai negozi espansi dall'agente.",
  "delivery.tip.run.duration": "Nell'intervallo di date, la durata totale delle consegne effettuate da tutti i robot legati ai negozi espansi dall'agente",
  "delivery.tip.task.num": "Nell'intervallo di date, il numero totale di compiti eseguiti da tutti i robot associati al negozio",
  "delivery.tip.delivery.tables": "Nell'intervallo di date, il numero di tavoli da pranzo serviti da tutti i robot collegati sotto l'espansione dell'agenzia del negozio.",
  "delivery.tip.delivery.plates": "Nell'intervallo di date, il numero di vassoi di consegna dei robot associati a tutti i negozi espansi dall'agente.",
  "greeter.tip.run.mileage": "Nell'intervallo di date specificato, il totale dei chilometri percorsi dai robot assegnati a tutti i negozi espansi dall'agente.",
  "greeter.tip.run.duration": "Nell'intervallo di date, la durata totale dell'operazione di guida dei robot associati sotto tutti i negozi espansi dall'agente.",
  "greeter.tip.task.times": "Nell'intervallo di date, il numero di volte in cui l'agente ha espanso i compiti di leadership per tutti i robot vincolati sotto il negozio.",
  "interaction.tip.all.times": "Nell'intervallo di date specificato, conta il numero di interazioni uomo-macchina (tocco, interazione vocale) generate da tutti i robot associati ai negozi gestiti dall'agente.",
  "interaction.tip.voice.times": "Nell'intervallo di date, il numero di interazioni vocali dei robot legati a tutti i negozi espansi dall'agente.",
  "interaction.tip.duration": "Nell'intervallo di date, la durata cumulativa delle interazioni vocali di tutti i robot collegati sotto l'agenzia che espande i negozi.",
  "solicit.tip.duration": "Nell'intervallo di date, la durata totale di funzionamento dei robot di accoglienza legati a tutti i negozi espansi dall'agente",
  "solicit.tip.hello.times": "Nel periodo specificato, conta il numero di volte in cui i robot associati a tutti i negozi gestiti dall'agente hanno dato il benvenuto.",
  "solicit.tip.reached.times": "Nell'intervallo di date, il numero di volte in cui gli utenti sono stati raggiunti da tutti i robot collegati sotto il negozio espanso dall'agente.",
  "solicit.tip.attach.times": "Nell'intervallo di date, l'agente espande tutti i robot vincolati nei negozi per raggiungere gli utenti, e il numero di persone che si fermano e si soffermano.",
  "solicit.tip.interation.times": "Nell'intervallo di date specificato, il numero di volte in cui tutti i robot collegati ai negozi espansi dall'agente sono stati attivati dagli utenti.",
  "grid.click.times": "Nell'intervallo di date, il numero di volte in cui questa funzione è stata cliccata su tutti i robot collegati sotto il negozio espanso dall'agente.",
  "ad.tiny.play.duration": "Nell'intervallo di date, la durata della riproduzione degli annunci su schermi piccoli in tutti i robot collegati sotto i negozi espansi dall'agente.",
  "ad.tiny.play.times": "Nell'intervallo di date specificato, il numero di volte in cui gli annunci pubblicitari su schermi piccoli sono stati riprodotti su tutti i robot collegati nei negozi espansi dall'agente.",
  "ad.large.play.duration": "Nell'intervallo di date, la durata della riproduzione degli annunci pubblicitari su grande schermo in tutti i robot collegati sotto i negozi espansi dall'agente.",
  "ad.large.play.times": "Nell'intervallo di date, il numero di volte in cui gli annunci pubblicitari su grande schermo sono stati riprodotti in tutti i robot collegati sotto il negozio espanso dall'agente.",
  "recycle.tip.mileage": "Nell'intervallo di date, il chilometraggio totale percorso dai robot legati a tutti i negozi espansi dall'agente.",
  "recycle.tip.duration": "Nell'intervallo di date, la durata totale di funzionamento delle offerte di ritorno di tutti i robot vincolati sotto il negozio espanso dall'agente.",
  "recycle.tip.tables": "Nell'intervallo di date, il numero di volte in cui i tavoli sono stati puliti e ripristinati dai robot legati a tutti i negozi espansi dall'agente.",
  "by.key": "Premi {key}",
  "by.store": "Secondo il negozio",
  "by.robot": "secondo la macchina",
  "by.day": "a giornata",
  "by.hour": "a ore",
  "export.config": "Esporta configurazione",
  "timeby.config.label": "Regole di configurazione per l'esportazione dei dati per intervallo di tempo",
  "robot.sn_mac": "Robot SN/MAC",
  "dc.clean.area.total": "Area totale da pulire (m²)",
  "dc.clean.area.total.tip": "Nell'intervallo di date, l'area totale accumulata pulita dai robot legati a tutti i negozi espansi dall'agente.",
  "dc.clean.time.total": "Durata totale della pulizia (h)",
  "dc.clean.time.total.tip": "Intervallo di date, durata totale cumulativa della pulizia di tutti i robot associati ai negozi sviluppati dall'agente.",
  "dc.clean.task.number": "Compiti di pulizia",
  "dc.clean.task.number.tip": "Nell'intervallo di date, il numero totale di compiti di pulizia eseguiti dai robot associati a tutti i negozi espansi dall'agente.",
  "dc.power.consumption": "Situazione del consumo di energia (kW*h)",
  "dc.power.consumption.tip": "Nell'intervallo di date, il consumo totale di energia elettrica accumulato dai robot associati a tutti i negozi espansi dall'agente.",
  "dc.water.consumption": "Quantità di acqua consumata (ml)",
  "dc.water.consumption.tip": "Nell'intervallo di date, il consumo cumulativo di acqua di tutti i robot vincolati ai negozi espansi dall'agente.",
  "dc.tab.all": "Tutte le modalità",
  "dc.tab.scrubbing": "Modalità di lavaggio del pavimento",
  "dc.tab.sweeping": "Modalità di pulizia del pavimento",
  "dc.sweep.vacuuming": "Aspirapolvere per tappeti",
  "dc.sweep.dustpush": "Spinta silenziosa della polvere",
  "dc.delivery": "Consegna",
  "dc.clean": "Pulizia",
  "dc.time": "tempo",
  "dc.基本数据": "Dati di base",
  "dc.清洁任务分布": "Compito di pulizia in esecuzione distribuito",
  "dc.清洁任务分布描述": "Nell'intervallo di date, la somma del numero di compiti eseguiti ogni ora in un giorno naturale da tutti i robot associati al negozio. (Esempio: se si seleziona l'intervallo dall'1 gennaio al 2 gennaio, e il 1 gennaio vengono eseguiti compiti dalle 1:00 alle 2:00 e il 2 gennaio viene eseguito un compito all'1:00, allora la distribuzione dei compiti alle 1:00 sarà di 2, e alle 2:00 sarà di 1).",
  "dc.robot.delivery.tip": "Questa macchina non è un modello da distribuzione.",
  "dc.robot.clean.tip": "Questa macchina non è un tipo di macchina per la pulizia.",
  "dc.store.unknow": "Mi dispiace, non ho trovato quel negozio.",
  "dc.mileage.tip": "Il chilometraggio include solo i dati di funzionamento dei robot di consegna, escludendo i dati di funzionamento dei robot per la pulizia.",
  "input.name.search": "Inserisci {key} per cercare"
}