export default {
  "log.boot": "Accensione e autotest",
  "log.abnormal": "Anomalia di guasto",
  "log.charge": "Registro di ricarica",
  "log.battery": "Stato di salute della batteria",
  "production.date": "Data di creazione",
  "boot.status": "stato",
  "boot.undetected": "Non rilevato",
  "boot.normal": "normale",
  "boot.abnormal": "anomalo",
  "key.no": "codice",
  "log.production.time": "Tempo di generazione del log",
  "log.push.time": "Tempo di migrazione del log al cloud",
  "boot.description": "descrizione",
  "boot.check_module": "Stato del modulo di autodiagnosi",
  "poweron.ratio": "Percentuale di memorizzazione (%)",
  "robot.softVer": "versione del software",
  "robot.hardVer": "Versione del firmware",
  "common.systemid": "Versione del sistema operativo",
  "common.battery": "Livello di carica attuale",
  "check.abnormal": "Esiste un'anomalia",
  "check.normal": "Nessuna anomalia",
  "error.category": "Tipo di guasto",
  "error.detail": "Dettagli del guasto",
  "error.grade": "Livello di guasto",
  "error.list": "Elenco dei guasti",
  "error.ID": "ID guasto",
  "filter.more": "Maggiori filtri",
  "charge.count_battery": "Quantità di carica della batteria",
  "charge.count_time": "Durata della ricarica",
  "soh.battery_sn": "Numero di serie della batteria",
  "soh.full": "Capacità della batteria (mAh)",
  "soh.remaining": "Capacità residua (mAh)",
  "soh.battery_voltage": "Tensione della batteria (mV)",
  "soh.soh": "Indice di salute della batteria",
  "soh.cycle": "Numero di cicli",
  "soh.battery_type": "Tipo di batteria",
  "tip.soh": "Il log verrà riportato solo quando questo campo subisce una modifica.",
  "key.clip": "Copia con un clic",
  "collapse": "Ritirare",
  "please.select": "Si prega di scegliere",
  "please.input": "Si prega di inserire",
  "cycle.range.tip": "L'intervallo di ciclo non ha dati."
}