export default {
  "menu.dataCenter": "Centro dati",
  "menu.dataCenter.dashBoard": "Cruscotto",
  "menu.dataCenter.operationAnalysis": "Analisi operativa",
  "menu.dataCenter.operationAnalysis.aStoreOperations": "Classifica delle prestazioni dei negozi",
  "menu.dataCenter.operationAnalysis.bStoreProduct": "Classifica delle operazioni di prodotto",
  "menu.dataCenter.operationAnalysis.cAtiveProduct": "Analisi dei prodotti attivi",
  "menu.dataCenter.operationAnalysis.sProductRoom": "Statistiche delle consegne dei prodotti",
  "menu.dataCenter.operationAnalysis.eProductBackPlate": "Statistiche delle attività di controfferta del prodotto",
  "menu.dataCenter.operationAnalysis.fProductDisinfect": "Statistiche sul compito di disinfezione del prodotto",
  "menu.dataCenter.operationAnalysis.gProductRunning": "Panoramica sull'operatività del prodotto",
  "menu.dataCenter.operationAnalysis.hProductDaily": "Dati giornalieri medi del prodotto",
  "menu.dataCenter.operationAnalysis.iShopOperation": "Statistiche operative del negozio per fasce orarie",
  "menu.dataCenter.operationAnalysis.jProductGrameTime": "Statistiche operative del periodo del prodotto",
  "menu.dataCenter.operationAnalysis.kShopEverydayOperation": "Statistiche giornaliere di funzionamento del negozio",
  "menu.dataCenter.operationAnalysis.LShopSevenOperation": "Statistiche operative medie degli ultimi sette giorni del punto vendita",
  "menu.dataCenter.operationAnalysis.mProductEverydayOperation": "Statistiche giornaliere sull'operatività del prodotto",
  "menu.dataCenter.operationAnalysis.nProductSevenOperation": "Statistiche operative dei dati del prodotto sette",
  "menu.dataCenter.operationAnalysis.VRobotTaskAnalysis": "Analisi dei compiti del robot",
  "menu.reportLog": "Registro dei rapporti",
  "menu.reportLog.foodDelivery": "Compito di consegna del pasto",
  "menu.reportLog.recycleDish": "Compito di controfferta",
  "menu.reportLog.disInfect": "Compito di disinfezione",
  "menu.reportLog.flashDelivery": "Compito di consegna oggetti in camera",
  "menu.reportLog.powerOn": "Accensione e autotest",
  "menu.reportLog.charge": "Registro di ricarica",
  "menu.reportLog.failure": "Anomalia di guasto",
  "menu.reportLog.upgrade": "Rapporto di aggiornamento",
  "menu.reportLog.batteryHealth": "Stato di salute della batteria",
  "menu.reportLog.AbnormalIPAddr": "Registrazione di indirizzi IP anomali",
  "menu.reportLog.about2fall_report": "Registro anti-caduta",
  "menu.valueAdded": "Servizi a valore aggiunto",
  "menu.valueAdded.custom": "Voce Personalizzata V1.1",
  "menu.valueAdded.customV1": "Voce Personalizzata V1.0",
  "menu.valueAdded.software": "Pacchetto funzionale del software",
  "menu.valueAdded.tts": "Domande e risposte TTS",
  "menu.valueAdded.sip": "Impostazioni del servizio telefonico SIP",
  "menu.account": "Gestione dell'account",
  "menu.account.accountConfig": "Configurazione dell'account",
  "menu.systemManage.AccountOperationHistory": "Storico delle operazioni",
  "menu.AccountOperationHistory": "Storico delle operazioni",
  "menu.systemManage": "Gestione del sistema",
  "menu.systemManage.dictionaryManagement": "Gestione del dizionario",
  "menu.systemManage.messageNotification": "Notifica di messaggio",
  "menu.openPlatform": "Piattaforma aperta",
  "menu.openPlatform.applicationCenter": "Centro di Domanda",
  "menu.openPlatform.developDoc": "Documentazione di sviluppo",
  "menu.returnManage": "Ritorno alla gestione",
  "menu.returnManage.record": "Registrazione di reso",
  "menu.returnManage.useReturn": "Utilizzo reso",
  "menu.customerCenter": "Centro Clienti",
  "menu.customerCenter.storeManagement": "Gestione del punto vendita",
  "menu.customerCenter.storeDetail": "Dettagli del negozio",
  "menu.customerCenter.bindRobots": "Legare il robot",
  "menu.customerCenter.bindARobot": "Aggiungi robot",
  "menu.customerCenter.storeRobotManagement": "Negozio di macchine",
  "menu.customerCenter.activeCodeManagement": "Codice di attivazione",
  "menu.customerCenter.financialInstitution": "istituzione finanziaria",
  "menu.customerCenter.financialDetail": "Dettagli dell'istituto finanziario",
  "menu.customerCenter.agent": "Gestione degli agenti",
  "menu.customerCenter.agentDetail": "Dettagli dell'agente",
  "menu.productCenter": "Centro prodotti",
  "menu.productCenter.productArchives": "Archivio del prodotto",
  "menu.fileCenter": "Centro documenti",
  "menu.fileCenter.mapFile": "File di mappa",
  "menu.fileCenter.formFile": "Documento di Accettazione",
  "menu.fileCenter.downloadFile": "Scaricamento del documento",
  "menu.equipmentCenter": "Centro prodotti",
  "menu.equipmentCenter.productArchives": "Archivio del prodotto",
  "menu.equipmentCenter.productLibrary": "Biblioteca dei prodotti meccanici",
  "menu.equipmentCenter.outboundProducts": "Prodotti spediti al distributore di livello inferiore",
  "menu.equipmentCenter.viewProductInfo": "Visualizza le informazioni sul prodotto",
  "menu.equipmentCenter.productEdit": "Informazioni sull'editore",
  "menu.equipmentCenter.installedProduct": "Prodotto installato",
  "menu.equipmentCenter.installedProducts": "Prodotto installato",
  "menu.equipmentCenter.flowCard": "Prodotto con carta SIM dati già associata",
  "menu.equipmentCenter.productDetail": "Dettagli del prodotto",
  "menu.equipmentCenter.productChangeRecord": "Registro delle modifiche del prodotto",
  "menu.equipmentCenter.product-change-records": "Registro delle modifiche dell'attrezzatura",
  "menu.equipmentCenter.flowCardChangeRecord": "Registro delle modifiche della carta SIM dati",
  "menu.equipmentCenter.assignedProduct": "Prodotto di manutenzione assegnato",
  "menu.equipmentCenter.unallocatedProduct": "Prodotti di manutenzione non assegnati",
  "menu.equipmentCenter.antiSmuggling": "Controllo del rischio di merce in fuga",
  "menu.equipmentCenter.accessories": "Gestione dei componenti",
  "menu.welcome": "Benvenuto",
  "menu.more-blocks": "Maggiori blocchi",
  "menu.home": "Pagina iniziale",
  "menu.admin": "Pagina di gestione",
  "menu.admin.sub-page": "Pagina di gestione di secondo livello",
  "menu.login": "Accesso",
  "menu.register": "registrazione",
  "menu.register.result": "Risultato della registrazione",
  "menu.dashboard.analysis": "Pagina di analisi",
  "menu.dashboard.monitor": "Pagina di monitoraggio",
  "menu.dashboard.workplace": "banco da lavoro",
  "menu.exception.403": "403",
  "menu.exception.404": "404",
  "menu.exception.500": "cinquecento",
  "menu.form": "Pagina del modulo",
  "menu.form.basic-form": "Modulo di base",
  "menu.form.step-form": "Modulo suddiviso in passaggi",
  "menu.form.step-form.info": "Modulo suddiviso in passaggi (inserimento delle informazioni di trasferimento)",
  "menu.form.step-form.confirm": "Modulo suddiviso in passaggi (conferma delle informazioni di trasferimento)",
  "menu.form.step-form.result": "Modulo a passi (completato)",
  "menu.form.advanced-form": "Modulo avanzato",
  "menu.list": "Pagina dell'elenco",
  "menu.list.table-list": "Modulo di richiesta",
  "menu.list.basic-list": "Lista standard",
  "menu.list.card-list": "Lista delle carte",
  "menu.list.search-list": "Elenco di ricerca",
  "menu.list.search-list.articles": "Elenco di ricerca (articoli)",
  "menu.list.search-list.projects": "Elenco di ricerca (progetto)",
  "menu.list.search-list.applications": "Elenco di ricerca (applicazioni)",
  "menu.profile": "Pagina dei dettagli",
  "menu.profile.basic": "Pagina dei dettagli di base",
  "menu.profile.advanced": "Pagina dei dettagli avanzata",
  "menu.result": "Pagina dei risultati",
  "menu.result.success": "Pagina di successo",
  "menu.result.fail": "Pagina di errore",
  "menu.exception": "Pagina Anomala",
  "menu.exception.not-permission": "403",
  "menu.exception.not-find": "404",
  "menu.exception.server-error": "cinquecento",
  "menu.exception.trigger": "Errore attivato",
  "menu.account.center": "Centro personale",
  "menu.account.settings": "Impostazioni personali",
  "menu.account.trigger": "Errore attivato",
  "menu.account.logout": "Esci dal login",
  "menu.editor": "Editor grafico",
  "menu.editor.flow": "Editor di flusso",
  "menu.editor.mind": "Editor di mappe mentali",
  "menu.editor.koni": "Editor di topologia",
  "menu.test": "test\n",
  "menu.dataCenter.operationAnalysis.oFoodDelivery": "Servizio di consegna prodotti Statistiche dei dati dei tavoli da pranzo",
  "menu.dataCenter.operationAnalysis.pReturnPlate": "Servizio di offerta di ritorno del prodotto Statistiche dei dati del tavolo da pranzo",
  "menu.dataCenter.operationAnalysis.RCruiseMode": "Modo di crociera del prodotto dati statistici",
  "menu.dataCenter.operationAnalysis.TSolicitCustomersMode": "Modelli di dati statistici per l'acquisizione di clienti dei prodotti",
  "menu.dataCenter.operationAnalysis.SLeadmode": "Modello di leadership del prodotto nella statistica dei dati",
  "menu.dataCenter.operationAnalysis.UAdPlayMode": "Statistiche sulla riproduzione degli annunci pubblicitari",
  "menu.customerCenter.rcagent": "Agente associato",
  "menu.customerCenter.equipment": "Apparecchiature di proprietà",
  "menu.customerCenter.financialInfo": "Dettagli dell'istituto di finanziamento",
  "menu.reportLog.SIMCardLog": "Carta SIM dati",
  "menu.SIMCardMgr": "Gestione della scheda SIM dati",
  "menu.SIMCardMgr.ActivedCardMgr": "Carta SIM dati attivata",
  "menu.SIMCardMgr.ExpiredCardMgr": "Avviso di scadenza della carta SIM dati",
  "menu.BusinessDistrictMgr": "Gestione del distretto commerciale",
  "menu.BusinessDistrictMgr.Add": "Nuovo",
  "menu.BusinessDistrictMgr.Edit": "redattore",
  "menu.BusinessDistrictMgr.Detail": "Controlla",
  "menu.dataCenter.dataOverview": "Panoramica dei dati",
  "menu.dataCenter.storeAnalysis": "Analisi del punto vendita",
  "menu.dataCenter.robotOperationAnalysis": "Analisi del funzionamento del robot",
  "menu.dataCenter.robotTaskAnalysis": "Dati di consegna del robot",
  "menu.dataCenter.cleanRobotData": "Robot per la pulizia dei dati",
  "menu.app-center": "Centro applicazioni",
  "menu.app-center.emoticon-mgmt": "Gestione delle espressioni del robot",
  "menu.app-center.emoticon-add": "Creare pacchetti di emoticon",
  "menu.app-center.emoticon-edit": "Modifica pacchetto di emoticon",
  "menu.app-center.voice-mgmt": "Gestione vocale dei robot",
  "menu.app-center.voice-add": "Creazione di pacchetti vocali personalizzati",
  "menu.app-center.voice-edit": "Modifica pacchetto vocale personalizzato",
  "menu.app-center.voice-auth": "Pacchetto di autorizzazione vocale",
  "menu.app-center.open-platform": "Piattaforma aperta",
  "menu.app-center.open-platform-detail": "Controlla",
  "menu.app-center.open-platform-add": "Domanda di applicazione",
  "menu.app-center.open-platform-edit": "Modifica applicazione",
  "menu.log-center": "Centro di registrazione",
  "menu.log-center.robot-logs": "Registro dei robot",
  "menu.message-center": "Centro notifiche",
  "menu.message-center.message-detail": "Dettagli del messaggio"
}