export default {
  "请输入": "Si prega di inserire",
  "选择": "selezione",
  "返回": "ritorno",
  "未绑定": "Non vincolato",
  "已安装": "Installato",
  "导入时间": "Tempo di importazione",
  "代理名称": "Nome dell'agente",
  "所属代理": "Agenzia di appartenenza",
  "出库撤回": "Ritiro dal magazzino",
  "出库撤回说明": "Istruzioni per il ritiro dal magazzino",
  "撤回后下级代理": "Dopo il ritiro, l'agente di livello inferiore non sarà in grado di visualizzare o operare il robot.",
  "出库撤回失败": "Annullamento del ritiro dal magazzino fallito",
  "该代理已将机器人绑定门店": "L'agente ha associato il robot al negozio.",
  "出库至下级代理": "Uscita verso l'agente di livello inferiore",
  "未选择下级代理商": "Non è stato selezionato alcun agente di livello inferiore.",
  "没有出库产品": "Nessun prodotto spedito",
  "确定出库": "Conferma dell'uscita dal magazzino",
  "出库说明": "Istruzioni per l'uscita dal magazzino",
  "选择未出库产品": "Seleziona il prodotto non ancora spedito",
  "选择下级代理商": "Selezionare un agente di livello inferiore",
  "代理商帐号": "Conto dell'agente",
  "注册地址": "Indirizzo di registrazione",
  "销售区域": "Area di vendita",
  "注册时间": "data di registrazione",
  "一级": "Primo livello",
  "二级": "secondo livello",
  "已损坏": "Danneggiato",
  "已锁机": "Dispositivo bloccato",
  "冻结中": "Congelato",
  "过期": "La verifica di fabbrica è scaduta.",
  "未激活": "Non attivato",
  "激活": "Attivazione",
  "已激活": "Attivato",
  "已入库": "Già in magazzino",
  "厂测中": "In fase di test in fabbrica",
  "无记录": "Nessun record",
  "全部": "tutto",
  "产品信息": "Informazioni sul prodotto",
  "维保信息": "Informazioni sulla manutenzione",
  "服务信息": "Informazioni sul servizio",
  "产品操作记录": "Registro operativo del prodotto",
  "换板待验证": "Cambio di pannello in attesa di verifica",
  "待验证": "Da verificare",
  "所属门店": "Negozio di appartenenza",
  "所属代理商": "Agenzia di appartenenza",
  "激活时间": "Tempo di attivazione",
  "昵称": "soprannome",
  "SN": "SN(PID)",
  "MAC": "MAC",
  "软件版本": "versione del software",
  "固件版本": "Versione del firmware",
  "现场用途": "Utilizzo sul posto",
  "机器分组": "Gruppo di macchine",
  "用机类型": "tipo di macchina",
  "保修时长": "Durata della garanzia",
  "实施工程师": "Ingegnere di implementazione",
  "运维工程师": "Ingegnere di manutenzione e operazioni",
  "首次导入代理": "Prima importazione di agenti:",
  "绑定代理": "Legare un agente:",
  "的门店": "delle filiali:",
  "从门店": "Dallo store:",
  "解绑返回代理": "Scollegare, tornare all'agente:",
  "代理": "Agente:",
  "出库产品到下级代理": "Prodotti spediti al sottorappresentante:",
  "从下级代理": "Da un agente di livello inferiore:",
  "出库撤回到代理": "Ritiro dal magazzino al rappresentante:",
  "操作说明": "Istruzioni per l'uso:",
  "操作人": "Operatore:",
  "机器产品库使用提示": "Il magazzino dei prodotti meccanici include i prodotti restituiti al magazzino dopo essere stati scollegati dai negozi dei commercianti; così come i prodotti che sono stati venduti e collegati ai negozi dei commercianti. Allo stesso tempo, è possibile spedire i prodotti \"non collegati\" ai tuoi agenti di livello inferiore.",
  "未綁定状态": "Stato non associato: robot che si trovano ancora in magazzino e non sono stati associati a nessun negozio commerciale.",
  "功能介绍": "Introduzione delle funzioni:",
  "冻结": "congelato",
  "取消冻结": "Annulla il congelamento",
  "未绑定状态描述": "Non vincolato: dal magazzino dell'azienda Purdue al magazzino dell'agente, lo stato in cui l'agente non ha venduto e vincolato al negozio.",
  "未激活状态描述": "Non attivato: lo stato in cui l'agente vende il robot e lo associa a un negozio fisico, ma il robot non è stato acceso e attivato.",
  "已激活状态描述": "Attivato: Lo stato in cui l'agente attiva il robot già associato al negozio per l'uso dopo l'accensione.",
  "已冻结状态描述": "Congelato: lo stato del robot dopo che l'agente lo ha congelato, in questa condizione il robot non potrà più essere utilizzato.",
  "换板待验证状态描述": "In attesa di verifica dopo la sostituzione della scheda madre: lo stato durante il processo di sostituzione quando la scheda madre del robot è danneggiata.",
  "还剩": "ancora rimasto",
  "个月": "mese",
  "系统操作": "Operazione del sistema",
  "租赁时长": "Durata del noleggio",
  "试用时长": "durata della prova",
  "试用截止时间": "Data di scadenza del periodo di prova",
  "门店安装时间": "Orario di installazione del negozio",
  "备件信息": "Informazioni sui componenti",
  "备件类型": "Tipo di componente",
  "导出全部": "Esporta tutto",
  "供应商": "fornitore",
  "型号": "modello",
  "上报时间": "Tempo di segnalazione",
  "电池": "batteria",
  "雷达": "radar",
  "相机": "macchina fotografica",
  "核心板": "Scheda madre",
  "屏幕": "schermo",
  "充电器": "Caricabatterie",
  "功能板": "Versione funzionale",
  "上位机": "Unità di controllo superiore"
}