export default {
  "exception.monitor": "Monitoraggio delle anomalie",
  "key.whitelist": "{key} lista bianca",
  "risk.control.settings": "Impostazioni di controllo del rischio",
  "robot.run.district": "Area di esercizio",
  "robot.report.time.latest": "Ultimo tempo di segnalazione",
  "robot.lock.confirm": "Dopo aver eseguito l'operazione di blocco, il robot non potrà essere utilizzato, né potrà essere scollegato o ricollegato a un altro negozio.",
  "robot.lock.remark": "Informazioni sul blocco del dispositivo",
  "robot.unlock.confirm": "Dopo aver eseguito l'operazione di sblocco, il robot rimuoverà l'avviso e tornerà a funzionare normalmente.",
  "robot.exception.view": "Visualizza i dettagli dell'eccezione",
  "robot.info": "Informazioni sul robot",
  "shop.info": "Informazioni sul punto vendita",
  "robot.category": "Tipi di robot",
  "robot.smuggling.warning": "Allarme di irregolarità, rischio di merce di contrabbando",
  "robot.run.location": "Posizione di esecuzione",
  "key.remove": "Rimuovere",
  "time.add": "Aggiungi orario",
  "use.instructions": "Istruzioni per l'uso",
  "confirm.remove": "Dopo aver eseguito l'operazione di rimozione, la macchina attiverà il meccanismo di controllo del rischio di \"prevenzione della fuga di merci\".",
  "device.add": "Aggiungi dispositivo",
  "use.instruction.reason": "Motivo per l'aggiunta della macchina alla lista bianca",
  "query.result": "Risultato della ricerca",
  "query.byMac": "Ricerca indirizzo MAC",
  "base.version.No": "Numero di versione di base",
  "key.auto.lock": "Blocco automatico {key}",
  "district.china.mainland.outside": "Hong Kong, Macao, Taiwan e estero",
  "district.china.mainland": "Continente cinese",
  "key.enable": "Attivare",
  "edit.risk.control.settings": "Modifica delle impostazioni di controllo del rischio",
  "robot.status.locked": "Dispositivo bloccato",
  "robot.status.unlock": "Già sbloccato",
  "robot.sn/pid": "Numero di serie (PID) dell'apparecchio",
  "key.status": "stato di {key}",
  "risk.control": "Controllo del rischio",
  "status.risk.control": "Stato di controllo del rischio",
  "status.robot": "Stato del robot",
  "status.abnormal.watning": "Allerta di Anomalia",
  "datatype.nomal": "Dati normali",
  "datatype.nomal.tip": "Inclusi: robot aggiunti alla lista bianca, robot sbloccati e robot che non hanno mai attivato il controllo anti-contrabbando.",
  "datatype.abnomal": "Dati anomali",
  "opr.area": "{key} area operativa",
  "goto.check": "Vai a controllare",
  "risk.control.notify": "Notifica di controllo del rischio",
  "risk.control.warntip": "I robot operano in aree non delegate, e ripetute attivazioni comporteranno il blocco del dispositivo.",
  "abnormal.waning.robots": "Dispositivo di avviso di anomalie",
  "etc.": "aspetta",
  "robot.lock.switch": "Interruttore di blocco",
  "robot.lock.auto": "Serratura automatica",
  "robot.lock.manual": "Blocco manuale",
  "abnormal.lock.robots": "Dispositivo di blocco per il controllo del rischio del vento",
  "robot.lock.tip": "È stata attivata la protezione contro la merce di contrabbando, al momento il dispositivo è bloccato. In caso di dubbi, contattare il personale del servizio Purdu.",
  "warning.send.email": "Casella di posta elettronica per avvisi di allerta eccezionali",
  "input.email.multiple": "Inserisci più indirizzi email separati da un a capo",
  "input.forExample": "Esempio:",
  "email.invalid": "Indirizzo email non conforme",
  "PuduBot": "Festa di Regali",
  "BellaBot": "Bella",
  "HolaBot": "Va bene",
  "Puductor": "Gioia di Eliminare",
  "Puductor2": "Gioia Pop 2",
  "KettyBot": "zucca (calabash)",
  "FlashBot": "Scatola del fulmine",
  "PuduCC1": "Fuori dal mondo",
  "SwiftBot": "Consegna Felice",
  "PuduBot2": "Festa di Consegna 2",
  "PuduSH1": "Leone e tigre"
}