export default {
  "productListIframe.无记录": "Nessun record",
  "productListIframe.厂测中": "In fase di test in fabbrica",
  "productListIframe.厂测过期": "Scadenza del test di fabbrica",
  "productListIframe.已入库": "Già in magazzino",
  "productListIframe.未绑定": "Non vincolato",
  "productListIframe.未激活": "Non attivato",
  "productListIframe.已激活": "Attivato",
  "productListIframe.已冻结": "Congelato",
  "productListIframe.换板待验证": "Cambio di pannello in attesa di verifica",
  "productListIframe.保内": "Riserva",
  "productListIframe.保外": "fuori garanzia",
  "productListIframe.产品名称": "Nome del prodotto",
  "productListIframe.所属门店": "Negozio di appartenenza",
  "productListIframe.所属代理": "Agenzia di appartenenza",
  "productListIframe.产品状态": "Stato del prodotto",
  "productListIframe.首次激活时间": "Data di attivazione iniziale",
  "productListIframe.最新安装时间": "Ultimo orario di installazione",
  "productListIframe.代理维保状态": "Stato di manutenzione del rappresentante",
  "productListIframe.终端维保状态": "Stato di manutenzione del terminale",
  "productListIframe.设备地址": "Indirizzo dispositivo",
  "productListIframe.关闭": "chiuso",
  "productListIframe.没有更多了": "Non c'è più.",
  "productListIframe.加载中": "Caricamento in corso",
  "productListIframe.请选择机器": "Si prega di selezionare la macchina",
  "productListIframe.搜索": "ricerca",
  "productListIframe.清除筛选": "Rimuovi filtro",
  "productListIframe.查看更多": "Guarda di più",
  "productListIframe.完成": "completato"
}