export default {
  "app.setting.pagestyle": "Impostazioni dello stile generale",
  "app.setting.pagestyle.dark": "Stile del menu a colori scuri",
  "app.setting.pagestyle.light": "Stile del menu a colori vivaci",
  "app.setting.content-width": "Area di contenuto larghezza",
  "app.setting.content-width.fixed": "Larghezza fissa",
  "app.setting.content-width.fluid": "flusso",
  "app.setting.themecolor": "Colore principale",
  "app.setting.themecolor.dust": "Crepuscolo",
  "app.setting.themecolor.volcano": "vulcano",
  "app.setting.themecolor.sunset": "Tramonto",
  "app.setting.themecolor.cyan": "Azzurro brillante",
  "app.setting.themecolor.green": "Aurora verde",
  "app.setting.themecolor.daybreak": "Azzurro alba (predefinito)",
  "app.setting.themecolor.geekblue": "Geek Blu",
  "app.setting.themecolor.purple": "salsa di soia",
  "app.setting.navigationmode": "Modalità di navigazione",
  "app.setting.sidemenu": "Layout del menu laterale",
  "app.setting.topmenu": "Layout del menu superiore",
  "app.setting.fixedheader": "Intestazione fissa",
  "app.setting.fixedsidebar": "Menu laterale fisso",
  "app.setting.fixedsidebar.hint": "Il layout del menu laterale può essere configurato",
  "app.setting.hideheader": "Nascondi l'intestazione durante lo scorrimento in basso",
  "app.setting.hideheader.hint": "Configurabile quando si fissa l'intestazione",
  "app.setting.othersettings": "Altre impostazioni",
  "app.setting.weakmode": "Modalità per daltonici",
  "app.setting.copy": "Impostazioni di copia",
  "app.setting.copyinfo": "Copia eseguita con successo, si prega di sostituire la configurazione predefinita in src/defaultSettings.js",
  "app.setting.production.hint": "La barra di configurazione è utilizzata solo per l'anteprima nell'ambiente di sviluppo e non verrà visualizzata nell'ambiente di produzione. Si prega di copiare e modificare manualmente il file di configurazione."
}