export default {
  "app.settings.menuMap.basic": "Impostazioni di base",
  "app.settings.menuMap.security": "Impostazioni di sicurezza",
  "app.settings.menuMap.binding": "Account collegato",
  "app.settings.menuMap.notification": "Notifica di nuovo messaggio",
  "app.settings.basic.avatar": "avatar",
  "app.settings.basic.change-avatar": "Cambia avatar",
  "app.settings.basic.email": "casella di posta elettronica",
  "app.settings.basic.email-message": "Inserisci il tuo indirizzo email!",
  "app.settings.basic.nickname": "soprannome",
  "app.settings.basic.nickname-message": "Inserisci il tuo soprannome!",
  "app.settings.basic.profile": "Profilo personale",
  "app.settings.basic.profile-message": "Inserisci una breve presentazione personale!",
  "app.settings.basic.profile-placeholder": "Profilo personale",
  "app.settings.basic.country": "Nazione/Area",
  "app.settings.basic.country-message": "Inserisci il tuo paese o regione!",
  "app.settings.basic.geographic": "Provincia o città di residenza",
  "app.settings.basic.geographic-message": "Inserisci la tua provincia e città!",
  "app.settings.basic.address": "Indirizzo stradale",
  "app.settings.basic.address-message": "Inserisci il tuo indirizzo stradale!",
  "app.settings.basic.phone": "Numero di contatto",
  "app.settings.basic.phone-message": "Inserisci il tuo numero di telefono!",
  "app.settings.basic.update": "Aggiorna le informazioni di base",
  "app.settings.security.strong": "forte",
  "app.settings.security.medium": "centro",
  "app.settings.security.weak": "debole",
  "app.settings.security.password": "password dell'account",
  "app.settings.security.password-description": "Forza della password attuale",
  "app.settings.security.phone": "telefono di sicurezza",
  "app.settings.security.phone-description": "Telefono già associato",
  "app.settings.security.question": "Domanda di sicurezza",
  "app.settings.security.question-description": "Non è stata impostata una domanda di sicurezza, la quale può proteggere efficacemente la sicurezza dell'account.",
  "app.settings.security.email": "E-mail di riserva",
  "app.settings.security.email-description": "E-mail già associata",
  "app.settings.security.mfa": "Dispositivo MFA",
  "app.settings.security.mfa-description": "Dispositivo MFA non associato, dopo l'associazione, è possibile effettuare una seconda conferma.",
  "app.settings.security.modify": "Modifica",
  "app.settings.security.set": "impostazioni",
  "app.settings.security.bind": "legare",
  "app.settings.binding.taobao": "Legare Taobao",
  "app.settings.binding.taobao-description": "Attualmente non è collegato alcun account Taobao.",
  "app.settings.binding.alipay": "Legare Alipay",
  "app.settings.binding.alipay-description": "Attualmente non è associato alcun account Alipay.",
  "app.settings.binding.dingding": "Legare DingTalk",
  "app.settings.binding.dingding-description": "Attualmente non è associato alcun account DingTalk.",
  "app.settings.binding.bind": "legare",
  "app.settings.notification.password": "password dell'account",
  "app.settings.notification.password-description": "Le notifiche dei messaggi di altri utenti saranno inviate tramite messaggio interno.",
  "app.settings.notification.messages": "Messaggio di sistema",
  "app.settings.notification.messages-description": "I messaggi di sistema verranno notificati tramite messaggi interni.",
  "app.settings.notification.todo": "Compiti da svolgere",
  "app.settings.notification.todo-description": "Le attività da svolgere saranno notificate tramite messaggio interno.",
  "app.settings.open": "aperto",
  "app.settings.close": "chiave",
  "robot.check.blacklist": "L'indirizzo MAC è stato aggiunto alla blacklist, si prega di contattare la società Purdue per la gestione."
}