export default {
  "language.select.label": "Seleziona la lingua",
  "voice.add": "Aggiungi voce",
  "voice.category": "Classificazione vocale",
  "voice.mp3": "audio vocale",
  "voice.mp3.del.confirm": "Eliminando questa voce, i pacchetti vocali personalizzati aggiunti successivamente non includeranno più la voce di questa scena.",
  "voice.language": "specie di lingua vocale",
  "voice.id.correct.tip": "Si prega di inserire il corretto VoiceID del robot, altrimenti non sarà possibile effettuare l'annuncio.",
  "voice.display.scene.desc": "Scenari di sintesi vocale",
  "voice.display.content": "Contenuto del testo del messaggio vocale",
  "voice.upload.limit": "Supporta il caricamento di file MP3 fino a un massimo di 1MB",
  "voice.pkg.desc": "Descrizione del pacchetto vocale",
  "voice.access": "Robot autorizzato",
  "voice.pkg.auth": "Pacchetto di autorizzazione vocale",
  "key.agent.name": "agente",
  "key.auth.add": "Aggiungere l'autorizzazione",
  "key.batch.replace": "Sostituzione in batch",
  "key.robot.category": "Tipi di robot",
  "key.robot.No": "robotica",
  "voice.all": "Tutta la voce",
  "voice.merge.submit": "Sintesi vocale completata",
  "voice.merge.submit.failed": "Aggiornamento del pacchetto vocale fallito",
  "voice.change.mp3": "Sostituire l'audio",
  "voice.validity.period.tip": "Si prega di selezionare la data di scadenza",
  "voice.authorized.mac.tip": "Autorizza questo pacchetto vocale per i seguenti robot {robot}.",
  "voice.authorized.store.tip": "Autorizza questo pacchetto vocale per il robot {robot} nei seguenti negozi.",
  "voice.authorized.agent.tip": "Autorizza questo pacchetto vocale a tutti i negozi sotto l'agente per il robot {robot}.",
  "voice.voiceid.notmatch": "Il nome del file non corrisponde a nessun VoiceID.",
  "voice.filesize.exceed": "La dimensione del file supera il limite consentito.",
  "voice.upload.warning1": "È necessario comprimere i file all'interno della cartella, la cartella non ha bisogno di essere compressa.",
  "voice.upload.warning2": "Il nome dell'audio deve essere l'ID vocale corrispondente al tipo di prodotto robotico.",
  "voice.upload.warning3": "Supporta fino a 200 file audio mp3 e non supera i 200MB.",
  "voice.upload.warning4": "Poiché il file è di grandi dimensioni, non è possibile uscire durante il processo di caricamento.",
  "not.your.robot": "Non sono un robot del tuo inventario.",
  "key.limit.import.count": "Limitato a {key} pezzi",
  "navBar.lang": "linguaggio"
}