export default {
  "open.platform.title": "PUDU 開放平台",
  "open.platform.desc": "普渡開放平台可以為機器人業務開發者提供開放的軟件和硬件服務。藉助普渡開放平台，開發人員能夠充分利用機器人的全部功能，將機器人與各個行業相結合，從零開始完成機器人業務開發落地，為項目創造無限可能。",
  "H-C.interaction": "人機交互",
  "navigation.control": "導航控制",
  "voice.play": "語音播報",
  "full.amount.data": "全量數據",
  "view.api.doc": "查看API開放文件",
  "know.detail": "了解詳情",
  "apply.sdk": "申請遠程控制SDK",
  "apply.agent": "申請代理",
  "apply.people": "申請人",
  "apply.email": "申請人郵箱",
  "apply.purpose": "申請目的",
  "device.id": "設備ID",
  "device.secret": "秘鑰",
  "app.secret": "應用秘鑰",
  "apply.time": "申請時間",
  "applicant.info": "申請人資訊",
  "receive.email": "接收資訊郵箱",
  "apply.app.info": "申請應用信息",
  "applicable.stores": "適用門店",
  "app.stores.tip": "選擇需要遠程控制的機器人所屬門店",
  "apply.functions": "申請功能",
  "apply.desc": "您正在申請「遠程控制開放SDK」，開放者在自研的平台中，可調用該SDK的開放能力，遠程呼叫門店下的機器人。",
  "api.doc.desc": "遠程控制開放SDK文檔",
  "api.sdk.download": "審核通過後，即可下載",
  "openplatform.email": "普渡開發者提問郵箱",
  "email.input.tip": "務必填寫正確，用於接收申請通過後的秘鑰和SDK資訊",
  "approved.tip": "編輯應用信息，將直接生效，無需重複審核",
  "regionId.diff.tip": "門店源地址不同",
  "voice.play.mgt": "語音播報管理",
  "voice.play.subtitle": "自定義配置不同場景的語音播報，引流、促銷、攬客，讓機器人成為更專業的營銷高手",
  "emoticon.interface.mgt": "表情介面管理",
  "emoticon.interface.subtitle": "個性化設置不同有趣、好玩的機器人表情，讓機器人更加吸引顧客",
  "open.platform.subtitle": "機器人全鏈路技術能力開放，助力開發者實現全行業場景應用",
  "emo.pack.name": "表情包名",
  "emo.pack.create": "創建定制表情包",
  "apply.scope": "適用範圍",
  "opr.steps": "操作步驟",
  "opr.steps.sub": "務必按照步驟執行，否則會設置失敗",
  "steps.1": "步驟1",
  "steps.1.desc": "下載機器人當前表情包文件",
  "steps.2": "步驟2",
  "steps.2.desc": "逐一用新表情檔案替換原有檔案",
  "steps.2.desc.ketty": "葫蘆包括2組表情：“double_eye”、“single_eye”，選擇替換其中一組表情，使用“新表情文件”去替換“animation”和“firstImage”文件夾中的一組表情",
  "steps.2.ps1": "1. 文件夾和文件的層級、命名和數量要嚴格保持不變",
  "steps.2.ps2": "2. 圖片像素為 1920*1200 pixel，格式為.png；表情格式為.mp4；整個文件夾不可超過50MB",
  "steps.2.ps2.ketty": "2. 首幀圖片分辨率1280*800，格式為.png，100KB以內；表情動畫格式為.mp4，分辨率1280*800，4MB以內",
  "steps.3": "步驟3",
  "steps.3.desc": "全選表情文件，壓縮為.zip文件包，進行上傳",
  "steps.3.desc.ps": "不可外層嵌套文件夾進行壓縮",
  "emo.info": "表情包資訊",
  "key.emo.use.tip": "此表情包只針對{key}機型有效",
  "emo.upload": "上傳表情包",
  "upload.del.confirm": "將永久刪除該文件，是否確認？",
  "scope.agent": "所有的機器人",
  "key.scope.agent": "所有的{key}機器人",
  "scope.store": "指定門店的所有機器人",
  "scope.robot": "指定機器人",
  "emo.upload.tip": "請上傳zip文件，總大小在50M以內",
  "emo.step.info.1": "按照emo文件夾逐步替換表情文件",
  "emo.step.info.2": "文件夾層級、文件夾和文件命名不可更改",
  "emo.step.info.3": "文件不可超過50M，圖片像素1920*1200 pixel，表情格式為MP4格式；",
  "emo.step.info.4": "表情文件喜怒哀樂左右耳等14個MP4 + 1張PNG佔位圖（無佔位圖會導致切換表情黑屏）",
  "imp.robots.step1": "下載模板",
  "imp.robots.step2": "將MAC填入模板",
  "not.in.stock": "不在庫存中",
  "key.not": "不是{key}",
  "del.emoji.tip": "刪除後，不影響機器人已使用的表情包",
  "store.list": "門店列表",
  "robot.list": "機器人列表",
  "name.repeat": "名稱重複",
  "record.repeat": "有重複項",
  "zip.content.abnormal": "未按要求壓縮表情包文件",
  "scop.tip1": "1、全部：{key}會推送到代理商下所有機器人。新綁定的機器人會自動獲取{key}。",
  "scop.tip2": "2、按門店：{key}只會推送到已選擇門店下的機器人，已選擇的門店新綁定機器人，會自動獲取{key}。",
  "scop.tip3": "3、按機器：{key}只會推送到已選擇的機器人。",
  "emoji.pkg": "表情包",
  "voice.pkg": "語音包",
  "key.voice.use.tip": "此語音包只針對{key}機型有效",
  "voice.del.tip": "刪除後，該場景下將不再播報語音內容",
  "batch.step1": "下載voiceID和語音播報場景對照Excel表",
  "batch.step2": "根據“voiceID和場景對照表”，逐一將定制語音mp3文件名更改為對應的voiceID",
  "batch.step2.ps1": "1) 務必確保每個語音文件命名是正確的voiceID，否則會上傳失敗",
  "batch.step3": "將所有的定製語音放入文件夾後，選擇文件夾進行批量上傳",
  "batch.step3.ps1": "1) 注意不要壓縮文件夾",
  "batch.step3.ps2": "2) 單次上傳最多300個音頻，每個文件不超過3MB",
  "batch.btn": "選擇上傳文件夾",
  "file.type.error": "文件類型錯誤",
  "count.limit": "文件數量超過{key}限制",
  "wrong.file.type": "錯誤的文件類型",
  "file.size.exceeds": "文件大小超過{key}限制",
  "voice.packing.tip": "請勿關閉頁面，語音包合成中...",
  "business.district.desc": "配置商圈裡的機器人，可配送多個商家的餐品"
}