export default {
  "component.tagSelect.expand": "展開",
  "component.tagSelect.collapse": "摺起",
  "component.tagSelect.all": "全部",
  "key.select.max": "最多選擇{key}個機器人",
  "trial.period.day": "試用週期/日",
  "lease.cycle.month": "租賃週期/月",
  "required.warn": "您有必填內容需要填寫",
  "first.imp.time": "首次導入時間",
  "validate.robot.key.warn": "請輸入完整的SN(PID)或者MAC",
  "change.to.complex.query": "切換到複雜查詢",
  "change.to.simple.query": "切換到簡單查詢",
  "openapi.docs": "API開發文檔",
  "customer.name": "商戶名稱",
  "key.template": "範本",
  "confirm.file.upload": "請確認文件是否已上傳完成",
  "upload.fail": "上傳失敗，請重試",
  "key.success": "成功",
  "key.fail": "失敗",
  "import.result": "導入結果",
  "incompatibility.versions": "新版本與舊版本不兼容，",
  "auto.jump.available": "將自動跳轉可用版本...",
  "import.maxcount.tip": "檢測到已超過{count}個MAC，系統只導入前{count}個MAC，其餘MAC請重新再次導入。"
}