export default {
  "log.boot": "開機自檢",
  "log.abnormal": "異常故障",
  "log.charge": "充電日誌",
  "log.battery": "電池健康狀態",
  "production.date": "產生日期",
  "boot.status": "狀態",
  "boot.undetected": "未檢測",
  "boot.normal": "正常",
  "boot.abnormal": "異常",
  "key.no": "編號",
  "log.production.time": "日誌生成時間",
  "log.push.time": "日誌上雲時間",
  "boot.description": "描述",
  "boot.check_module": "自檢模組狀態",
  "poweron.ratio": "儲存比例(%)",
  "robot.softVer": "軟體版本",
  "robot.hardVer": "韌體版本",
  "common.systemid": "作業系統版本",
  "common.battery": "當前電量",
  "check.abnormal": "存在異常",
  "check.normal": "無異常",
  "error.category": "故障類型",
  "error.detail": "故障詳情",
  "error.grade": "故障等級",
  "error.list": "故障清單",
  "error.ID": "故障ID",
  "filter.more": "更多篩選",
  "charge.count_battery": "充電電量",
  "charge.count_time": "充電時長",
  "soh.battery_sn": "電池SN",
  "soh.full": "電池容量 (mAh)",
  "soh.remaining": "剩餘容量 (mAh)",
  "soh.battery_voltage": "電池電壓 (mV)",
  "soh.soh": "電池健康指數",
  "soh.cycle": "循環次數",
  "soh.battery_type": "電池類型",
  "tip.soh": "該字段發生變化時才會上報日誌",
  "key.clip": "一鍵複製",
  "collapse": "摺起",
  "please.select": "請選擇",
  "please.input": "請輸入",
  "cycle.range.tip": "循環範圍沒有數據"
}