export default {
  "联系邮箱": "correo electrónico de contacto",
  "代理商等级": "Nivel de agente",
  "上级代理商": "Agente superior",
  "重置密码": "Restablecer contraseña",
  "新密码": "Nueva contraseña",
  "操作成功": "Operación exitosa",
  "操作失败": "Operación fallida",
  "共n条记录": "Total de {total} registros",
  "是否前往": "La cuenta se ha añadido con éxito, por favor diríjase al \"Centro de Clientes\" para completar la información básica del agente.",
  "未添加无法登录": "Consejos: Si no se añade la información básica del agente, la cuenta no podrá iniciar sesión en el sistema.",
  "立即前往": "Dirígete allí inmediatamente",
  "查看账号": "Ver información de la cuenta",
  "生成新密码": "Haz clic aquí para generar una nueva contraseña",
  "随机密码": "Contraseña aleatoria",
  "更换密码": "Cambiar contraseña",
  "复制密码": "Contraseña de copia",
  "已复制！": "¡Copiado!",
  "图片裁剪": "Recorte de imagen",
  "获取文件md5出错": "Obtener el md5 del archivo falló",
  "oss删除文件失败": "Eliminación de archivo fallida en OSS",
  "视频个数超出限额": "El número de vídeos supera el límite permitido.",
  "素材类型不正确": "El tipo de formato del material no es correcto.",
  "图片过大": "La imagen es demasiado grande.",
  "视频过大": "El video es demasiado grande.",
  "分辨率超出": "La resolución supera los {height}P",
  "账号不能包含空格": "La cuenta no puede contener espacios.",
  "账号已存在": "La cuenta ya existe",
  "请设置密码": "Por favor, establezca una contraseña.",
  "密码规则": "Letras mayúsculas y minúsculas, números, combinación de cualquier tres tipos de caracteres especiales.",
  "agent.store.info": "Solo se contabiliza la cantidad de tiendas expandidas por el agente actual, no incluye el número de tiendas de agentes subordinados.",
  "account.noOrg.warning": "La cuenta no ha añadido información del agente, por favor contacte a la persona que creó su cuenta para resolverlo.",
  "login.redirect": "Usted ingresará a la página de \"Plataforma de Gestión Comercial\" después de {keyProp} segundos.",
  "login.suc": "Inicio de sesión exitoso",
  "login.fail": "Inicio de sesión fallido",
  "enter.nowait": "No es necesario esperar, haz clic para entrar.",
  "agent.type": "Tipos de agentes comerciales",
  "请勿输入非法字符": "Por favor, no introduzca caracteres ilegales."
}