export default {
  "中国港澳台及海外地区": "China, Hong Kong, Macao, Taiwán y regiones de ultramar",
  "中国大陆地区": "Región continental de China",
  "代理商类型": "Tipos de agentes comerciales",
  "类型": "tipo",
  "请选择代理商类型": "Por favor, seleccione el tipo de agente.",
  "运营区域": "Área de Venta Disponible",
  "请选择可销售的区域": "Por favor, seleccione la región disponible para la venta.",
  "新增代理商": "Nuevos agentes comerciales",
  "一级代理商": "Agente de nivel uno",
  "二级代理商": "Agente de segundo nivel",
  "一级": "Primera categoría",
  "二级": "Segundo nivel",
  "代理账号": "Cuenta de agente",
  "公司所在地": "La ubicación de la empresa",
  "注册时间": "Fecha de registro",
  "注册地区": "Región de registro",
  "销售区域": "Área de ventas",
  "上级代理商名称": "Nombre del agente superior",
  "拓展门店数": "Expansión del número de tiendas",
  "激活绑定数": "Números de activación/Números de dispositivos vinculados",
  "前往文件中心": "Dirígete al \"Centro de Documentos\"",
  "知道了": "Entendido",
  "结束日期": "fecha de finalización",
  "开始日期": "Fecha de inicio",
  "公司所在地不完整": "La dirección de la empresa está incompleta.",
  "请输入纯数字": "Por favor, introduzca el número de teléfono en números puros."
}