export default {
  "open.platform.title": "Plataforma abierta PUDU",
  "open.platform.desc": "La plataforma abierta de Purdue puede proporcionar servicios de software y hardware abiertos para desarrolladores de negocios de robots. Con la ayuda de la plataforma abierta de Purdue, los desarrolladores pueden aprovechar al máximo todas las funciones del robot, combinar el robot con diversas industrias y completar el desarrollo del negocio del robot desde cero, creando posibilidades ilimitadas para el proyecto.",
  "H-C.interaction": "Interacción hombre-máquina",
  "navigation.control": "Control de navegación",
  "voice.play": "Reproducción de voz",
  "full.amount.data": "Datos completos",
  "view.api.doc": "Consultar el documento de API abierta",
  "know.detail": "Entender los detalles",
  "apply.sdk": "Solicitud de SDK de control remoto",
  "apply.agent": "Solicitud de representación",
  "apply.people": "Solicitante",
  "apply.email": "Correo electrónico del solicitante",
  "apply.purpose": "Propósito de la solicitud",
  "device.id": "ID del dispositivo",
  "device.secret": "Clave secreta",
  "app.secret": "Clave de aplicación",
  "apply.time": "Tiempo de solicitud",
  "applicant.info": "Información del solicitante",
  "receive.email": "Buzón de recepción de información",
  "apply.app.info": "Solicitud de información de la aplicación",
  "applicable.stores": "Tiendas aplicables",
  "app.stores.tip": "Selecciona la tienda a la que pertenece el robot que necesita control remoto.",
  "apply.functions": "Solicitud de función",
  "apply.desc": "Usted está solicitando el \"SDK abierto de control remoto\", el cual permite a los desarrolladores en su plataforma propia, invocar las capacidades abiertas de dicho SDK para llamar a distancia a los robots ubicados en las tiendas.",
  "api.doc.desc": "Kit de Desarrollo de Software (SDK) para Control Remoto Abierto",
  "api.sdk.download": "Una vez aprobada la revisión, se podrá descargar.",
  "openplatform.email": "Correo electrónico de preguntas para desarrolladores de Purdue",
  "email.input.tip": "Es imprescindible rellenar correctamente para recibir la clave secreta y la información del SDK tras la aprobación de la solicitud.",
  "approved.tip": "Editar la información de la aplicación se hará efectiva inmediatamente, sin necesidad de una nueva verificación.",
  "regionId.diff.tip": "La dirección de origen de la tienda es diferente.",
  "voice.play.mgt": "Gestión de reproducción de voz",
  "voice.play.subtitle": "Configuración personalizada de anuncios de voz para diferentes escenarios, como atraer clientes, promociones y captación de clientes, haciendo que el robot se convierta en un experto en marketing más profesional.",
  "emoticon.interface.mgt": "Interfaz de gestión de expresiones",
  "emoticon.interface.subtitle": "Configuraciones personalizadas de expresiones de robot divertidas e interesantes, que hacen que el robot sea más atractivo para los clientes.",
  "open.platform.subtitle": "La capacidad tecnológica integral de los robots se abre, ayudando a los desarrolladores a implementar aplicaciones en todos los escenarios industriales.",
  "emo.pack.name": "Nombre del paquete de emoticonos",
  "emo.pack.create": "Crear paquetes de emojis personalizados",
  "apply.scope": "Ámbito de aplicación",
  "opr.steps": "Pasos de operación",
  "opr.steps.sub": "Es imprescindible seguir los pasos al pie de la letra, de lo contrario, la configuración fallará.",
  "steps.1": "Paso 1",
  "steps.1.desc": "Descargar el archivo de paquete de emoticonos del robot actual.",
  "steps.2": "Paso 2",
  "steps.2.desc": "Reemplazar los archivos originales uno por uno con nuevos archivos de expresiones.",
  "steps.2.desc.ketty": "Las calabazas incluyen 2 grupos de emojis: \"double_eye\" y \"single_eye\". Elija reemplazar uno de los grupos de emojis, utilizando el \"archivo de emoji nuevo\" para reemplazar el grupo de emojis en las carpetas \"animación\" y \"primera imagen\".",
  "steps.2.ps1": "1. La jerarquía, el nombre y la cantidad de carpetas y archivos deben mantenerse estrictamente sin cambios.",
  "steps.2.ps2": "2. La resolución de la imagen es de 1920*1200 píxeles, el formato es .png; el formato del emoji es .mp4; el tamaño total de la carpeta no debe exceder los 50MB.",
  "steps.2.ps2.ketty": "2. La resolución de la primera imagen es de 1280*800, en formato .png, con un tamaño máximo de 100KB; el formato de la animación de emoticonos es .mp4, con una resolución de 1280*800 y un tamaño máximo de 4MB.",
  "steps.3": "Paso 3",
  "steps.3.desc": "Selecciona todos los archivos de emoticonos, comprímelos en un paquete de archivos .zip y súbelos.",
  "steps.3.desc.ps": "No se puede comprimir una carpeta que contenga otras carpetas anidadas.",
  "emo.info": "Paquete de emoticonos",
  "key.emo.use.tip": "Este paquete de emoticonos solo es válido para el modelo {key}.",
  "emo.upload": "Subir paquete de emoticonos",
  "upload.del.confirm": "¿Confirma que desea eliminar este archivo de forma permanente?",
  "scope.agent": "Todos los robots",
  "key.scope.agent": "todos los robots {key}",
  "scope.store": "Robots de todas las tiendas designadas",
  "scope.robot": "Robot designado",
  "emo.upload.tip": "Por favor, suba un archivo zip, con un tamaño total de hasta 50 MB.",
  "emo.step.info.1": "Siga los pasos del archivo emo para reemplazar gradualmente los archivos de emoticonos.",
  "emo.step.info.2": "La jerarquía de carpetas, nombres de carpetas y archivos no se pueden cambiar.",
  "emo.step.info.3": "El archivo no debe exceder los 50 MB, la resolución de la imagen debe ser de 1920*1200 píxeles, y el formato de los emojis debe ser MP4.",
  "emo.step.info.4": "Archivos de expresiones de emociones como alegría, enojo, tristeza, placer, oreja izquierda, oreja derecha y otros 14 MP4 + 1 PNG de imagen de marcador de posición (la ausencia de una imagen de marcador de posición puede causar una pantalla negra al cambiar las expresiones)",
  "imp.robots.step1": "Descargar plantilla",
  "imp.robots.step2": "Rellena la plantilla con la MAC.",
  "not.in.stock": "No disponible en inventario",
  "key.not": "No es {key}",
  "del.emoji.tip": "Al eliminarlo, no afecta al paquete de emoticonos que ya ha utilizado el robot.",
  "store.list": "Lista de tiendas",
  "robot.list": "Lista de robots",
  "name.repeat": "Nombre duplicado",
  "record.repeat": "Hay ítems repetidos",
  "zip.content.abnormal": "No se comprimió el archivo del paquete de emojis según lo requerido.",
  "scop.tip1": "1. Todo: {key} se enviará a todos los robots bajo el distribuidor. Los robots recién vinculados obtendrán automáticamente {key}.",
  "scop.tip2": "2. Según la tienda: {key} solo se enviará a los robots que estén bajo la tienda seleccionada, y los robots recién vinculados a la tienda seleccionada obtendrán automáticamente {key}.",
  "scop.tip3": "3. Según la máquina: {key} solo se enviará a los robots seleccionados.",
  "emoji.pkg": "Paquete de emoticonos",
  "voice.pkg": "Paquete de voz",
  "key.voice.use.tip": "Este paquete de voz solo es válido para el modelo {key}",
  "voice.del.tip": "Al eliminar, ya no se reproducirá contenido de voz en este escenario.",
  "batch.step1": "Descarga la tabla de Excel de comparación de voiceID y escenas de locución.",
  "batch.step2": "De acuerdo con la \"tabla de correspondencia de voiceID y escena\", cambie el nombre de los archivos mp3 de voz personalizados uno por uno al voiceID correspondiente.",
  "batch.step2.ps1": "1) Asegúrese de que cada archivo de voz esté correctamente nombrado con el voiceID, de lo contrario, la carga fallará.",
  "batch.step3": "Después de colocar todas las voces personalizadas en la carpeta, selecciona la carpeta para subirlas en masa.",
  "batch.step3.ps1": "1) Tenga cuidado de no comprimir la carpeta.",
  "batch.step3.ps2": "2) Se pueden subir hasta 300 archivos de audio a la vez, y cada archivo no debe superar los 3MB.",
  "batch.btn": "Seleccionar carpeta de carga",
  "file.type.error": "Tipo de archivo incorrecto",
  "count.limit": "La cantidad de archivos supera el límite de {key}",
  "wrong.file.type": "Tipo de archivo incorrecto",
  "file.size.exceeds": "El tamaño del archivo supera el límite de {key}",
  "voice.packing.tip": "Por favor, no cierre la página, la síntesis del paquete de voz está en proceso...",
  "business.district.desc": "Configurar robots en el distrito comercial para entregar comidas de múltiples comercios."
}