export default {
  "bd.account": "cuenta",
  "bd.username": "Nombre",
  "bd.role": "personaje",
  "bd.name": "Nombre del distrito comercial",
  "bd.numOfStores": "número de tiendas",
  "bd.createtime": "Fecha de creación",
  "bd.updatetime": "Hora de actualización",
  "bd.operation": "operación",
  "bd.check": "Verificar",
  "bd.edit": "editor",
  "bd.qrcode": "Descargar código QR",
  "bd.new": "Nueva incorporación",
  "bd.goback": "regresar",
  "bd.account.placeholder": "Por favor, introduzca su cuenta.",
  "bd.name.placeholder": "Por favor, ingrese el nombre de la zona comercial.",
  "bd.inquire": "Consulta",
  "bd.reset": "Restablecer",
  "bd.store.tip": "Por favor, seleccione la tienda.",
  "bd.store.placeholder": "Por favor, introduzcan sus nombres.",
  "bd.map.tip": "Por favor, seleccione el mapa.",
  "bd.store.order": "Número de serie",
  "bd.store.name": "Nombre de la tienda",
  "bd.store.label": "Seleccionar tienda",
  "bd.map.label": "Seleccionar mapa",
  "bd.map.name": "Nombre del mapa",
  "bd.map.uploadtype": "Tipo de carga",
  "bd.map.association": "Número de productos relacionados",
  "bd.map.version": "versión",
  "bd.map.using": "En uso",
  "bd.map.unused": "No utilizado",
  "bd.map.uploadtype.apk": "Carga de APK",
  "bd.map.uploadtype.platform": "Plataforma de carga",
  "bd.map.choose": "selección",
  "bd.store.industry": "industria",
  "bd.store.address": "Dirección de la tienda",
  "bd.store.normal": "Normal",
  "bd.store.logout": "Anulación",
  "bd.insiders.noOperatingAuthority": "El personal interno no tiene permiso de operación.",
  "bd.store.reminder": "Recordatorio amable: Solo se admiten tiendas en estado \"normal\"."
}