export default {
  "component.tagSelect.expand": "desplegar",
  "component.tagSelect.collapse": "Plegar",
  "component.tagSelect.all": "todo",
  "key.select.max": "Selecciona un máximo de {key} robots.",
  "trial.period.day": "Período de prueba/días",
  "lease.cycle.month": "Período de alquiler/mes",
  "required.warn": "Usted tiene contenido obligatorio que necesita completar.",
  "first.imp.time": "Fecha de primera importación",
  "validate.robot.key.warn": "Por favor, ingrese el SN (PID) completo o el MAC.",
  "change.to.complex.query": "Cambiar a consulta compleja",
  "change.to.simple.query": "Cambiar a consulta simple",
  "openapi.docs": "Documentación de desarrollo de API",
  "customer.name": "Nombre del comerciante",
  "key.template": "Plantilla",
  "confirm.file.upload": "Por favor, confirme si el archivo se ha subido completamente.",
  "upload.fail": "La carga ha fallado, por favor intente de nuevo.",
  "key.success": "éxito",
  "key.fail": "fracaso",
  "import.result": "Resultados de la importación",
  "incompatibility.versions": "La nueva versión no es compatible con la versión antigua.",
  "auto.jump.available": "Se redirigirá automáticamente a la versión disponible...",
  "import.maxcount.tip": "Se ha detectado que se han superado los {count} MAC, el sistema solo importará los primeros {count} MAC, por favor, importe el resto de los MAC nuevamente."
}