export default {
  "dc.total": "Total",
  "dc.yesterday": "Ayer",
  "dc.last7days": "En los últimos 7 días",
  "dc.last30days": "En los últimos 30 días",
  "dc.naturalDay": "día natural",
  "dc.natureWeek": "semana natural",
  "dc.naturalMonth": "mes natural",
  "dc.chainRatio": "mes con mes",
  "dc.cumulativeNumber": "Número acumulado",
  "dc.activeRate": "Tasa de actividad",
  "dc.robotOperationOverview": "Panorama general del funcionamiento de la máquina",
  "dc.workTime": "Duración del trabajo",
  "dc.runningMileage": "Kilometraje de funcionamiento",
  "dc.taskTimes": "Ejecutar tarea次",
  "dc.robotRunningPeakTrend": "Tendencia de pico en la operación de robots",
  "dc.monthOnMonth": "Período homólogo interanual",
  "dc.numberOfRobotRuns": "robots en funcionamiento",
  "dc.stages": "{num} dispositivos",
  "dc.robotOverview": "Visión general de la máquina",
  "dc.powerOnRobot": "Robot de encendido",
  "dc.bindTheRobot": "Vincular robot",
  "dc.activateRobot": "Activar robot",
  "dc.numberOfRobotsBound": "Número de máquinas vinculadas",
  "dc.numberOfActiveRobots": "Número de máquinas activadas",
  "dc.storeOverview": "Visión general de la tienda",
  "dc.numberOfActiveStores": "Número de tiendas activas",
  "dc.numberOfNewStores": "Nuevas tiendas abiertas",
  "dc.activeStore": "Tiendas activas",
  "dc.silentStore": "Tienda Silenciosa",
  "dc.activeRobotPoweredOn": "Robot activo al encender",
  "dc.downtime": "Duración de la suspensión",
  "dc.operatingHours": "Horas de funcionamiento",
  "dc.emptyActiveStore": "Actualmente no hay tiendas activas",
  "dc.emptySilentStore": "Tienda temporalmente sin silencio",
  "dc.export": "Exportar",
  "dc.addStore": "Nueva tienda",
  "dc.cumulativeStores": "Tiendas acumuladas",
  "dc.storeName": "Nombre de la tienda",
  "dc.storeNamePlaceholder": "Por favor, ingrese el nombre de la tienda.",
  "dc.query": "Consulta",
  "dc.activeRank": "Clasificación de Actividad",
  "dc.creationTime": "Fecha de creación",
  "dc.activeRobot": "Robot de encendido",
  "dc.runTime": "Duración de funcionamiento",
  "dc.key.robot": "robot",
  "dc.key.boottime": "Hora de encendido",
  "dc.key.starttime": "Hora de inicio de funcionamiento",
  "dc.task.number": "Número de tareas",
  "dc.robots.all": "Todos los robots",
  "dc.robot.select": "Por favor, elija un robot.",
  "dc.tab.delivery": "Datos de envío",
  "dc.tab.cruise": "Datos de crucero",
  "dc.tab.greeter": "Datos de liderazgo",
  "dc.tab.interaction": "Datos de interacción",
  "dc.tab.solicit": "Datos de captación de clientes",
  "dc.tab.grid": "Datos de la celda",
  "dc.tab.ad": "Datos de publicidad",
  "dc.tab.recovery": "Datos de contraoferta",
  "dc.mileage": "Kilometraje de funcionamiento",
  "dc.runtime": "Duración de funcionamiento",
  "dc.interactiveVisits": "Interacciones de usuario",
  "dc.interactionTime": "Duración de la interacción",
  "dc.greetings": "Saludos",
  "dc.reached": "Alcance de personas",
  "dc.attract": "Atraer visitantes",
  "dc.voiceInteractions": "Número de interacciones de voz",
  "dc.voiceinteractionTime": "Duración de la interacción por voz",
  "dc.takeMeInCount": "\"Cuadrícula de estilo 'Llévame a la tienda'\"",
  "dc.featuredItemCount": "\"Productos destacados\" en cuadrícula",
  "dc.favorablePromotionsCount": "\"Actividades Promocionales\" de cuadrícula",
  "dc.guideToMenuCount": "\"Cuadrícula de asignación de asientos\"",
  "dc.posterCount": "\"Cuadrícula de estilo póster\"",
  "dc.usherCount": "\"Cuadrícula de guía\"",
  "dc.danceCount": "\"Cuadrícula de categoría de baile\"",
  "dc.videoPosterCount": "\"Póster de vídeo\" tipo cuadrícula",
  "dc.smallScreenExposureTime": "Duración de reproducción en pantalla pequeña",
  "dc.smallScreenExposures": "Número de reproducciones en pantalla pequeña",
  "dc.bigScreenExposureTime": "Duración de reproducción en pantalla grande",
  "dc.bigScreenExposures": "Número de reproducciones en pantalla grande",
  "dc.deliveryTables": "Número de mesas entregadas",
  "dc.deliveryPlate": "Número de platos entregados",
  "dc.numberOfTieLessons": "Número de veces que se ha llevado a los clientes a sus mesas",
  "dc.numberOfCleanTables": "Mesas limpias",
  "tip.export.nodata": "No hay datos disponibles para exportar",
  "dc.robotOperationOverview.toolTip": "El funcionamiento general del robot",
  "dc.robotOperationOverview.toolTip-1": "1. Horas de trabajo (h): En el rango de fechas, el número total de horas de funcionamiento acumuladas de todos los robots vinculados a las tiendas expandidas por el agente.",
  "dc.robotOperationOverview.toolTip-2": "1. Horas de trabajo (h): Durante el rango de fechas, el total de horas acumuladas de funcionamiento de los robots vinculados por las tiendas expandidas por el agente.",
  "dc.robotOperationOverview.toolTip-3": "3. Número de tareas ejecutadas: En el rango de fechas, el número acumulado de tareas ejecutadas por todos los robots vinculados a las tiendas desarrolladas por el agente.",
  "dc.robotRunningPeakTrend.toolTip": "Tendencia de pico en la operación de robots",
  "dc.robotRunningPeakTrend.toolTip-1": "1. Día natural: Se puede consultar el número de robots de diferentes tipos que están operando durante cualquier período de 24 horas de cualquier día.",
  "dc.robotRunningPeakTrend.toolTip-2": "2. Semana natural: Se puede consultar cualquier semana, el número de unidades de robots de diferentes tipos que se han encendido y operado cada día.",
  "dc.robotRunningPeakTrend.toolTip-3": "3. Mes natural: Se puede consultar cualquier mes, el número de unidades de robots de diferentes tipos que se han encendido y operado cada día.",
  "dc.robotOverview.toolTip": "Activación y estado activo de robots",
  "dc.robotOverview.toolTip-1": "1. Robots de encendido: Número acumulado de encendidos de todos los robots vinculados a las tiendas expandidas por los agentes dentro del rango de fechas.",
  "dc.robotOverview.toolTip-2": "2. Número acumulado: la cantidad total de robots vinculados desde la primera vez que el agente vinculó un robot a la tienda hasta la fecha límite de selección.",
  "dc.robotOverview.toolTip-3": "3. Tasa de actividad = En el rango de fechas, (Número de robots activos ÷ Número acumulado) * 100%.",
  "dc.robotOverview.toolTip-4": "4. Vinculación de robots: Número acumulado de robots vinculados a la tienda por el agente dentro del rango de fechas.",
  "dc.robotOverview.toolTip-5": "5. Activación de robots: Número acumulado de robots ya activados vinculados a las tiendas por los agentes dentro del rango de fechas.",
  "dc.storeOverview.toolTip": "Expansión de tiendas activas y situación de nuevas incorporaciones",
  "dc.storeOverview.toolTip-1": "1. Número de tiendas activas: en el rango de fechas, se cuenta como una tienda activa aquella tienda expandida por el agente donde hay un robot en funcionamiento.",
  "dc.storeOverview.toolTip-2": "2. Número acumulado: desde la fecha en que el agente se vincula por primera vez con la tienda, hasta la fecha límite de selección, la cantidad acumulada de tiendas.",
  "dc.storeOverview.toolTip-3": "3. Tasa de actividad = En el rango de fechas, (Número de tiendas activas ÷ Número acumulado) * 100%.",
  "dc.storeOverview.toolTip-4": "4. Número de nuevas tiendas: en el rango de fechas, la cantidad total de tiendas nuevas añadidas.",
  "dc.storeOverview.toolTip-5": "5. Top 10 de tiendas activas: En el rango de fechas, entre las tiendas desarrolladas por los agentes, aquellas con una mayor tasa de uso de robots y un tiempo de funcionamiento más prolongado, tendrán una clasificación más alta en la lista de tiendas activas.",
  "dc.storeOverview.toolTip-6": "6. Top 10 de tiendas en silencio: En el rango de fechas, entre las tiendas desarrolladas por los agentes, aquellas en las que la actividad del robot se detiene y la actividad es cero, se consideran una tienda en silencio. Cuantos más robots estén desactivados y más tiempo permanezcan en silencio, más alta será la posición en el ranking de silencio.",
  "dc.activeStore.toolTip": "Dentro del rango de fechas, las tiendas desarrolladas por el agente en las que hay robots en funcionamiento, se contarán como 1 tienda activa.",
  "dc.silentStore.toolTip": "Todas las máquinas vinculadas en la tienda no se han encendido dentro del rango de fechas, lo que se cuenta como una tienda inactiva.",
  "dc.addStore.toolTip": "Cantidad acumulada de nuevas tiendas añadidas dentro del rango de fechas.",
  "dc.cumulativeStores.toolTip": "Desde la fecha de la primera vinculación de la tienda por parte del agente, hasta la fecha límite de selección, el número acumulado de tiendas.",
  "robot.status.bind.tip": "1. Ya desvinculado: el robot actualmente está vinculado a otra tienda, estos datos corresponden al historial de la tienda filtrado por la fecha seleccionada.",
  "robot.status.unbind.tip": "2. Ya vinculado: el robot está actualmente vinculado a esa tienda, y los datos corresponden a los datos de funcionamiento de la tienda para las fechas filtradas.",
  "cruise.tip.run.mileage": "En el rango de fechas, la distancia total recorrida en patrullaje por todos los robots vinculados bajo la tienda extendida por el agente.",
  "cruise.tip.run.duration": "En el rango de fechas, la duración total del tiempo de patrullaje de todos los robots vinculados bajo la tienda expandida por el agente.",
  "cruise.tip.interaction.times": "Durante el rango de fechas, el número total de interacciones de todos los robots vinculados bajo la tienda expandida por el agente.",
  "cruise.tip.interaction.duration": "Dentro del rango de fechas, la duración total de la interacción de todos los robots vinculados bajo la tienda expandida por el agente.",
  "delivery.tip.run.mileage": "Dentro del rango de fechas, la distancia total recorrida en entregas de todos los robots vinculados a la tienda extendida por el agente.",
  "delivery.tip.run.duration": "Dentro del rango de fechas, la duración total de funcionamiento de la entrega de todos los robots vinculados bajo la tienda expandida por el agente.",
  "delivery.tip.task.num": "Dentro del rango de fechas, el número total acumulado de tareas ejecutadas por todos los robots vinculados a la tienda.",
  "delivery.tip.delivery.tables": "Dentro del rango de fechas, el agente expande el número de mesas de entrega de comida para todos los robots vinculados bajo la tienda.",
  "delivery.tip.delivery.plates": "Durante el rango de fechas, el número de platos de entrega de todos los robots vinculados bajo la tienda extendida por el agente.",
  "greeter.tip.run.mileage": "En el rango de fechas, la distancia total recorrida por todos los robots vinculados bajo la expansión de la tienda por el agente.",
  "greeter.tip.run.duration": "Dentro del rango de fechas, la duración total de funcionamiento de los robots asignados en todas las tiendas expandidas por el agente.",
  "greeter.tip.task.times": "Dentro del rango de fechas, el número de veces que se asignan tareas de liderazgo de posición para todos los robots vinculados bajo la tienda expandida por el agente.",
  "interaction.tip.all.times": "Durante el rango de fechas, el número de interacciones humano-máquina (tacto, interacción por voz) generadas por todos los robots vinculados bajo la tienda expandida por el agente.",
  "interaction.tip.voice.times": "Durante el rango de fechas, el número de interacciones de voz de todos los robots vinculados bajo la tienda expandida por el agente.",
  "interaction.tip.duration": "En el rango de fechas, la duración acumulada de la interacción por voz de todos los robots vinculados bajo la tienda extendida por el agente.",
  "solicit.tip.duration": "Dentro del rango de fechas, la duración total de operación de atracción de clientes de todos los robots vinculados bajo la tienda expandida por el agente.",
  "solicit.tip.hello.times": "Dentro del rango de fechas, el número de veces que los robots vinculados bajo la tienda expandida por el agente saludan.",
  "solicit.tip.reached.times": "Durante el rango de fechas, el número de veces que los usuarios han interactuado con todos los robots vinculados bajo la tienda extendida por el agente.",
  "solicit.tip.attach.times": "Dentro del rango de fechas, el agente expande todas las máquinas vinculadas en la tienda para contactar a los usuarios, y el número de personas que se detienen y permanecen.",
  "solicit.tip.interation.times": "Durante el rango de fechas, la cantidad de veces que todos los robots vinculados a la tienda extendida por el agente son despertados por los usuarios.",
  "grid.click.times": "En el rango de fechas, la cantidad de veces que se ha hecho clic en esta función entre todos los robots vinculados bajo la tienda extendida por el agente.",
  "ad.tiny.play.duration": "Durante el rango de fechas, la duración de reproducción de anuncios en pantallas pequeñas en todos los robots vinculados bajo la tienda expandida por el agente.",
  "ad.tiny.play.times": "Durante el rango de fechas, el número de veces que se han reproducido anuncios en pantallas pequeñas en todos los robots vinculados bajo la tienda extendida por el agente.",
  "ad.large.play.duration": "Durante el rango de fechas, la duración de la reproducción de anuncios en pantalla grande en todos los robots vinculados bajo la tienda ampliada por el agente.",
  "ad.large.play.times": "Durante el rango de fechas, el número de veces que se reprodujeron anuncios en pantallas grandes en todos los robots vinculados bajo la tienda expandida por el agente.",
  "recycle.tip.mileage": "Dentro del rango de fechas, la distancia total recorrida por la ejecución de la oferta de retorno de todos los robots vinculados bajo la tienda expandida por el agente.",
  "recycle.tip.duration": "En el rango de fechas, la duración total de funcionamiento de la oferta de retorno de todos los robots vinculados bajo la tienda extendida por el agente.",
  "recycle.tip.tables": "Dentro del rango de fechas, el número de veces que las mesas son limpiadas por los robots vinculados en todas las tiendas expandidas por el agente.",
  "by.key": "Pulsa {tecla}",
  "by.store": "Según la tienda",
  "by.robot": "según la máquina",
  "by.day": "por día",
  "by.hour": "por hora",
  "export.config": "Exportar configuración",
  "timeby.config.label": "Reglas de configuración para la exportación de datos por intervalos de tiempo",
  "robot.sn_mac": "Robot SN/MAC",
  "dc.clean.area.total": "Área total de limpieza (m²)",
  "dc.clean.area.total.tip": "Durante el período de tiempo establecido, el área total acumulada de limpieza de todos los robots vinculados a las tiendas desarrolladas por el agente.",
  "dc.clean.time.total": "Duración total de la limpieza (h)",
  "dc.clean.time.total.tip": "Rango de fechas, la duración total acumulada de limpieza de todos los robots vinculados en las tiendas expandidas por el agente.",
  "dc.clean.task.number": "Tareas de limpieza",
  "dc.clean.task.number.tip": "Rango de fechas, número acumulado de tareas de limpieza realizadas por todos los robots vinculados a las tiendas expandidas por el agente.",
  "dc.power.consumption": "Situación de consumo de energía (kw*h)",
  "dc.power.consumption.tip": "Rango de fechas, consumo acumulado de electricidad de todos los robots vinculados en las tiendas expandidas por el agente.",
  "dc.water.consumption": "Cantidad de agua consumida (ml)",
  "dc.water.consumption.tip": "Durante el período de tiempo, el volumen total de agua consumida por todos los robots vinculados a las tiendas desarrolladas por el agente.",
  "dc.tab.all": "Todos los modos",
  "dc.tab.scrubbing": "Modo de lavado de suelos",
  "dc.tab.sweeping": "Modo de barrido",
  "dc.sweep.vacuuming": "Aspiración de alfombras",
  "dc.sweep.dustpush": "Empujador de polvo silencioso",
  "dc.delivery": "Entrega",
  "dc.clean": "Limpieza",
  "dc.time": "tiempo",
  "dc.基本数据": "Datos básicos",
  "dc.清洁任务分布": "Tareas de limpieza distribuidas",
  "dc.清洁任务分布描述": "Dentro del rango de fechas, la suma del número de tareas ejecutadas por todos los robots vinculados a la tienda en cada hora del día natural. (Ejemplo: si se selecciona la fecha del 1 de enero al 2 de enero, y se ejecutan tareas de 1:00 a 2:00 el 1 de enero y tareas a la 1:00 el 2 de enero, entonces la distribución de tareas contabilizará 2 tareas a la 1:00 y 1 tarea a las 2:00).",
  "dc.robot.delivery.tip": "Esta máquina no es de tipo distribución.",
  "dc.robot.clean.tip": "Esta máquina no es de tipo limpieza.",
  "dc.store.unknow": "Lo siento, no se encontró esa tienda.",
  "dc.mileage.tip": "La distancia recorrida solo incluye los datos de funcionamiento del robot de reparto y no incluye los datos de funcionamiento del robot de limpieza.",
  "input.name.search": "Por favor, ingrese {key} para buscar"
}