export default {
  "log.boot": "Autoverificación al encender",
  "log.abnormal": "Avería anormal",
  "log.charge": "Registro de carga",
  "log.battery": "Estado de salud de la batería",
  "production.date": "Fecha de creación",
  "boot.status": "estado",
  "boot.undetected": "No detectado",
  "boot.normal": "Normal",
  "boot.abnormal": "anormal",
  "key.no": "Número de serie",
  "log.production.time": "Hora de generación del registro",
  "log.push.time": "Registro de tiempo en la nube",
  "boot.description": "descripción",
  "boot.check_module": "Estado del módulo de autodiagnóstico",
  "poweron.ratio": "Porcentaje de almacenamiento (%)",
  "robot.softVer": "versión del software",
  "robot.hardVer": "Versión del firmware",
  "common.systemid": "Versión del sistema operativo",
  "common.battery": "Nivel actual de batería",
  "check.abnormal": "Existe una anomalía",
  "check.normal": "Sin anomalías",
  "error.category": "Tipo de avería",
  "error.detail": "Detalles de la avería",
  "error.grade": "Nivel de avería",
  "error.list": "Lista de fallos",
  "error.ID": "ID de avería",
  "filter.more": "Más filtros",
  "charge.count_battery": "Carga de la batería",
  "charge.count_time": "Duración de la carga",
  "soh.battery_sn": "Número de serie de la batería",
  "soh.full": "Capacidad de la batería (mAh)",
  "soh.remaining": "Capacidad restante (mAh)",
  "soh.battery_voltage": "Voltaje de la batería (mV)",
  "soh.soh": "Índice de salud de la batería",
  "soh.cycle": "Número de ciclos",
  "soh.battery_type": "Tipo de batería",
  "tip.soh": "El registro se reportará solo cuando este campo cambie.",
  "key.clip": "Copia con un clic",
  "collapse": "Plegar",
  "please.select": "Por favor, elija",
  "please.input": "Por favor, introduzca.",
  "cycle.range.tip": "El rango de ciclo no tiene datos."
}