export default {
  "menu.dataCenter": "Centro de datos",
  "menu.dataCenter.dashBoard": "Tablero de instrumentos",
  "menu.dataCenter.operationAnalysis": "Análisis de operaciones",
  "menu.dataCenter.operationAnalysis.aStoreOperations": "Clasificación de Operaciones de Tiendas",
  "menu.dataCenter.operationAnalysis.bStoreProduct": "Ranking de Operaciones de Producto",
  "menu.dataCenter.operationAnalysis.cAtiveProduct": "Análisis de Productos Activos",
  "menu.dataCenter.operationAnalysis.sProductRoom": "Estadísticas de tareas de entrega de productos",
  "menu.dataCenter.operationAnalysis.eProductBackPlate": "Estadísticas de tareas de contraoferta de productos",
  "menu.dataCenter.operationAnalysis.fProductDisinfect": "Estadísticas de la tarea de desinfección del producto",
  "menu.dataCenter.operationAnalysis.gProductRunning": "Resumen de operaciones del producto",
  "menu.dataCenter.operationAnalysis.hProductDaily": "Datos diarios promedio del producto",
  "menu.dataCenter.operationAnalysis.iShopOperation": "Estadísticas de operación por horario de la tienda",
  "menu.dataCenter.operationAnalysis.jProductGrameTime": "Estadísticas de operación del producto por período",
  "menu.dataCenter.operationAnalysis.kShopEverydayOperation": "Estadísticas diarias de operación de la tienda",
  "menu.dataCenter.operationAnalysis.LShopSevenOperation": "Estadísticas de operación promedio de los últimos siete días de la tienda",
  "menu.dataCenter.operationAnalysis.mProductEverydayOperation": "Estadísticas diarias de operación del producto",
  "menu.dataCenter.operationAnalysis.nProductSevenOperation": "Estadísticas de operación de datos de los siete productos",
  "menu.dataCenter.operationAnalysis.VRobotTaskAnalysis": "Análisis de tareas de robots",
  "menu.reportLog": "Informe de registro",
  "menu.reportLog.foodDelivery": "Tarea de entrega de comida",
  "menu.reportLog.recycleDish": "Tarea de contraoferta",
  "menu.reportLog.disInfect": "Tarea de desinfección",
  "menu.reportLog.flashDelivery": "Tarea de entrega de objetos en la habitación",
  "menu.reportLog.powerOn": "Autoverificación al encender",
  "menu.reportLog.charge": "Registro de carga",
  "menu.reportLog.failure": "Avería anormal",
  "menu.reportLog.upgrade": "Informe de actualización",
  "menu.reportLog.batteryHealth": "Estado de salud de la batería",
  "menu.reportLog.AbnormalIPAddr": "Registro de direcciones IP anómalas",
  "menu.reportLog.about2fall_report": "Diario de prevención de caídas",
  "menu.valueAdded": "Servicios de valor agregado",
  "menu.valueAdded.custom": "Voz personalizada V1.1",
  "menu.valueAdded.customV1": "Voz personalizada V1.0",
  "menu.valueAdded.software": "Paquete de funciones de software",
  "menu.valueAdded.tts": "Respuestas de TTS",
  "menu.valueAdded.sip": "Configuración del servicio de telefonía SIP",
  "menu.account": "Gestión de cuentas",
  "menu.account.accountConfig": "Configuración de la cuenta",
  "menu.systemManage.AccountOperationHistory": "Historial de operaciones",
  "menu.AccountOperationHistory": "Historial de operaciones",
  "menu.systemManage": "Administración del sistema",
  "menu.systemManage.dictionaryManagement": "Gestión de diccionario",
  "menu.systemManage.messageNotification": "Notificación de mensaje",
  "menu.openPlatform": "Plataforma abierta",
  "menu.openPlatform.applicationCenter": "Centro de Solicitud",
  "menu.openPlatform.developDoc": "Documentación de desarrollo",
  "menu.returnManage": "Devolución de gestión",
  "menu.returnManage.record": "Registro de devolución",
  "menu.returnManage.useReturn": "Uso de devolución",
  "menu.customerCenter": "Centro de Atención al Cliente",
  "menu.customerCenter.storeManagement": "Gestión de tiendas",
  "menu.customerCenter.storeDetail": "Detalles de la tienda",
  "menu.customerCenter.bindRobots": "Vincular robot",
  "menu.customerCenter.bindARobot": "Añadir robot",
  "menu.customerCenter.storeRobotManagement": "Máquina de la tienda",
  "menu.customerCenter.activeCodeManagement": "Código de activación",
  "menu.customerCenter.financialInstitution": "Institución financiera",
  "menu.customerCenter.financialDetail": "Detalles de la institución financiera",
  "menu.customerCenter.agent": "Gestión de agentes",
  "menu.customerCenter.agentDetail": "Detalles del agente",
  "menu.productCenter": "Centro de productos",
  "menu.productCenter.productArchives": "Archivo de Producto",
  "menu.fileCenter": "Centro de Documentos",
  "menu.fileCenter.mapFile": "Archivo de mapa",
  "menu.fileCenter.formFile": "Documento de Acta de Recepción",
  "menu.fileCenter.downloadFile": "Descarga de archivos",
  "menu.equipmentCenter": "Centro de productos",
  "menu.equipmentCenter.productArchives": "Archivo de Producto",
  "menu.equipmentCenter.productLibrary": "Biblioteca de productos de maquinaria",
  "menu.equipmentCenter.outboundProducts": "Productos enviados al agente subordinado",
  "menu.equipmentCenter.viewProductInfo": "Ver información del producto",
  "menu.equipmentCenter.productEdit": "Información del editor",
  "menu.equipmentCenter.installedProduct": "Producto instalado",
  "menu.equipmentCenter.installedProducts": "Producto instalado",
  "menu.equipmentCenter.flowCard": "Producto de tarjeta de datos vinculada",
  "menu.equipmentCenter.productDetail": "Detalles del producto",
  "menu.equipmentCenter.productChangeRecord": "Registro de cambios del producto",
  "menu.equipmentCenter.product-change-records": "Registro de Cambio de Equipo",
  "menu.equipmentCenter.flowCardChangeRecord": "Registro de cambios de la tarjeta de datos",
  "menu.equipmentCenter.assignedProduct": "Productos de operaciones y mantenimiento asignados",
  "menu.equipmentCenter.unallocatedProduct": "Productos de operaciones y mantenimiento no asignados",
  "menu.equipmentCenter.antiSmuggling": "Control de riesgo de fuga de mercancías",
  "menu.equipmentCenter.accessories": "Gestión de accesorios",
  "menu.welcome": "Bienvenido",
  "menu.more-blocks": "Más bloques",
  "menu.home": "Página principal",
  "menu.admin": "Página de gestión",
  "menu.admin.sub-page": "Página de gestión de segundo nivel",
  "menu.login": "Iniciar sesión",
  "menu.register": "Registro",
  "menu.register.result": "Resultado del registro",
  "menu.dashboard.analysis": "Página de análisis",
  "menu.dashboard.monitor": "Página de monitoreo",
  "menu.dashboard.workplace": "Mesa de trabajo",
  "menu.exception.403": "403",
  "menu.exception.404": "404",
  "menu.exception.500": "quinientos",
  "menu.form": "Página de formulario",
  "menu.form.basic-form": "Formulario básico",
  "menu.form.step-form": "Formulario paso a paso",
  "menu.form.step-form.info": "Formulario paso a paso (información de transferencia)",
  "menu.form.step-form.confirm": "Formulario paso a paso (confirmación de información de transferencia)",
  "menu.form.step-form.result": "Formulario paso a paso (completado)",
  "menu.form.advanced-form": "Formulario avanzado",
  "menu.list": "Página de lista",
  "menu.list.table-list": "Formulario de consulta",
  "menu.list.basic-list": "Lista Estándar",
  "menu.list.card-list": "Lista de tarjetas",
  "menu.list.search-list": "Lista de búsqueda",
  "menu.list.search-list.articles": "Lista de búsqueda (artículos)",
  "menu.list.search-list.projects": "Lista de búsqueda (proyectos)",
  "menu.list.search-list.applications": "Lista de búsqueda (aplicaciones)",
  "menu.profile": "Página de detalles",
  "menu.profile.basic": "Página de detalles básicos",
  "menu.profile.advanced": "Página de detalles avanzada",
  "menu.result": "Página de resultados",
  "menu.result.success": "Página de éxito",
  "menu.result.fail": "Página de error",
  "menu.exception": "Página anormal",
  "menu.exception.not-permission": "403",
  "menu.exception.not-find": "404",
  "menu.exception.server-error": "quinientos",
  "menu.exception.trigger": "Disparar error",
  "menu.account.center": "Centro personal",
  "menu.account.settings": "Configuración personal",
  "menu.account.trigger": "Se ha producido un error.",
  "menu.account.logout": "Cerrar sesión",
  "menu.editor": "Editor gráfico",
  "menu.editor.flow": "Editor de procesos",
  "menu.editor.mind": "Editor de mapas mentales",
  "menu.editor.koni": "Editor de topología",
  "menu.test": "prueba",
  "menu.dataCenter.operationAnalysis.oFoodDelivery": "Servicio de entrega de productos Estadísticas de datos de mesas de comedor",
  "menu.dataCenter.operationAnalysis.pReturnPlate": "Servicio de respuesta de productos, estadísticas de datos de mesas de comedor",
  "menu.dataCenter.operationAnalysis.RCruiseMode": "Modo de crucero de producto estadísticas de datos",
  "menu.dataCenter.operationAnalysis.TSolicitCustomersMode": "Estadísticas de datos del modelo de atracción de clientes del producto",
  "menu.dataCenter.operationAnalysis.SLeadmode": "Modo de liderazgo de producto en estadísticas de datos",
  "menu.dataCenter.operationAnalysis.UAdPlayMode": "Estadísticas de reproducción de anuncios",
  "menu.customerCenter.rcagent": "Agente asociado",
  "menu.customerCenter.equipment": "Equipo de propiedad",
  "menu.customerCenter.financialInfo": "Detalles de la institución de financiamiento",
  "menu.reportLog.SIMCardLog": "Tarjeta SIM de datos",
  "menu.SIMCardMgr": "Gestión de tarjetas SIM de datos",
  "menu.SIMCardMgr.ActivedCardMgr": "Tarjeta de datos activada",
  "menu.SIMCardMgr.ExpiredCardMgr": "Advertencia de vencimiento de la tarjeta de datos",
  "menu.BusinessDistrictMgr": "Gestión de distritos comerciales",
  "menu.BusinessDistrictMgr.Add": "Nueva incorporación",
  "menu.BusinessDistrictMgr.Edit": "editor",
  "menu.BusinessDistrictMgr.Detail": "Verificar",
  "menu.dataCenter.dataOverview": "Vista general de datos",
  "menu.dataCenter.storeAnalysis": "Análisis de la tienda",
  "menu.dataCenter.robotOperationAnalysis": "Análisis de funcionamiento de robots",
  "menu.dataCenter.robotTaskAnalysis": "Datos de entrega de robots",
  "menu.dataCenter.cleanRobotData": "Robots limpian datos",
  "menu.app-center": "Centro de Aplicaciones",
  "menu.app-center.emoticon-mgmt": "Gestión de expresiones de robots",
  "menu.app-center.emoticon-add": "Crear paquete de emoticonos",
  "menu.app-center.emoticon-edit": "Editar paquete de emoticonos",
  "menu.app-center.voice-mgmt": "Gestión de voz de robots",
  "menu.app-center.voice-add": "Crear paquete de voz personalizado",
  "menu.app-center.voice-edit": "Edición de paquetes de voz personalizados",
  "menu.app-center.voice-auth": "Paquete de voz autorizado",
  "menu.app-center.open-platform": "Plataforma abierta",
  "menu.app-center.open-platform-detail": "Verificar",
  "menu.app-center.open-platform-add": "Solicitud de aplicación",
  "menu.app-center.open-platform-edit": "Editar aplicación",
  "menu.log-center": "Centro de registros",
  "menu.log-center.robot-logs": "Registro de robots",
  "menu.message-center": "Centro de Noticias",
  "menu.message-center.message-detail": "Detalles del mensaje"
}