export default {
  "exception.monitor": "Monitoreo de anomalías",
  "key.whitelist": "{key} lista blanca",
  "risk.control.settings": "Configuración de control de riesgo",
  "robot.run.district": "Área de operación",
  "robot.report.time.latest": "Último tiempo reportado",
  "robot.lock.confirm": "Después de realizar la operación de bloqueo del dispositivo, el robot no podrá utilizarse, ni desvincularse ni cambiar de tienda vinculada.",
  "robot.lock.remark": "Información de la nota del bloqueo del dispositivo",
  "robot.unlock.confirm": "Al ejecutar la operación de desbloqueo, el robot eliminará la advertencia y volverá a su uso normal.",
  "robot.exception.view": "Ver detalles de la anomalía",
  "robot.info": "Información del robot",
  "shop.info": "Información de la tienda",
  "robot.category": "Tipo de robot",
  "robot.smuggling.warning": "Advertencia de anomalía, existe riesgo de contrabando de mercancías.",
  "robot.run.location": "Posición de funcionamiento",
  "key.remove": "eliminación",
  "time.add": "Añadir tiempo",
  "use.instructions": "Instrucciones de uso",
  "confirm.remove": "Al ejecutar la operación de eliminación, la máquina activará el mecanismo de control de riesgos de \"prevención de desvío de mercancías\".",
  "device.add": "Agregar dispositivo",
  "use.instruction.reason": "Razón por la cual la máquina se añade a la lista blanca",
  "query.result": "Resultados de la consulta",
  "query.byMac": "Consulta de dirección MAC",
  "base.version.No": "Número de versión base",
  "key.auto.lock": "Cierre automático {key}",
  "district.china.mainland.outside": "Hong Kong, Macao, Taiwán y el extranjero",
  "district.china.mainland": "Continente chino",
  "key.enable": "Activar",
  "edit.risk.control.settings": "Editar la configuración de control de riesgos",
  "robot.status.locked": "Ya está bloqueado el dispositivo.",
  "robot.status.unlock": "Desbloqueado",
  "robot.sn/pid": "Número de serie del equipo (PID)",
  "key.status": "{clave} estado",
  "risk.control": "Control de riesgo",
  "status.risk.control": "Estado de control de riesgo",
  "status.robot": "Estado del robot",
  "status.abnormal.watning": "Advertencia de anomalía",
  "datatype.nomal": "Datos normales",
  "datatype.nomal.tip": "Incluye: robots en la lista blanca, robots desbloqueados y robots que nunca han activado el control de riesgos de contrabando.",
  "datatype.abnomal": "Datos anormales",
  "opr.area": "{key} área de operaciones",
  "goto.check": "Ir a ver.",
  "risk.control.notify": "Notificación de control de riesgos",
  "risk.control.warntip": "Los robots operan dentro de una zona no autorizada, múltiples activaciones resultarán en el bloqueo del dispositivo.",
  "abnormal.waning.robots": "Dispositivo de advertencia de anomalías",
  "etc.": "esperar",
  "robot.lock.switch": "Interruptor de bloqueo",
  "robot.lock.auto": "Cierre automático",
  "robot.lock.manual": "Bloqueo manual",
  "abnormal.lock.robots": "Dispositivo de bloqueo de control de riesgo de viento",
  "robot.lock.tip": "Se ha activado el control de riesgo de mercancía desviada, actualmente el dispositivo está bloqueado. Si tiene alguna duda, contacte al personal de servicio de Purdu.",
  "warning.send.email": "Alerta de correo electrónico de advertencia de anomalías",
  "input.email.multiple": "Varias cuentas de correo electrónico ingresadas en líneas separadas",
  "input.forExample": "Ejemplo:",
  "email.invalid": "dirección de correo electrónico no conforme",
  "PuduBot": "Felicidad para llevar",
  "BellaBot": "Bella",
  "HolaBot": "Está bien",
  "Puductor": "Alegría Explosiva",
  "Puductor2": "Alegría Explosiva 2",
  "KettyBot": "calabaza de peregrino",
  "FlashBot": "Caja de relámpagos",
  "PuduCC1": "Fuera del polvo",
  "SwiftBot": "Entrega Inteligente",
  "PuduBot2": "Alegría 2",
  "PuduSH1": "León y tigre"
}