export default {
  "请输入": "Por favor, introduzca.",
  "选择": "selección",
  "返回": "regresar",
  "未绑定": "No vinculado",
  "已安装": "Instalado",
  "导入时间": "Tiempo de importación",
  "代理名称": "Nombre del agente",
  "所属代理": "Agencia afiliada",
  "出库撤回": "Retirada de inventario",
  "出库撤回说明": "Instrucciones para la revocación de salida de almacén",
  "撤回后下级代理": "Tras la retirada, el subagente ya no podrá ver ni operar este robot.",
  "出库撤回失败": "Fallo en la retirada del almacén",
  "该代理已将机器人绑定门店": "El agente ha vinculado el robot a la tienda.",
  "出库至下级代理": "Salida hacia el agente subordinado",
  "未选择下级代理商": "No se ha seleccionado un agente distribuidor subordinado.",
  "没有出库产品": "No hay productos despachados.",
  "确定出库": "Confirmar salida de almacén",
  "出库说明": "Instrucciones de Salida de Almacén",
  "选择未出库产品": "Seleccionar productos no despachados",
  "选择下级代理商": "Seleccionar subagente",
  "代理商帐号": "Cuenta de agente comercial",
  "注册地址": "Dirección de registro",
  "销售区域": "Área de ventas",
  "注册时间": "Fecha de registro",
  "一级": "Primera categoría",
  "二级": "Segundo nivel",
  "已损坏": "Dañado",
  "已锁机": "Ya está bloqueado el dispositivo.",
  "冻结中": "Congelado",
  "过期": "La inspección de fábrica ha caducado.",
  "未激活": "No activado",
  "激活": "Activar",
  "已激活": "Activado",
  "已入库": "Ya en almacén",
  "厂测中": "En pruebas de fábrica",
  "无记录": "Sin registro",
  "全部": "todo",
  "产品信息": "Información del producto",
  "维保信息": "Información de mantenimiento",
  "服务信息": "Información de servicio",
  "产品操作记录": "Registro de operación del producto",
  "换板待验证": "Cambio de placa pendiente de verificación",
  "待验证": "Pendiente de verificación",
  "所属门店": "Tienda afiliada",
  "所属代理商": "Agente afiliado",
  "激活时间": "Tiempo de activación",
  "昵称": "Apodo",
  "SN": "SN(PID)",
  "MAC": "MAC",
  "软件版本": "versión del software",
  "固件版本": "Versión del firmware",
  "现场用途": "Uso en el lugar",
  "机器分组": "Agrupación de máquinas",
  "用机类型": "Tipo de máquina",
  "保修时长": "Duración de la garantía",
  "实施工程师": "Ingeniero de implementación",
  "运维工程师": "Ingeniero de operaciones y mantenimiento",
  "首次导入代理": "Primera importación de agente:",
  "绑定代理": "Vinculación de agente:",
  "的门店": "de la tienda:",
  "从门店": "Desde la tienda:",
  "解绑返回代理": "Desvincular, volver al agente:",
  "代理": "Agente:",
  "出库产品到下级代理": "Productos enviados al agente subordinado:",
  "从下级代理": "Desde el agente de nivel inferior:",
  "出库撤回到代理": "Salida de almacén retirada al agente:",
  "操作说明": "Instrucciones de operación:",
  "操作人": "Operador:",
  "机器产品库使用提示": "El almacén de productos de la máquina incluye productos que han sido desvinculados de las tiendas de los comerciantes y devueltos al almacén; así como productos que ya han sido vendidos y vinculados a las tiendas de los comerciantes. Al mismo tiempo, puedes enviar productos \"no vinculados\" desde el almacén a tus agentes subordinados.",
  "未綁定状态": "Estado no vinculado: robots que aún no están vinculados a una tienda comercial y se encuentran en el estado de almacén.",
  "功能介绍": "Introducción de funciones:",
  "冻结": "Congelado",
  "取消冻结": "Cancelar congelación",
  "未绑定状态描述": "No vinculado: Estado en el que los productos se trasladan del almacén de la empresa Purdu al inventario del agente, y el agente no ha vendido ni vinculado a una tienda específica.",
  "未激活状态描述": "No activado: Estado en el que el agente vende el robot y lo vincula a una tienda física, pero el robot no se ha encendido ni activado.",
  "已激活状态描述": "Activado: Estado en el que el agente activa el robot vinculado a la tienda para su uso al encenderlo.",
  "已冻结状态描述": "Congelado: Estado del robot después de que el agente lo congela, en este estado el robot ya no podrá ser utilizado.",
  "换板待验证状态描述": "Cambio de placa pendiente de verificación: estado durante el proceso de reemplazo cuando la placa principal del robot está dañada.",
  "还剩": "todavía queda",
  "个月": "meses",
  "系统操作": "Operación del sistema",
  "租赁时长": "Duración del alquiler",
  "试用时长": "Duración de prueba",
  "试用截止时间": "Fecha límite de prueba",
  "门店安装时间": "Tiempo de instalación de la tienda",
  "备件信息": "Información de componentes",
  "备件类型": "Tipo de componente",
  "导出全部": "Exportar todo",
  "供应商": "Proveedor",
  "型号": "modelo",
  "上报时间": "Tiempo de reporte",
  "电池": "batería",
  "雷达": "Radar",
  "相机": "cámara",
  "核心板": "Placa base",
  "屏幕": "pantalla",
  "充电器": "Cargador",
  "功能板": "Versión funcional",
  "上位机": "Ordenador superior"
}