export default {
  "productListIframe.无记录": "Sin registro",
  "productListIframe.厂测中": "En pruebas de fábrica",
  "productListIframe.厂测过期": "Prueba de fábrica vencida",
  "productListIframe.已入库": "Ya en almacén",
  "productListIframe.未绑定": "No vinculado",
  "productListIframe.未激活": "No activado",
  "productListIframe.已激活": "Activado",
  "productListIframe.已冻结": "Congelado",
  "productListIframe.换板待验证": "Cambio de placa pendiente de verificación",
  "productListIframe.保内": "Dentro del seguro",
  "productListIframe.保外": "Fuera de garantía",
  "productListIframe.产品名称": "Nombre del producto",
  "productListIframe.所属门店": "Tienda afiliada",
  "productListIframe.所属代理": "Agencia afiliada",
  "productListIframe.产品状态": "Estado del producto",
  "productListIframe.首次激活时间": "Fecha de activación inicial",
  "productListIframe.最新安装时间": "Último tiempo de instalación",
  "productListIframe.代理维保状态": "Estado de mantenimiento del agente",
  "productListIframe.终端维保状态": "Estado de mantenimiento del terminal",
  "productListIframe.设备地址": "Dirección del dispositivo",
  "productListIframe.关闭": "Cerrado",
  "productListIframe.没有更多了": "No hay más.",
  "productListIframe.加载中": "Cargando",
  "productListIframe.请选择机器": "Por favor, seleccione la máquina.",
  "productListIframe.搜索": "Búsqueda",
  "productListIframe.清除筛选": "Limpiar filtro",
  "productListIframe.查看更多": "Ver más",
  "productListIframe.完成": "completado"
}