export default {
  "app.setting.pagestyle": "Configuración del estilo general",
  "app.setting.pagestyle.dark": "Estilo de menú oscuro",
  "app.setting.pagestyle.light": "Estilo de menú de colores brillantes",
  "app.setting.content-width": "Área de contenido de ancho",
  "app.setting.content-width.fixed": "Ancho fijo",
  "app.setting.content-width.fluid": "fluídico",
  "app.setting.themecolor": "Color principal",
  "app.setting.themecolor.dust": "Crepúsculo",
  "app.setting.themecolor.volcano": "volcán",
  "app.setting.themecolor.sunset": "Atardecer",
  "app.setting.themecolor.cyan": "Claro azul",
  "app.setting.themecolor.green": "Aurora verde",
  "app.setting.themecolor.daybreak": "Azul alba (predeterminado)",
  "app.setting.themecolor.geekblue": "Geek Azul",
  "app.setting.themecolor.purple": "Salsa de soja",
  "app.setting.navigationmode": "Modo de navegación",
  "app.setting.sidemenu": "Diseño del menú lateral",
  "app.setting.topmenu": "Diseño del menú superior",
  "app.setting.fixedheader": "Encabezado fijo",
  "app.setting.fixedsidebar": "Menú lateral fijo",
  "app.setting.fixedsidebar.hint": "El diseño del menú lateral se puede configurar.",
  "app.setting.hideheader": "Ocultar el encabezado al deslizar hacia abajo",
  "app.setting.hideheader.hint": "Encabezado fijo configurable",
  "app.setting.othersettings": "Otras configuraciones",
  "app.setting.weakmode": "Modo para daltónicos",
  "app.setting.copy": "Configuración de copia",
  "app.setting.copyinfo": "Copia realizada con éxito, por favor reemplace la configuración predeterminada en src/defaultSettings.js",
  "app.setting.production.hint": "La barra de configuración solo se utiliza para previsualización en el entorno de desarrollo y no se mostrará en el entorno de producción. Por favor, copie y modifique manualmente el archivo de configuración después."
}