export default {
  "app.settings.menuMap.basic": "Configuración básica",
  "app.settings.menuMap.security": "Configuración de seguridad",
  "app.settings.menuMap.binding": "Vinculación de cuenta",
  "app.settings.menuMap.notification": "Nueva notificación de mensaje",
  "app.settings.basic.avatar": "Avatar",
  "app.settings.basic.change-avatar": "Cambiar foto de perfil",
  "app.settings.basic.email": "correo electrónico",
  "app.settings.basic.email-message": "Por favor, introduzca su correo electrónico.",
  "app.settings.basic.nickname": "Apodo",
  "app.settings.basic.nickname-message": "Por favor, introduzca su apodo.",
  "app.settings.basic.profile": "Perfil personal",
  "app.settings.basic.profile-message": "¡Por favor, introduzca una breve descripción personal!",
  "app.settings.basic.profile-placeholder": "Perfil personal",
  "app.settings.basic.country": "País/Región",
  "app.settings.basic.country-message": "Por favor, introduzca su país o región.",
  "app.settings.basic.geographic": "Provincia o ciudad en la que se encuentra",
  "app.settings.basic.geographic-message": "Por favor, introduzca su provincia y ciudad de residencia.",
  "app.settings.basic.address": "Dirección de la calle",
  "app.settings.basic.address-message": "Por favor, introduzca su dirección de la calle.",
  "app.settings.basic.phone": "Teléfono de contacto",
  "app.settings.basic.phone-message": "Por favor, introduzca su número de teléfono de contacto.",
  "app.settings.basic.update": "Actualizar información básica",
  "app.settings.security.strong": "fuerte",
  "app.settings.security.medium": "centro",
  "app.settings.security.weak": "débil",
  "app.settings.security.password": "contraseña de la cuenta",
  "app.settings.security.password-description": "La fortaleza de la contraseña actual",
  "app.settings.security.phone": "Teléfono de seguridad",
  "app.settings.security.phone-description": "Teléfono móvil vinculado",
  "app.settings.security.question": "Pregunta de seguridad",
  "app.settings.security.question-description": "No se han establecido preguntas de seguridad, las preguntas de seguridad pueden proteger eficazmente la seguridad de la cuenta.",
  "app.settings.security.email": "Correo electrónico de reserva",
  "app.settings.security.email-description": "Correo electrónico vinculado",
  "app.settings.security.mfa": "Dispositivo MFA",
  "app.settings.security.mfa-description": "Dispositivo MFA no vinculado, después de vincularlo, se puede realizar una confirmación secundaria.",
  "app.settings.security.modify": "Modificación",
  "app.settings.security.set": "Configuración",
  "app.settings.security.bind": "Vinculación",
  "app.settings.binding.taobao": "Vincular Taobao",
  "app.settings.binding.taobao-description": "Actualmente no hay ninguna cuenta de Taobao vinculada.",
  "app.settings.binding.alipay": "Vincular Alipay",
  "app.settings.binding.alipay-description": "Actualmente no hay ninguna cuenta de Alipay vinculada.",
  "app.settings.binding.dingding": "Vincular DingTalk",
  "app.settings.binding.dingding-description": "Actualmente no se ha vinculado ninguna cuenta de DingTalk.",
  "app.settings.binding.bind": "Vinculación",
  "app.settings.notification.password": "contraseña de la cuenta",
  "app.settings.notification.password-description": "Los mensajes de otros usuarios se notificarán en forma de mensaje interno.",
  "app.settings.notification.messages": "Mensaje del sistema",
  "app.settings.notification.messages-description": "Los mensajes del sistema se notificarán en forma de mensajes internos.",
  "app.settings.notification.todo": "Tareas pendientes",
  "app.settings.notification.todo-description": "Las tareas pendientes se notificarán mediante mensajes internos.",
  "app.settings.open": "abrir",
  "app.settings.close": "Cerrado",
  "robot.check.blacklist": "La dirección MAC ha sido añadida a la lista negra, por favor contacte con la empresa Purdue para su gestión."
}