export default {
  "language.select.label": "Seleccionar idioma",
  "voice.add": "Agregar voz",
  "voice.category": "Clasificación de voz",
  "voice.mp3": "Archivo de audio de voz",
  "voice.mp3.del.confirm": "Al eliminar este audio, los paquetes de voz personalizados que se añadan posteriormente ya no incluirán el audio de esta escena.",
  "voice.language": "Idioma de voz",
  "voice.id.correct.tip": "Por favor, rellene el VoiceID correcto del robot, de lo contrario no se podrá realizar el anuncio.",
  "voice.display.scene.desc": "Escenario de locución en off",
  "voice.display.content": "Contenido del texto del anuncio de voz",
  "voice.upload.limit": "Se admite la carga de archivos MP3 de hasta 1MB.",
  "voice.pkg.desc": "Descripción del paquete de voz",
  "voice.access": "Robot autorizado",
  "voice.pkg.auth": "Paquete de voz autorizado",
  "key.agent.name": "agente comercial",
  "key.auth.add": "Agregar autorización",
  "key.batch.replace": "Reemplazo en lote",
  "key.robot.category": "Tipo de robot",
  "key.robot.No": "robots numéricos",
  "voice.all": "Todas las voces",
  "voice.merge.submit": "sintetizar voz y completar",
  "voice.merge.submit.failed": "La actualización del paquete de voz ha fallado",
  "voice.change.mp3": "Cambiar audio",
  "voice.validity.period.tip": "Por favor, seleccione la fecha de vencimiento",
  "voice.authorized.mac.tip": "Otorgar la licencia de este paquete de voz a los siguientes robots {robot}",
  "voice.authorized.store.tip": "Autorizar este paquete de voz para el robot {robot} de las siguientes tiendas.",
  "voice.authorized.agent.tip": "Otorgar la licencia de este paquete de voz a todas las tiendas bajo el agente para el robot {robot}.",
  "voice.voiceid.notmatch": "El nombre del archivo no coincide con ningún VoiceID.",
  "voice.filesize.exceed": "El tamaño del archivo excede el límite permitido.",
  "voice.upload.warning1": "Necesita comprimir los archivos dentro de la carpeta, no es necesario comprimir la carpeta.",
  "voice.upload.warning2": "El nombre del audio debe ser el voiceID correspondiente al tipo de producto de robot.",
  "voice.upload.warning3": "Se admiten hasta 200 archivos de audio mp3, y no deben superar los 200MB.",
  "voice.upload.warning4": "Debido a que el archivo es grande, no se puede salir durante el proceso de carga.",
  "not.your.robot": "No es un robot de su inventario.",
  "key.limit.import.count": "Limitar {key}个",
  "navBar.lang": "idioma"
}