export default {
  "bd.account": "บัญชี",
  "bd.username": "ชื่อ",
  "bd.role": "ตัวละคร",
  "bd.name": "ชื่อย่านการค้า",
  "bd.numOfStores": "จำนวนสาขา",
  "bd.createtime": "เวลาที่สร้าง",
  "bd.updatetime": "เวลาอัปเดต",
  "bd.operation": "การดำเนินการ",
  "bd.check": "ตรวจสอบ",
  "bd.edit": "บรรณาธิการ",
  "bd.qrcode": "ดาวน์โหลดคิวอาร์โค้ด",
  "bd.new": "เพิ่มเติม",
  "bd.goback": "กลับ",
  "bd.account.placeholder": "กรุณาใส่หมายเลขบัญชี",
  "bd.name.placeholder": "กรุณากรอกชื่อย่านการค้า",
  "bd.inquire": "การค้นหา",
  "bd.reset": "รีเซ็ต",
  "bd.store.tip": "กรุณาเลือกสาขา",
  "bd.store.placeholder": "กรุณาใส่ชื่อของคุณ",
  "bd.map.tip": "กรุณาเลือกแผนที่",
  "bd.store.order": "ลำดับ",
  "bd.store.name": "ชื่อร้านค้า",
  "bd.store.label": "เลือกสาขา",
  "bd.map.label": "เลือกแผนที่",
  "bd.map.name": "ชื่อแผนที่",
  "bd.map.uploadtype": "ประเภทการอัปโหลด",
  "bd.map.association": "จำนวนผลิตภัณฑ์ที่เกี่ยวข้อง",
  "bd.map.version": "เวอร์ชัน",
  "bd.map.using": "กำลังใช้งาน",
  "bd.map.unused": "ไม่ได้ใช้งาน",
  "bd.map.uploadtype.apk": "อัปโหลด APK",
  "bd.map.uploadtype.platform": "อัปโหลดแพลตฟอร์ม",
  "bd.map.choose": "เลือก",
  "bd.store.industry": "อุตสาหกรรม",
  "bd.store.address": "ที่อยู่ร้านค้า",
  "bd.store.normal": "ปกติ",
  "bd.store.logout": "ยกเลิก",
  "bd.insiders.noOperatingAuthority": "พนักงานภายในไม่มีสิทธิ์ในการดำเนินการ!",
  "bd.store.reminder": "คำแนะนำอบอุ่น: รองรับเฉพาะร้านค้าที่อยู่ในสถานะ \"ปกติ\" เท่านั้น"
}