export default {
  "component.tagSelect.expand": "แผ่ขยาย",
  "component.tagSelect.collapse": "เก็บไว้",
  "component.tagSelect.all": "ทั้งหมด",
  "key.select.max": "เลือกหุ่นยนต์ได้มากที่สุด {key} ตัว",
  "trial.period.day": "ระยะเวลาทดลองใช้/วัน",
  "lease.cycle.month": "ระยะเวลาการเช่า/เดือน",
  "required.warn": "คุณมีเนื้อหาที่จำเป็นต้องกรอก",
  "first.imp.time": "ครั้งแรกของการนำเข้าข้อมูล",
  "validate.robot.key.warn": "กรุณาใส่ SN (PID) หรือ MAC ให้ครบถ้วน",
  "change.to.complex.query": "เปลี่ยนไปใช้การค้นหาแบบซับซ้อน",
  "change.to.simple.query": "เปลี่ยนไปใช้การค้นหาแบบง่าย",
  "openapi.docs": "เอกสารคู่มือการพัฒนา API",
  "customer.name": "ชื่อร้านค้า",
  "key.template": "แม่แบบ",
  "confirm.file.upload": "กรุณายืนยันว่าไฟล์ถูกอัปโหลดเสร็จสิ้นแล้วหรือไม่",
  "upload.fail": "อัปโหลดไม่สำเร็จ กรุณาลองใหม่",
  "key.success": "ความสำเร็จ",
  "key.fail": "ล้มเหลว",
  "import.result": "ผลการนำเข้า",
  "incompatibility.versions": "เวอร์ชันใหม่ไม่สามารถใช้ร่วมกับเวอร์ชันเก่าได้",
  "auto.jump.available": "กำลังจะเปลี่ยนไปยังเวอร์ชันที่สามารถใช้งานได้...",
  "import.maxcount.tip": "ตรวจพบว่ามี MAC เกิน {count} ตัว ระบบจะนำเข้า MAC แค่ {count} ตัวแรกเท่านั้น สำหรับ MAC ที่เหลือกรุณานำเข้าใหม่อีกครั้ง"
}