export default {
  "log.boot": "เปิดเครื่องตรวจสอบตนเอง",
  "log.abnormal": "ข้อผิดพลาดที่ผิดปกติ",
  "log.charge": "บันทึกการชาร์จ",
  "log.battery": "สถานะสุขภาพแบตเตอรี่",
  "production.date": "วันที่สร้าง",
  "boot.status": "สถานะ",
  "boot.undetected": "ไม่ได้ตรวจจับ",
  "boot.normal": "ปกติ",
  "boot.abnormal": "ผิดปกติ",
  "key.no": "รหัส",
  "log.production.time": "เวลาสร้างบันทึก",
  "log.push.time": "เวลาบันทึกบนคลาวด์",
  "boot.description": "คำอธิบาย",
  "boot.check_module": "สถานะโมดูลตรวจสอบตนเอง",
  "poweron.ratio": "อัตราส่วนการจัดเก็บ (%)",
  "robot.softVer": "เวอร์ชันซอฟต์แวร์",
  "robot.hardVer": "เฟิร์มแวร์ 版本",
  "common.systemid": "รุ่นของระบบปฏิบัติการ",
  "common.battery": "ปัจจุบันแบตเตอรี่",
  "check.abnormal": "มีข้อผิดพลาด",
  "check.normal": "ไม่มีความผิดปกติ",
  "error.category": "ประเภทของความเสียหาย",
  "error.detail": "รายละเอียดของการเสียหาย",
  "error.grade": "ระดับความเสียหาย",
  "error.list": "รายการข้อผิดพลาด",
  "error.ID": "รหัสข้อผิดพลาด",
  "filter.more": "ตัวกรองเพิ่มเติม",
  "charge.count_battery": "ปริมาณการชาร์จแบตเตอรี่",
  "charge.count_time": "ระยะเวลาในการชาร์จ",
  "soh.battery_sn": "หมายเลขซีเรียลของแบตเตอรี่",
  "soh.full": "ความจุแบตเตอรี่ (mAh)",
  "soh.remaining": "ความจุที่เหลือ (mAh)",
  "soh.battery_voltage": "แรงดันไฟฟ้าของแบตเตอรี่ (มิลลิโวลต์)",
  "soh.soh": "ดัชนีสุขภาพแบตเตอรี่",
  "soh.cycle": "จำนวนรอบ",
  "soh.battery_type": "ประเภทของแบตเตอรี่",
  "tip.soh": "จะรายงานบันทึกเมื่อฟิลด์นี้มีการเปลี่ยนแปลง",
  "key.clip": "คัดลอกด้วยคลิกเดียว",
  "collapse": "เก็บไว้",
  "please.select": "กรุณาเลือก",
  "please.input": "กรุณาใส่ข้อมูล",
  "cycle.range.tip": "ไม่มีข้อมูลในช่วงวงจร"
}