export default {
  "exception.monitor": "การตรวจสอบความผิดปกติ",
  "key.whitelist": "{key} รายชื่อขาว",
  "risk.control.settings": "การตั้งค่าควบคุมความเสี่ยง",
  "robot.run.district": "พื้นที่ปฏิบัติการ",
  "robot.report.time.latest": "เวลาที่รายงานล่าสุด",
  "robot.lock.confirm": "หลังจากดำเนินการล็อคเครื่องแล้ว หุ่นยนต์จะไม่สามารถใช้งาน ไม่สามารถยกเลิกการผูกมัดและเปลี่ยนการผูกมัดกับร้านค้าได้",
  "robot.lock.remark": "หมายเหตุข้อมูลการล็อคเครื่อง",
  "robot.unlock.confirm": "หลังจากดำเนินการปลดล็อคแล้ว หุ่นยนต์จะยกเลิกการเตือนและกลับมาใช้งานได้ตามปกติ",
  "robot.exception.view": "ตรวจสอบรายละเอียดข้อผิดพลาด",
  "robot.info": "ข้อมูลหุ่นยนต์",
  "shop.info": "ข้อมูลร้านค้า",
  "robot.category": "ประเภทหุ่นยนต์",
  "robot.smuggling.warning": "คำเตือนผิดปกติ มีความเสี่ยงของการลักลอบขนสินค้า",
  "robot.run.location": "ตำแหน่งการทำงาน",
  "key.remove": "ย้ายออก",
  "time.add": "เพิ่มเวลา",
  "use.instructions": "คำแนะนำการใช้งาน",
  "confirm.remove": "หลังจากดำเนินการลบออกแล้ว ระบบจะเริ่มต้นกลไก \"การควบคุมความเสี่ยงของการลักลอบขนสินค้า\"",
  "device.add": "เพิ่มอุปกรณ์",
  "use.instruction.reason": "เหตุผลที่เครื่องถูกเพิ่มไปยังรายการขาว",
  "query.result": "ผลการค้นหา",
  "query.byMac": "การค้นหาที่อยู่ MAC",
  "base.version.No": "หมายเลขเวอร์ชันมาตรฐาน",
  "key.auto.lock": "ล็อคอัตโนมัติ{key}",
  "district.china.mainland.outside": "ฮ่องกง มาเก๊า ไต้หวัน และต่างประเทศ",
  "district.china.mainland": "จีนแผ่นดินใหญ่",
  "key.enable": "เปิดใช้งาน",
  "edit.risk.control.settings": "แก้ไขการตั้งค่าควบคุมความเสี่ยง",
  "robot.status.locked": "เครื่องถูกล็อค",
  "robot.status.unlock": "ได้ปลดล็อคแล้ว",
  "robot.sn/pid": "อุปกรณ์ SN (PID)",
  "key.status": "สถานะ{key}",
  "risk.control": "ควบคุมความเสี่ยง",
  "status.risk.control": "สถานะการควบคุมความเสี่ยง",
  "status.robot": "สถานะหุ่นยนต์",
  "status.abnormal.watning": "คำเตือนความผิดปกติ",
  "datatype.nomal": "ข้อมูลปกติ",
  "datatype.nomal.tip": "รวมถึง: หุ่นยนต์ที่ถูกเพิ่มเข้าไปในรายชื่อขาว, หุ่นยนต์ที่ถูกปลดล็อค และหุ่นยนต์ที่ไม่เคยทำให้เกิดการควบคุมการลักลอบขนสินค้า",
  "datatype.abnomal": "ข้อมูลผิดปกติ",
  "opr.area": "{key} พื้นที่ดำเนินการ",
  "goto.check": "ไปตรวจสอบ",
  "risk.control.notify": "แจ้งเตือนควบคุมความเสี่ยง",
  "risk.control.warntip": "หุ่นยนต์ทำงานในพื้นที่ที่ไม่ได้รับอนุญาต หากกระทำซ้ำหลายครั้งจะทำการล็อคเครื่อง",
  "abnormal.waning.robots": "อุปกรณ์เตือนภัยผิดปกติ",
  "etc.": "รอ",
  "robot.lock.switch": "สวิตช์ล็อคเครื่อง",
  "robot.lock.auto": "ล็อคอัตโนมัติ",
  "robot.lock.manual": "ล็อคเครื่องด้วยมือ",
  "abnormal.lock.robots": "อุปกรณ์ล็อคเครื่องเพื่อการควบคุมความเสี่ยง",
  "robot.lock.tip": "กระตุ้นการควบคุมสินค้าที่ลักลอบขนย้าย ณ ปัจจุบันเครื่องถูกล็อค หากมีข้อสงสัยกรุณาติดต่อเจ้าหน้าที่บริการของปูตู้",
  "warning.send.email": "กล่องจดหมายเตือนภัยผิดปกติ",
  "input.email.multiple": "หลายอีเมลใส่แล้วขึ้นบรรทัดใหม่",
  "input.forExample": "ตัวอย่าง",
  "email.invalid": "ที่อยู่อีเมลที่ไม่เป็นไปตามกฎ",
  "PuduBot": "ส่งความสุข",
  "BellaBot": "เบลล่า",
  "HolaBot": "ดีแล้ว",
  "Puductor": "ความสุขในการกำจัด",
  "Puductor2": "เกมส์สนุกๆ 2",
  "KettyBot": "ฟักทอง",
  "FlashBot": "กล่องฟ้าผ่า",
  "PuduCC1": "ออกจากฝุ่นควัน",
  "SwiftBot": "คิวเลอร์ซง",
  "PuduBot2": "ความสุขส่ง 2",
  "PuduSH1": "สิงโตและเสือ"
}