export default {
  "app.setting.pagestyle": "การตั้งค่าสไตล์โดยรวม",
  "app.setting.pagestyle.dark": "สไตล์เมนูสีเข้ม",
  "app.setting.pagestyle.light": "สไตล์เมนูสีสันสดใส",
  "app.setting.content-width": "พื้นที่ความกว้างของเนื้อหา",
  "app.setting.content-width.fixed": "กำหนดความกว้าง",
  "app.setting.content-width.fluid": "ไหล",
  "app.setting.themecolor": "สีธีม",
  "app.setting.themecolor.dust": "ค่ำคืน",
  "app.setting.themecolor.volcano": "ภูเขาไฟ",
  "app.setting.themecolor.sunset": "ค่ำคืน",
  "app.setting.themecolor.cyan": "สีฟ้าอ่อน",
  "app.setting.themecolor.green": "แสงเหนือสีเขียว",
  "app.setting.themecolor.daybreak": "สีฟ้ารุ่งอรุณ (ค่าเริ่มต้น)",
  "app.setting.themecolor.geekblue": "กีคบลู",
  "app.setting.themecolor.purple": "ซอสม่วง",
  "app.setting.navigationmode": "โหมดนำทาง",
  "app.setting.sidemenu": "เมนูด้านข้าง",
  "app.setting.topmenu": "เมนูบนสุด",
  "app.setting.fixedheader": "หัวข้อคงที่",
  "app.setting.fixedsidebar": "เมนูด้านข้างที่ติดตั้งแน่นหนา",
  "app.setting.fixedsidebar.hint": "เมนูด้านข้างสามารถกำหนดค่าเมื่อจัดวางได้",
  "app.setting.hideheader": "เมื่อเลื่อนลงซ่อนส่วนหัว",
  "app.setting.hideheader.hint": "ตั้งค่า Header ได้เมื่อทำการกำหนดค่า",
  "app.setting.othersettings": "การตั้งค่าอื่นๆ",
  "app.setting.weakmode": "โหมดสำหรับผู้ที่มีปัญหาการมองเห็นสี",
  "app.setting.copy": "คัดลอกการตั้งค่า",
  "app.setting.copyinfo": "คัดลอกสำเร็จแล้ว โปรดไปที่ src/defaultSettings.js เพื่อแทนที่การตั้งค่าเริ่มต้น",
  "app.setting.production.hint": "แถบการตั้งค่าใช้สำหรับการแสดงตัวอย่างในสภาพแวดล้อมการพัฒนาเท่านั้น จะไม่แสดงในสภาพแวดล้อมการผลิต กรุณาคัดลอกและแก้ไขไฟล์การตั้งค่าด้วยตนเอง"
}