export default {
  "app.settings.menuMap.basic": "การตั้งค่าพื้นฐาน",
  "app.settings.menuMap.security": "การตั้งค่าความปลอดภัย",
  "app.settings.menuMap.binding": "การผูกบัญชี",
  "app.settings.menuMap.notification": "ข่าวสารแจ้งเตือนใหม่",
  "app.settings.basic.avatar": "รูปโปรไฟล์",
  "app.settings.basic.change-avatar": "เปลี่ยนรูปโปรไฟล์",
  "app.settings.basic.email": "กล่องจดหมาย",
  "app.settings.basic.email-message": "กรุณากรอกอีเมลของคุณ!",
  "app.settings.basic.nickname": "ชื่อเล่น",
  "app.settings.basic.nickname-message": "กรุณากรอกชื่อเล่นของคุณ!",
  "app.settings.basic.profile": "ประวัติส่วนตัว",
  "app.settings.basic.profile-message": "กรุณากรอกข้อมูลประวัติส่วนตัว!",
  "app.settings.basic.profile-placeholder": "ประวัติส่วนตัว",
  "app.settings.basic.country": "ประเทศ/ภูมิภาค",
  "app.settings.basic.country-message": "กรุณากรอกชื่อประเทศหรือภูมิภาคของคุณ!",
  "app.settings.basic.geographic": "จังหวัด/เมืองที่อยู่",
  "app.settings.basic.geographic-message": "กรุณากรอกจังหวัดและเมืองที่คุณอยู่!",
  "app.settings.basic.address": "ที่อยู่ถนน",
  "app.settings.basic.address-message": "กรุณาใส่ที่อยู่ถนนของคุณ!",
  "app.settings.basic.phone": "เบอร์ติดต่อ",
  "app.settings.basic.phone-message": "กรุณาใส่หมายเลขโทรศัพท์ของคุณ!",
  "app.settings.basic.update": "อัปเดตข้อมูลพื้นฐาน",
  "app.settings.security.strong": "แข็ง",
  "app.settings.security.medium": "ไทย",
  "app.settings.security.weak": "อ่อนแอ",
  "app.settings.security.password": "รหัสบัญชี",
  "app.settings.security.password-description": "ระดับความแข็งแกร่งของรหัสผ่านปัจจุบัน",
  "app.settings.security.phone": "โทรศัพท์มือถือความปลอดภัย",
  "app.settings.security.phone-description": "โทรศัพท์มือถือที่ผูกไว้แล้ว",
  "app.settings.security.question": "คำถามความปลอดภัย",
  "app.settings.security.question-description": "ยังไม่ได้ตั้งคำถามความปลอดภัย คำถามความปลอดภัยสามารถช่วยปกป้องความปลอดภัยของบัญชีได้อย่างมีประสิทธิภาพ",
  "app.settings.security.email": "อีเมลสำรอง",
  "app.settings.security.email-description": "อีเมลที่ผูกไว้แล้ว",
  "app.settings.security.mfa": "อุปกรณ์ MFA",
  "app.settings.security.mfa-description": "ยังไม่ได้ผูกมัดอุปกรณ์ MFA หลังจากผูกมัดแล้ว สามารถทำการยืนยันครั้งที่สองได้",
  "app.settings.security.modify": "แก้ไข",
  "app.settings.security.set": "การตั้งค่า",
  "app.settings.security.bind": "ผูกมัด",
  "app.settings.binding.taobao": "ผูกบัญชีกับ Taobao",
  "app.settings.binding.taobao-description": "ขณะนี้ยังไม่ได้ผูกบัญชี Taobao",
  "app.settings.binding.alipay": "ผูกบัญชี Alipay",
  "app.settings.binding.alipay-description": "ขณะนี้ยังไม่ได้ผูกบัญชี Alipay",
  "app.settings.binding.dingding": "ผูกบัญชีกับ DingTalk",
  "app.settings.binding.dingding-description": "ขณะนี้ยังไม่ได้ผูกบัญชี DingTalk",
  "app.settings.binding.bind": "ผูกมัด",
  "app.settings.notification.password": "รหัสบัญชี",
  "app.settings.notification.password-description": "ข้อความจากผู้ใช้รายอื่นจะแจ้งให้ทราบในรูปแบบข้อความภายในเว็บไซต์",
  "app.settings.notification.messages": "ข้อความระบบ",
  "app.settings.notification.messages-description": "ข้อความระบบจะแจ้งเตือนในรูปแบบของข้อความภายในเว็บไซต์",
  "app.settings.notification.todo": "งานที่ต้องทำ",
  "app.settings.notification.todo-description": "งานที่ต้องทำจะแจ้งเตือนในรูปแบบข้อความภายในเว็บไซต์",
  "app.settings.open": "เปิด",
  "app.settings.close": "กวน",
  "robot.check.blacklist": "ที่อยู่ MAC นี้ได้ถูกเพิ่มเข้าไปในบัญชีดำแล้ว กรุณาติดต่อบริษัท Purdue เพื่อดำเนินการ"
}