export default {
  "language.select.label": "เลือกภาษา",
  "voice.add": "เพิ่มเสียง",
  "voice.category": "การจำแนกประเภทเสียง",
  "voice.mp3": "ไฟล์เสียง",
  "voice.mp3.del.confirm": "หลังจากลบเสียงนี้แล้ว แพ็คเกจเสียงที่กำหนดเองที่เพิ่มเข้ามาใหม่จะไม่รวมเสียงสถานการณ์นี้อีก",
  "voice.language": "ภาษาพูด",
  "voice.id.correct.tip": "กรุณากรอก VoiceID ของหุ่นยนต์ให้ถูกต้อง มิฉะนั้นจะไม่สามารถเล่นเสียงได้",
  "voice.display.scene.desc": "ฉากการเล่าเรื่องด้วยเสียง",
  "voice.display.content": "เนื้อหาของคำบรรยายที่เล่นผ่านระบบเสียง",
  "voice.upload.limit": "รองรับการอัปโหลดไฟล์ MP3 ขนาดสูงสุด 1MB",
  "voice.pkg.desc": "คำอธิบายแพ็คเสียง",
  "voice.access": "หุ่นยนต์ที่ได้รับอนุญาต",
  "voice.pkg.auth": "การอนุญาตแพ็กเสียง",
  "key.agent.name": "ตัวแทนจำหน่าย",
  "key.auth.add": "เพิ่มสิทธิ์การใช้งาน",
  "key.batch.replace": "การแทนที่แบบกลุ่ม",
  "key.robot.category": "ประเภทหุ่นยนต์",
  "key.robot.No": "หุ่นยนต์จำนวน",
  "voice.all": "ทั้งหมดเป็นเสียง",
  "voice.merge.submit": "สังเคราะห์เสียงและเสร็จสิ้น",
  "voice.merge.submit.failed": "แพ็คเกจเสียงอัปเดตไม่สำเร็จ",
  "voice.change.mp3": "เปลี่ยนไฟล์เสียง",
  "voice.validity.period.tip": "กรุณาเลือกวันหมดอายุ",
  "voice.authorized.mac.tip": "จะให้สิทธิ์แพ็คเกจเสียงนี้กับหุ่นยนต์{robot}ด้านล่าง",
  "voice.authorized.store.tip": "จะให้สิทธิ์แพ็กเกจเสียงนี้กับหุ่นยนต์ {robot} ที่ร้านค้าต่อไปนี้",
  "voice.authorized.agent.tip": "จะให้สิทธิ์แพ็กเกจเสียงนี้กับตัวแทนจำหน่ายทุกสาขาสำหรับหุ่นยนต์{robot}",
  "voice.voiceid.notmatch": "ชื่อไฟล์ไม่ตรงกับ VoiceID ใดๆ",
  "voice.filesize.exceed": "ขนาดของไฟล์เกินขีดจำกัดที่อนุญาต",
  "voice.upload.warning1": "ต้องการให้ทำการย้ายไฟล์ภายในโฟลเดอร์ ไม่จำเป็นต้องบีบอัดโฟลเดอร์",
  "voice.upload.warning2": "ชื่อไฟล์เสียงต้องเป็น voiceID ที่สอดคล้องกับประเภทผลิตภัณฑ์หุ่นยนต์",
  "voice.upload.warning3": "รองรับไฟล์เสียง mp3 ได้มากที่สุด 200 ไฟล์ และขนาดไม่เกิน 200MB",
  "voice.upload.warning4": "เนื่องจากไฟล์มีขนาดใหญ่ ระหว่างการอัปโหลดไม่สามารถออกจากระบบได้",
  "not.your.robot": "ไม่ใช่หุ่นยนต์ในสต็อกของคุณ",
  "key.limit.import.count": "จำกัด {key} คน",
  "navBar.lang": "ภาษา"
}