export default {
  "联系邮箱": "contact e-mail",
  "代理商等级": "Agentniveau",
  "上级代理商": "Hoofdagent",
  "重置密码": "Wachtwoord resetten",
  "新密码": "Nieuw wachtwoord",
  "操作成功": "Operatie geslaagd",
  "操作失败": "Operatie mislukt",
  "共n条记录": "In totaal {total} records",
  "是否前往": "Account succesvol toegevoegd, ga naar \"Klantencentrum\" om basisinformatie van de agent aan te vullen.",
  "未添加无法登录": "Tips: Als de basisinformatie van de agent niet is toegevoegd, kan er niet met het account worden ingelogd op het systeem.",
  "立即前往": "Onmiddellijk gaan",
  "查看账号": "Bekijk accountinformatie",
  "生成新密码": "Klik hier om een nieuw wachtwoord aan te maken",
  "随机密码": "Willekeurig wachtwoord",
  "更换密码": "Wachtwoord wijzigen",
  "复制密码": "Kopieer wachtwoord",
  "已复制！": "Gekopieerd!",
  "图片裁剪": "Afbeelding bijsnijden",
  "获取文件md5出错": "Het verkrijgen van de md5 van het bestand is mislukt.",
  "oss删除文件失败": "Het verwijderen van bestanden in OSS is mislukt.",
  "视频个数超出限额": "Het aantal video's overschrijdt de limiet.",
  "素材类型不正确": "Het formaat van het materiaal is niet correct",
  "图片过大": "De afbeelding is te groot.",
  "视频过大": "Het videobestand is te groot",
  "分辨率超出": "Resolutie hoger dan {height}P",
  "账号不能包含空格": "Het account mag geen spaties bevatten.",
  "账号已存在": "Account bestaat al",
  "请设置密码": "Stel een wachtwoord in",
  "密码规则": "Hoofdletters, kleine letters, cijfers, combinatie van drie soorten speciale tekens",
  "agent.store.info": "Enkel de aantallen van winkels uitgebreid door de huidige agent worden geteld, dit is exclusief het aantal winkels van ondergeschikte agenten.",
  "account.noOrg.warning": "Het account heeft geen informatie over de agent aangevuld, neem contact op met de persoon die uw account heeft aangemaakt voor afhandeling.",
  "login.redirect": "U wordt binnen {keyProp} seconden naar de pagina \"Handelaarsbeheerplatform\" geleid.",
  "login.suc": "Inloggen geslaagd",
  "login.fail": "Inloggen mislukt",
  "enter.nowait": "Geen wachttijd, klik om te betreden",
  "agent.type": "Agenttype",
  "请勿输入非法字符": "Gelieve geen illegale tekens in te voeren"
}