export default {
  "中国港澳台及海外地区": "China, Hongkong, Macau, Taiwan en overzeese gebieden",
  "中国大陆地区": "het vasteland van China",
  "代理商类型": "Agenttype",
  "类型": "soort",
  "请选择代理商类型": "Kies het type agent.",
  "运营区域": "Verkoopgebied",
  "请选择可销售的区域": "Selecteer het verkoopbare gebied",
  "新增代理商": "Nieuwe agenten",
  "一级代理商": "Eerstegraads distributeur",
  "二级代理商": "Tweedegraads distributeur",
  "一级": "Eerste niveau",
  "二级": "tweede niveau",
  "代理账号": "Gedelegeerde account",
  "公司所在地": "Bedrijfslocatie",
  "注册时间": "Registratietijd",
  "注册地区": "Geregistreerd gebied",
  "销售区域": "Verkoopgebied",
  "上级代理商名称": "Naam van de hogere agent",
  "拓展门店数": "Uitbreiding van het aantal winkels",
  "激活绑定数": "Geactiveerd aantal/Gekoppelde apparaten",
  "前往文件中心": "Ga naar het \"Documentencentrum\"",
  "知道了": "Begrepen",
  "结束日期": "einddatum",
  "开始日期": "Begindatum",
  "公司所在地不完整": "Het adres van het bedrijf is onvolledig.",
  "请输入纯数字": "Voer het telefoonnummer in met alleen cijfers."
}