export default {
  "open.platform.title": "PUDU Open Platform",
  "open.platform.desc": "Purdue Open Platform kan open software- en hardware-services bieden aan ontwikkelaars van robotica. Met behulp van de Purdue Open Platform kunnen ontwikkelaars volledig gebruik maken van alle functies van de robot, de robot combineren met verschillende industrieën, vanaf nul beginnen met de ontwikkeling van robotica en onbeperkte mogelijkheden creëren voor projecten.",
  "H-C.interaction": "Mens-machine-interactie",
  "navigation.control": "Navigatiecontrole",
  "voice.play": "Spraakbericht",
  "full.amount.data": "Volledige gegevens",
  "view.api.doc": "Bekijk de API open documentatie",
  "know.detail": "Meer weten",
  "apply.sdk": "Aanvraag voor Remote Control SDK",
  "apply.agent": "Aanvraag voor vertegenwoordiging",
  "apply.people": "Aanvrager",
  "apply.email": "Aanvrager e-mail",
  "apply.purpose": "Aanvraagdoel",
  "device.id": "Apparaat-ID",
  "device.secret": "sleutel",
  "app.secret": "Toepassingssleutel",
  "apply.time": "Aanvraagtijd",
  "applicant.info": "Aanvrager informatie",
  "receive.email": "Ontvangen berichten mailbox",
  "apply.app.info": "Aanvraag voor applicatie-informatie",
  "applicable.stores": "Toepasselijke winkels",
  "app.stores.tip": "Selecteer de winkel waartoe de robot die op afstand moet worden bestuurd behoort.",
  "apply.functions": "Aanvraagfunctie",
  "apply.desc": "U bent bezig met het aanvragen van de \"Remote Control Open SDK\", waarmee ontwikkelaars de open functies van deze SDK kunnen aanroepen binnen hun eigen ontwikkelde platformen om op afstand robots in winkels aan te sturen.",
  "api.doc.desc": "Afstandsbediening Open SDK-documentatie",
  "api.sdk.download": "Na goedkeuring kunt u het downloaden.",
  "openplatform.email": "Purdue ontwikkelaars vraag e-mailbox",
  "email.input.tip": "Zorg ervoor dat u het correct invult, het wordt gebruikt om de sleutel en SDK-informatie te ontvangen nadat de aanvraag is goedgekeurd.",
  "approved.tip": "Het bewerken van app-informatie zal direct van kracht zijn, zonder dat herhaalde goedkeuring nodig is.",
  "regionId.diff.tip": "De oorspronkelijke adressen van de winkels zijn verschillend.",
  "voice.play.mgt": "Spraakberichtbeheer",
  "voice.play.subtitle": "Aangepaste configuratie van spraakberichten voor verschillende scenario's, zoals het aantrekken van klanten, promoties en het werven van klanten, maakt de robot een meer professionele marketingexpert.",
  "emoticon.interface.mgt": "Emoticon-interfacebeheer",
  "emoticon.interface.subtitle": "Gepersonaliseerde instellingen van verschillende interessante en leuke robotgezichtsuitdrukkingen maken de robot aantrekkelijker voor klanten.",
  "open.platform.subtitle": "Robots volledige keten technologische capaciteiten worden opengesteld, om ontwikkelaars te helpen toepassingen in alle industrieën te realiseren.",
  "emo.pack.name": "Emoticonpakketnaam",
  "emo.pack.create": "Maak een aangepaste emoticonpakket",
  "apply.scope": "Toepassingsgebied",
  "opr.steps": "Bedieningsprocedure",
  "opr.steps.sub": "Zorg ervoor dat je de stappen volgt, anders zal de instelling mislukken.",
  "steps.1": "Stap 1",
  "steps.1.desc": "Download het huidige emoticonpakket van de robot.",
  "steps.2": "Stap 2",
  "steps.2.desc": "Vervang de bestaande bestanden één voor één met nieuwe emoticonbestanden.",
  "steps.2.desc.ketty": "De kalebas omvat 2 sets emoticons: \"double_eye\" en \"single_eye\". Kies om een van de sets emoticons te vervangen, gebruik het \"nieuwe emoticonbestand\" om een set emoticons in de \"animatie\" en \"firstImage\" mappen te vervangen.",
  "steps.2.ps1": "De hiërarchie, naamgeving en het aantal van mappen en bestanden moeten strikt ongewijzigd blijven.",
  "steps.2.ps2": "2. De resolutie van de afbeelding is 1920*1200 pixels, het formaat is .png; het formaat voor emoticons is .mp4; de hele map mag niet groter zijn dan 50MB.",
  "steps.2.ps2.ketty": "2. De resolutie van de eerste afbeelding is 1280*800, in .png-formaat, minder dan 100KB; het formaat voor de emoticon-animatie is .mp4, met een resolutie van 1280*800, minder dan 4MB.",
  "steps.3": "Stap 3",
  "steps.3.desc": "Selecteer alle emoticonbestanden, comprimeer ze tot een .zip-bestand en upload ze.",
  "steps.3.desc.ps": "Geen mappen nesten voor compressie.",
  "emo.info": "Emoticonpakketinformatie",
  "key.emo.use.tip": "Deze stickerpack is alleen geldig voor het {key} model.",
  "emo.upload": "Uploaden van emoticons",
  "upload.del.confirm": "Het bestand zal permanent verwijderd worden, weet u het zeker?",
  "scope.agent": "Alle robots",
  "key.scope.agent": "alle {key} robots",
  "scope.store": "Alle robots van de aangewezen winkel",
  "scope.robot": "Aangewezen robot",
  "emo.upload.tip": "Gelieve een zip-bestand te uploaden, de totale grootte moet minder dan 50M zijn.",
  "emo.step.info.1": "Vervang stap voor stap de emoticonbestanden volgens de emo-map.",
  "emo.step.info.2": "De hiërarchie van mappen, de namen van mappen en bestanden mogen niet worden gewijzigd.",
  "emo.step.info.3": "Het bestand mag niet groter zijn dan 50M, de afbeeldingsresolutie is 1920*1200 pixels, het formaat voor emoticons is MP4-formaat.",
  "emo.step.info.4": "Emotiebestanden blij, boos, verdrietig, vrolijk, linker- en rechteroor, enzovoort, 14 MP4's + 1 PNG-plaatshouderafbeelding (zonder plaatshouderafbeelding kan het wisselen van emoties leiden tot een zwart scherm)",
  "imp.robots.step1": "Download sjabloon",
  "imp.robots.step2": "Vul de MAC in het sjabloon in",
  "not.in.stock": "Niet op voorraad",
  "key.not": "niet de {key}",
  "del.emoji.tip": "Na verwijdering heeft dit geen invloed op de emoticonpakketten die door de robot zijn gebruikt.",
  "store.list": "Winkellijst",
  "robot.list": "Robotslijst",
  "name.repeat": "Naam duplicaat",
  "record.repeat": "Er zijn dubbele items.",
  "zip.content.abnormal": "Niet volgens de eisen gecomprimeerde emoticonpakketten.",
  "scop.tip1": "1. Alles: {key} zal worden gepusht naar alle robots onder de agent. Nieuw gebonden robots zullen automatisch {key} verkrijgen.",
  "scop.tip2": "2. Volgens de winkel: {key} zal alleen worden gepusht naar de robots onder de geselecteerde winkel, en nieuwe robots die aan de geselecteerde winkel zijn gebonden, zullen automatisch {key} verkrijgen.",
  "scop.tip3": "3. Volgens apparaat: {key} zal alleen worden gepusht naar de geselecteerde robot.",
  "emoji.pkg": "emoticonpakket",
  "voice.pkg": "Stemmenpakket",
  "key.voice.use.tip": "Dit audiopakket is alleen geldig voor het {key} model.",
  "voice.del.tip": "Na verwijdering zal er in dit scenario geen spraakinhoud meer worden afgespeeld.",
  "batch.step1": "Download de Excel-tabel met VoiceID en de vergelijking van spraakuitzendingsscenario's",
  "batch.step2": "Volgens de \"voiceID en scènevergelijkingstabel\", hernoem de aangepaste spraak mp3-bestandsnamen één voor één naar de overeenkomstige voiceID.",
  "batch.step2.ps1": "Zorg er absoluut voor dat elke audiobestand correct is benoemd met de voiceID, anders zal het uploaden mislukken.",
  "batch.step3": "Nadat alle aangepaste spraakbestanden in een map zijn geplaatst, selecteer de map om ze in bulk te uploaden.",
  "batch.step3.ps1": "Let op dat u de map niet comprimeert.",
  "batch.step3.ps2": "2) U kunt maximaal 300 audiobestanden per keer uploaden, elk bestand mag niet groter zijn dan 3MB.",
  "batch.btn": "Selecteer de map die je wilt uploaden",
  "file.type.error": "Bestandstypefout",
  "count.limit": "Het aantal documenten overschrijdt de {key} limiet.",
  "wrong.file.type": "Onjuist bestandstype",
  "file.size.exceeds": "Het bestandsformaat overschrijdt de {key}-limiet.",
  "voice.packing.tip": "Gelieve de pagina niet te sluiten, spraakpakket wordt samengesteld...",
  "business.district.desc": "Robots in het winkelgebied kunnen maaltijden van meerdere restaurants bezorgen."
}