export default {
  "bd.account": "account",
  "bd.username": "Naam",
  "bd.role": "karakter",
  "bd.name": "Winkelgebied Naam",
  "bd.numOfStores": "Aantal winkels",
  "bd.createtime": "Aanmaakdatum",
  "bd.updatetime": "Bijgewerkt tijd",
  "bd.operation": "Bediening",
  "bd.check": "Bekijken",
  "bd.edit": "Redacteur",
  "bd.qrcode": "Download de QR-code",
  "bd.new": "Nieuw",
  "bd.goback": "terugkeer",
  "bd.account.placeholder": "Voer alstublieft het accountnummer in",
  "bd.name.placeholder": "Voer de naam van het winkelgebied in",
  "bd.inquire": "Onderzoek",
  "bd.reset": "Herstellen",
  "bd.store.tip": "Kies alstublieft een winkel.",
  "bd.store.placeholder": "Voer alstublieft uw namen in.",
  "bd.map.tip": "Kies alstublieft een kaart",
  "bd.store.order": "Nummer",
  "bd.store.name": "Winkelnaam",
  "bd.store.label": "Kies een winkel",
  "bd.map.label": "Kies kaart",
  "bd.map.name": "Kaartnaam",
  "bd.map.uploadtype": "Uploadtype",
  "bd.map.association": "Gerelateerd productaantal",
  "bd.map.version": "versie",
  "bd.map.using": "In gebruik",
  "bd.map.unused": "Ongebruikt",
  "bd.map.uploadtype.apk": "APK uploaden",
  "bd.map.uploadtype.platform": "Platform uploaden",
  "bd.map.choose": "keuze",
  "bd.store.industry": "industrie",
  "bd.store.address": "Winkeladres",
  "bd.store.normal": "normaal",
  "bd.store.logout": "Uitschrijven",
  "bd.insiders.noOperatingAuthority": "Interne medewerkers hebben geen toegangsrechten!",
  "bd.store.reminder": "Warme tip: Alleen winkels in \"normale\" staat worden ondersteund."
}