export default {
  "component.tagSelect.expand": "ontvouwen",
  "component.tagSelect.collapse": "Opvouwen",
  "component.tagSelect.all": "alles",
  "key.select.max": "Kies maximaal {key} robots",
  "trial.period.day": "Proefperiode/dagen",
  "lease.cycle.month": "Huurperiode/maand",
  "required.warn": "U heeft verplichte velden die ingevuld moeten worden.",
  "first.imp.time": "Eerste importtijd",
  "validate.robot.key.warn": "Voer het volledige SN (PID) of MAC in",
  "change.to.complex.query": "Schakel over naar complexe zoekopdracht",
  "change.to.simple.query": "Schakel over naar eenvoudige zoekopdracht",
  "openapi.docs": "API-ontwikkelingsdocumentatie",
  "customer.name": "Handelsnaam",
  "key.template": "sjabloon",
  "confirm.file.upload": "Bevestig alstublieft of het bestand volledig is geüpload.",
  "upload.fail": "Uploaden mislukt, probeer het opnieuw.",
  "key.success": "Succes",
  "key.fail": "mislukking",
  "import.result": "Importresultaten",
  "incompatibility.versions": "De nieuwe versie is niet compatibel met de oude versie.",
  "auto.jump.available": "Er zal automatisch worden omgeleid naar een beschikbare versie...",
  "import.maxcount.tip": "Er zijn meer dan {count} MAC's gedetecteerd, het systeem heeft alleen de eerste {count} MAC's geïmporteerd, importeer de overige MAC's opnieuw."
}