export default {
  "dc.total": "Totaal",
  "dc.yesterday": "Gisteren",
  "dc.last7days": "Afgelopen 7 dagen",
  "dc.last30days": "Afgelopen 30 dagen",
  "dc.naturalDay": "natuurdag",
  "dc.natureWeek": "Natuurlijke week",
  "dc.naturalMonth": "natuurlijke maand",
  "dc.chainRatio": "maand-op-maand",
  "dc.cumulativeNumber": "Cumulatief aantal",
  "dc.activeRate": "Activiteitsgraad",
  "dc.robotOperationOverview": "Overzicht van de werking van de machine",
  "dc.workTime": "Werkuren",
  "dc.runningMileage": "Bedrijfskilometerstand",
  "dc.taskTimes": "Uitvoeren van taken",
  "dc.robotRunningPeakTrend": "Trend van piekprestaties van robots",
  "dc.monthOnMonth": "Jaar-op-jaar en maand-op-maand",
  "dc.numberOfRobotRuns": "Robots werking aantal",
  "dc.stages": "{num} toestellen",
  "dc.robotOverview": "Machineoverzicht",
  "dc.powerOnRobot": "Opstartrobot",
  "dc.bindTheRobot": "Gebonden robot",
  "dc.activateRobot": "Activeer de robot",
  "dc.numberOfRobotsBound": "Gebonden machineaantal",
  "dc.numberOfActiveRobots": "Geactiveerde machines",
  "dc.storeOverview": "Winkeloverzicht",
  "dc.numberOfActiveStores": "Actieve winkels",
  "dc.numberOfNewStores": "Nieuw toegevoegde winkels",
  "dc.activeStore": "Actieve winkel",
  "dc.silentStore": "Stille Winkel",
  "dc.activeRobotPoweredOn": "Opstarten actieve robot",
  "dc.downtime": "Onderbreking duur",
  "dc.operatingHours": "Bedrijfsuren",
  "dc.emptyActiveStore": "Geen actieve winkels op dit moment",
  "dc.emptySilentStore": "Tijdelijk geen stille winkels",
  "dc.export": "Exporteren",
  "dc.addStore": "Nieuwe winkel",
  "dc.cumulativeStores": "Cumulatieve winkels",
  "dc.storeName": "Winkelnaam",
  "dc.storeNamePlaceholder": "Voer de naam van de winkel in",
  "dc.query": "Onderzoek",
  "dc.activeRank": "Actieve ranglijst",
  "dc.creationTime": "Aanmaakdatum",
  "dc.activeRobot": "Opstartrobot",
  "dc.runTime": "Bedrijfstijd",
  "dc.key.robot": "robot",
  "dc.key.boottime": "Opstarttijd",
  "dc.key.starttime": "Starttijd van de werking",
  "dc.task.number": "Taakfrequentie",
  "dc.robots.all": "Alle robots",
  "dc.robot.select": "Kies alstublieft een robot.",
  "dc.tab.delivery": "Leveringsgegevens",
  "dc.tab.cruise": "Cruisegegevens",
  "dc.tab.greeter": "Leidende gegevens",
  "dc.tab.interaction": "Interactieve gegevens",
  "dc.tab.solicit": "Klantgegevens",
  "dc.tab.grid": "Paleisrastergegevens",
  "dc.tab.ad": "Advertentiegegevens",
  "dc.tab.recovery": "Tegenbod data",
  "dc.mileage": "Bedrijfskilometerstand",
  "dc.runtime": "Bedrijfstijd",
  "dc.interactiveVisits": "Interactie-aantal",
  "dc.interactionTime": "Interactietijd",
  "dc.greetings": "Begroetingen aantal",
  "dc.reached": "Bereikte personen",
  "dc.attract": "Aantrekkelijke bezoekersaantallen",
  "dc.voiceInteractions": "Aantal spraakinteracties",
  "dc.voiceinteractionTime": "Interactieduur van spraak",
  "dc.takeMeInCount": "\"Neem me mee naar de winkel\" soort raster",
  "dc.featuredItemCount": "\"Speciale producten\" categorie raster",
  "dc.favorablePromotionsCount": "\"Promotieactiviteiten\" categorie raster",
  "dc.guideToMenuCount": "\"Leidende positie\" soort rooster",
  "dc.posterCount": "\"Poster\" stijl raster",
  "dc.usherCount": "\"Leidende\" soort paleisrooster",
  "dc.danceCount": "\"Dans\" soort vakje",
  "dc.videoPosterCount": "\"Video poster\" stijl raster",
  "dc.smallScreenExposureTime": "Kleine scherm afspeeltijd",
  "dc.smallScreenExposures": "Kleine scherm afspeeltelling",
  "dc.bigScreenExposureTime": "Grote scherm afspeeltijd",
  "dc.bigScreenExposures": "Grote scherm afspeeltelling",
  "dc.deliveryTables": "Bezorgde tafelnummers",
  "dc.deliveryPlate": "Aantal bezorgde maaltijden",
  "dc.numberOfTieLessons": "Aantal keren dat gasten naar hun tafel zijn begeleid",
  "dc.numberOfCleanTables": "Schone tafels tellen",
  "tip.export.nodata": "Er zijn geen gegevens beschikbaar om te exporteren.",
  "dc.robotOperationOverview.toolTip": "De algehele werking van de robot",
  "dc.robotOperationOverview.toolTip-1": "Werkuren (h): Het totaal aantal uren dat de robots, die door de winkels zijn gebonden tijdens de uitbreiding door de agent, hebben gewerkt binnen de opgegeven datumbereik.",
  "dc.robotOperationOverview.toolTip-2": "Werkuren (h): Het totale aantal uren dat de robots, die door de winkels zijn gebonden tijdens de uitbreiding door de agent, hebben gewerkt binnen de opgegeven datumbereik.",
  "dc.robotOperationOverview.toolTip-3": "3. Aantal uitgevoerde taken: Het totale aantal taken uitgevoerd door alle robots die gekoppeld zijn aan winkels uitgebreid door de agent binnen de opgegeven datumbereik.",
  "dc.robotRunningPeakTrend.toolTip": "Robots functioneren op piekniveau trend situatie",
  "dc.robotRunningPeakTrend.toolTip-1": "1. Natuurlijke dag: U kunt het aantal operationele eenheden van verschillende soorten robots binnen elke periode van 24 uur op elke willekeurige dag opvragen.",
  "dc.robotRunningPeakTrend.toolTip-2": "2. Natuurlijke week: U kunt elke willekeurige week opvragen en het aantal operationele eenheden van verschillende soorten robots voor elke dag bekijken.",
  "dc.robotRunningPeakTrend.toolTip-3": "3. Natuurlijke maand: U kunt het aantal operationele eenheden van verschillende soorten robots voor elke dag van een willekeurige maand opvragen.",
  "dc.robotOverview.toolTip": "Robots activering en actieve status",
  "dc.robotOverview.toolTip-1": "Opstartrobot: Het cumulatieve aantal keer dat robots zijn opgestart in winkels uitgebreid door agenten binnen de datumbereik.",
  "dc.robotOverview.toolTip-2": "2. Cumulatief aantal: Het totale aantal gebonden robots vanaf de datum waarop de agent voor het eerst een winkelrobot bond tot aan de einddatum van de selectieperiode.",
  "dc.robotOverview.toolTip-3": "3. Activiteitsgraad = binnen de datumbereik, (aantal actieve robots ÷ cumulatief aantal) * 100%.",
  "dc.robotOverview.toolTip-4": "4. Gekoppelde robots: Het totale aantal robots dat door de agent binnen de datumperiode aan de winkel is gekoppeld.",
  "dc.robotOverview.toolTip-5": "5. Activering van robots: Het totale aantal robots dat binnen de datumbereik door de agenten is geactiveerd en gekoppeld aan de winkels.",
  "dc.storeOverview.toolTip": "Uitbreiding van de winkelactiviteit en nieuwe situaties",
  "dc.storeOverview.toolTip-1": "Actieve winkels: Binnen de datumreeks zijn de door de agent ontwikkelde winkels waarin robots actief zijn, gerekend als één actieve winkel.",
  "dc.storeOverview.toolTip-2": "2. Cumulatief aantal: Het totale aantal winkels dat is opgeteld vanaf de datum van de eerste binding van de winkel door de agent tot aan de einddatum van de geselecteerde periode.",
  "dc.storeOverview.toolTip-3": "3. Activiteitsgraad = binnen de datumbereik, (aantal actieve winkels ÷ cumulatief aantal) * 100%.",
  "dc.storeOverview.toolTip-4": "4. Aantal nieuwe winkels: Het totale aantal nieuwe winkels dat is toegevoegd binnen de opgegeven datumbereik.",
  "dc.storeOverview.toolTip-5": "5. Top 10 actieve winkels: Binnen de datumrange worden de door de agent ontwikkelde winkels gerangschikt op basis van de gebruiksfrequentie en de operationele duur van de robots. Hoe hoger de gebruiksfrequentie en hoe langer de operationele duur, des te hoger de winkel op de ranglijst van activiteit staat.",
  "dc.storeOverview.toolTip-6": "Top 10 stille winkels: Binnen de datumreeks worden winkels die door de agent zijn uitgebreid en waar de robotactiviteit is gestopt met een activiteitsniveau van 0, beschouwd als een stille winkel. Hoe meer robots er zijn gestopt en hoe langer de stilte duurt, des te hoger de winkel op de stilte-ranglijst staat.",
  "dc.activeStore.toolTip": "Binnen de datumbereik worden winkels die door de agent zijn uitgebreid en waar robots actief zijn, beschouwd als 1 actieve winkel.",
  "dc.silentStore.toolTip": "Alle machines die in de winkel zijn gebonden, zijn binnen de datumbereik niet ingeschakeld, wat telt als één stille winkel.",
  "dc.addStore.toolTip": "Binnen de datumbereik, het cumulatieve aantal nieuw toegevoegde winkels.",
  "dc.cumulativeStores.toolTip": "Vanaf de datum van de eerste binding van de winkel door de agent tot aan de geselecteerde einddatum, het cumulatieve aantal winkels binnen deze periode.",
  "robot.status.bind.tip": "1. Reeds ontkoppeld: de robot is momenteel gekoppeld aan een andere winkel, deze gegevens zijn de historische gegevens van de geselecteerde datum onder de winkel.",
  "robot.status.unbind.tip": "2. Reeds gebonden: De robot is momenteel gebonden aan deze winkel, en deze gegevens zijn de operationele gegevens van de winkel voor de geselecteerde datum.",
  "cruise.tip.run.mileage": "Binnen de datumbereik, de totale afgelegde afstand van de patrouillerende werking van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "cruise.tip.run.duration": "Binnen de datumbereik, de totale duur van de patrouille-uitvoering van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "cruise.tip.interaction.times": "Tijdens de datumperiode, het totale aantal interacties van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "cruise.tip.interaction.duration": "Binnen de datumbereik, de totale interactieduur van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "delivery.tip.run.mileage": "Binnen de datumbereik, de totale afgelegde afstand van de bezorgingsoperaties van alle aan de winkel gekoppelde robots uitbreiden.",
  "delivery.tip.run.duration": "Binnen de datumbereik, de totale looptijd van de bezorging van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "delivery.tip.task.num": "Binnen het datumbereik, het totale aantal uitgevoerde taken door alle robots die aan de winkel zijn gekoppeld",
  "delivery.tip.delivery.tables": "Binnen de datumbereik, het aantal bezorgtafels uitbreiden voor alle robots die gebonden zijn aan de winkels van de agent.",
  "delivery.tip.delivery.plates": "Binnen de datumbereik, het aantal bezorgde maaltijdbladen van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "greeter.tip.run.mileage": "Binnen de datumbereik, de totale afgelegde afstand van de leidende robots die gebonden zijn aan alle uitgebreide winkels door de agent.",
  "greeter.tip.run.duration": "Binnen de datumbereik, de totale operationele duur van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "greeter.tip.task.times": "Binnen de datumbereik, het aantal keer dat de agent uitbreidingswinkels alle gekoppelde robots de leidende positie taken hebben uitgevoerd.",
  "interaction.tip.all.times": "Binnen de datumbereik, het aantal keer dat mens-machine interacties (aanrakingen, spraakinteractie) plaatsvinden met alle gebonden robots in de uitgebreide winkels van de agent.",
  "interaction.tip.voice.times": "Binnen de datumbereik, het aantal keer dat spraakinteracties zijn uitgevoerd door alle robots die gekoppeld zijn aan de winkels uitgebreid door de agent.",
  "interaction.tip.duration": "Binnen de datumbereik is de totale duur van spraakinteracties van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "solicit.tip.duration": "Binnen de datumbereik, de totale operationele duur van klantenwerving door alle gebonden robots onder de uitgebreide winkels van de agent.",
  "solicit.tip.hello.times": "Binnen de datumbereik, het aantal keren dat alle gebonden robots in de uitgebreide winkels van de agent een begroeting doen.",
  "solicit.tip.reached.times": "Binnen de datumbereik, het aantal keer dat gebruikers bereikt zijn door alle gebonden robots onder de uitgebreide winkels van de agent.",
  "solicit.tip.attach.times": "Binnen de datumbereik, bereiken de agenten alle gebruikers die verbonden zijn met de robots in de uitgebreide winkels, en het aantal mensen dat blijft staan.",
  "solicit.tip.interation.times": "Binnen het datumbereik, het aantal keren dat alle aan winkels gekoppelde robots door gebruikers zijn geactiveerd.",
  "grid.click.times": "Binnen het datumbereik is het aantal keer dat deze functie is aangeklikt op alle gebonden robots in de uitgebreide winkels van de agent.",
  "ad.tiny.play.duration": "Binnen de datumbereik, de totale speelduur van kleine schermadvertenties op alle gebonden robots onder de uitgebreide winkels van de agent.",
  "ad.tiny.play.times": "Tijdens de periode, het aantal keren dat advertenties op kleine schermen zijn afgespeeld op alle robots die gebonden zijn aan de winkels uitgebreid door de agent.",
  "ad.large.play.duration": "Binnen de datumbereik, de speelduur van grote schermadvertenties op alle gebonden robots onder de uitgebreide winkels van de agent.",
  "ad.large.play.times": "Tijdens de periode heeft de agent het aantal keren dat advertenties op grote schermen zijn afgespeeld op alle robots die aan de winkels zijn gekoppeld, uitgebreid.",
  "recycle.tip.mileage": "Binnen de datumbereik, de totale afgelegde afstand van de terugkeeroperatie van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "recycle.tip.duration": "Binnen de datumbereik, de totale operationele duur van de terugkoppeling van alle gebonden robots onder de uitgebreide winkels van de agent.",
  "recycle.tip.tables": "Tijdens de periode heeft de agent het aantal keren dat de tafels zijn schoongemaakt door alle aan de winkel gekoppelde robots uitgebreid.",
  "by.key": "Druk op {toets}",
  "by.store": "Volgens de winkel",
  "by.robot": "Volgens de machine",
  "by.day": "per dag",
  "by.hour": "per uur",
  "export.config": "Exportconfiguratie",
  "timeby.config.label": "Tijdsperiode data export regelconfiguratie",
  "robot.sn_mac": "Robot SN/MAC",
  "dc.clean.area.total": "Schoonmaak totale oppervlakte (m²)",
  "dc.clean.area.total.tip": "Binnen de datumbereik is de totale cumulatieve schoonmaakoppervlakte van alle robots die gebonden zijn aan winkels uitgebreid door de agent.",
  "dc.clean.time.total": "Totale schoonmaaktijd (u)",
  "dc.clean.time.total.tip": "Tijdens de periode heeft de agent de totale cumulatieve schoonmaaktijd van alle robots die aan de uitgebreide winkels zijn gekoppeld.",
  "dc.clean.task.number": "Schoonmaaktaken",
  "dc.clean.task.number.tip": "Binnen de datumbereik, het totale aantal schoonmaaktaken uitgevoerd door robots die gebonden zijn aan winkels uitgebreid door de agent.",
  "dc.power.consumption": "Energieverbruik (kWh)",
  "dc.power.consumption.tip": "Binnen de datumbereik, de totale elektriciteitsverbruik van alle robots die gebonden zijn aan winkels uitgebreid door de agent.",
  "dc.water.consumption": "Waterverbruik (ml)",
  "dc.water.consumption.tip": "Binnen de datumbereik is het totale cumulatieve waterverbruik van alle robots die gebonden zijn aan winkels uitgebreid door de agent.",
  "dc.tab.all": "Alle modi",
  "dc.tab.scrubbing": "Wasvloermodus",
  "dc.tab.sweeping": "Veegmodus",
  "dc.sweep.vacuuming": "Tapijt stofzuigen",
  "dc.sweep.dustpush": "Stille stofduwer",
  "dc.delivery": "Bezorging",
  "dc.clean": "Schoonmaken",
  "dc.time": "tijd",
  "dc.基本数据": "Basisgegevens",
  "dc.清洁任务分布": "Schoonmaaktaak uitvoeringsverdeling",
  "dc.清洁任务分布描述": "Binnen de geselecteerde datumbereik, de totale som van taken uitgevoerd door alle robots gekoppeld aan de winkel, per uur van elke natuurlijke dag. (Voorbeeld: Als de datum is ingesteld van 1 januari tot 2 januari, en er worden taken uitgevoerd van 1:00 tot 2:00 op 1 januari en taken om 1:00 op 2 januari, dan is het aantal taken om 1:00 uur in totaal 2, en het aantal taken om 2:00 uur is 1.)",
  "dc.robot.delivery.tip": "Deze machine is geen bezorgtype machine.",
  "dc.robot.clean.tip": "Deze machine is geen schoonmaaktype machine.",
  "dc.store.unknow": "Sorry, de winkel is niet gevonden.",
  "dc.mileage.tip": "De bedrijfskilometerstand bevat alleen de operationele gegevens van bezorgrobots, niet de operationele gegevens van schoonmaakrobots.",
  "input.name.search": "Voer alstublieft {key} in om te zoeken"
}