export default {
  "log.boot": "Opstart Zelftest",
  "log.abnormal": "Abnormale storing",
  "log.charge": "Oplaadlogboek",
  "log.battery": "Batterij gezondheidstoestand",
  "production.date": "Productiedatum",
  "boot.status": "toestand",
  "boot.undetected": "Niet gedetecteerd",
  "boot.normal": "normaal",
  "boot.abnormal": "abnormaal",
  "key.no": "nummer",
  "log.production.time": "Logboek aanmaaktijd",
  "log.push.time": "Logboek uploaden naar de cloud tijd",
  "boot.description": "beschrijving",
  "boot.check_module": "Zelfcontrole module status",
  "poweron.ratio": "Opslagverhouding (%)",
  "robot.softVer": "Softwareversie",
  "robot.hardVer": "Firmwareversie",
  "common.systemid": "Besturingssysteemversie",
  "common.battery": "Huidige batterijniveau",
  "check.abnormal": "Er is een afwijking.",
  "check.normal": "Geen afwijkingen",
  "error.category": "Storingstype",
  "error.detail": "Storingsdetails",
  "error.grade": "Storingsniveau",
  "error.list": "Storingslijst",
  "error.ID": "Storings-ID",
  "filter.more": "Meer filters",
  "charge.count_battery": "Oplaadvermogen",
  "charge.count_time": "Oplaadtijd",
  "soh.battery_sn": "Batterij SN",
  "soh.full": "Batterijcapaciteit (mAh)",
  "soh.remaining": "Restcapaciteit (mAh)",
  "soh.battery_voltage": "Batterijspanning (mV)",
  "soh.soh": "Batterijgezondheidsindex",
  "soh.cycle": "Herhalingsaantal",
  "soh.battery_type": "Batterijtype",
  "tip.soh": "Het logboek wordt alleen gerapporteerd wanneer dit veld verandert.",
  "key.clip": "Met één klik kopiëren",
  "collapse": "Opvouwen",
  "please.select": "Gelieve te selecteren",
  "please.input": "Voer alstublieft in",
  "cycle.range.tip": "Er zijn geen gegevens in het bereik van de lus."
}