export default {
  "menu.dataCenter": "Gegevenscentrum",
  "menu.dataCenter.dashBoard": "Instrumentenpaneel",
  "menu.dataCenter.operationAnalysis": "Operationele Analyse",
  "menu.dataCenter.operationAnalysis.aStoreOperations": "Winkelbedrijfsranglijst",
  "menu.dataCenter.operationAnalysis.bStoreProduct": "Product Operationeleiderboard",
  "menu.dataCenter.operationAnalysis.cAtiveProduct": "Actieve Productanalyse",
  "menu.dataCenter.operationAnalysis.sProductRoom": "Productbezorgingstaakstatistieken",
  "menu.dataCenter.operationAnalysis.eProductBackPlate": "Productterugbiedingstaakstatistieken",
  "menu.dataCenter.operationAnalysis.fProductDisinfect": "Productdesinfectietaakstatistieken",
  "menu.dataCenter.operationAnalysis.gProductRunning": "Product Operation Overzicht",
  "menu.dataCenter.operationAnalysis.hProductDaily": "Product dagelijkse gemiddelde gegevens",
  "menu.dataCenter.operationAnalysis.iShopOperation": "Winkel Operationele Statistieken per Tijdsperiode",
  "menu.dataCenter.operationAnalysis.jProductGrameTime": "Productperiode operationele statistieken",
  "menu.dataCenter.operationAnalysis.kShopEverydayOperation": "Winkeldagelijkse operationele gegevensstatistieken",
  "menu.dataCenter.operationAnalysis.LShopSevenOperation": "Winkel gemiddelde operationele gegevensstatistieken van de afgelopen zeven dagen",
  "menu.dataCenter.operationAnalysis.mProductEverydayOperation": "Product dagelijkse operationele gegevensstatistieken",
  "menu.dataCenter.operationAnalysis.nProductSevenOperation": "Product Zeven Operationele Gegevensstatistieken",
  "menu.dataCenter.operationAnalysis.VRobotTaskAnalysis": "Analyse van robot taken",
  "menu.reportLog": "Ingediende logboeken",
  "menu.reportLog.foodDelivery": "Bezorgtaak",
  "menu.reportLog.recycleDish": "Tegenbod taak",
  "menu.reportLog.disInfect": "Ontsmettingstaak",
  "menu.reportLog.flashDelivery": "Kamerbezorgingstaak",
  "menu.reportLog.powerOn": "Opstart Zelftest",
  "menu.reportLog.charge": "Oplaadlogboek",
  "menu.reportLog.failure": "Abnormale storing",
  "menu.reportLog.upgrade": "Upgrade rapport",
  "menu.reportLog.batteryHealth": "Batterij gezondheidstoestand",
  "menu.reportLog.AbnormalIPAddr": "Abnormale IP-adresregistratie",
  "menu.reportLog.about2fall_report": "Valpreventie logboek",
  "menu.valueAdded": "Meerwaardediensten",
  "menu.valueAdded.custom": "Aangepaste spraak V1.1",
  "menu.valueAdded.customV1": "Aangepaste spraak V1.0",
  "menu.valueAdded.software": "Softwarefunctiepakket",
  "menu.valueAdded.tts": "TTS-vraag en antwoord",
  "menu.valueAdded.sip": "SIP-telefoondienstinstelling",
  "menu.account": "Accountbeheer",
  "menu.account.accountConfig": "Accountconfiguratie",
  "menu.systemManage.AccountOperationHistory": "Bedieningsgeschiedenis",
  "menu.AccountOperationHistory": "Bedieningsgeschiedenis",
  "menu.systemManage": "Systeembeheer",
  "menu.systemManage.dictionaryManagement": "Woordenboekbeheer",
  "menu.systemManage.messageNotification": "Berichtgeving",
  "menu.openPlatform": "Open Platform",
  "menu.openPlatform.applicationCenter": "Aanvraagcentrum",
  "menu.openPlatform.developDoc": "Ontwikkelingsdocumentatie",
  "menu.returnManage": "Terug naar beheer",
  "menu.returnManage.record": "Terugkeerrecord",
  "menu.returnManage.useReturn": "Gebruik retourneren",
  "menu.customerCenter": "Klantencentrum",
  "menu.customerCenter.storeManagement": "Winkelbeheer",
  "menu.customerCenter.storeDetail": "Winkeldetails",
  "menu.customerCenter.bindRobots": "Gebonden robot",
  "menu.customerCenter.bindARobot": "Toevoegen van een robot",
  "menu.customerCenter.storeRobotManagement": "Winkelapparatuur",
  "menu.customerCenter.activeCodeManagement": "Activeringscode",
  "menu.customerCenter.financialInstitution": "Financiële instellingen",
  "menu.customerCenter.financialDetail": "Financiële instelling details",
  "menu.customerCenter.agent": "Agentenbeheer",
  "menu.customerCenter.agentDetail": "Agent Details",
  "menu.productCenter": "Productcentrum",
  "menu.productCenter.productArchives": "Productdossier",
  "menu.fileCenter": "Documentencentrum",
  "menu.fileCenter.mapFile": "Kaartbestand",
  "menu.fileCenter.formFile": "Acceptatiebewijs",
  "menu.fileCenter.downloadFile": "Document download",
  "menu.equipmentCenter": "Productcentrum",
  "menu.equipmentCenter.productArchives": "Productdossier",
  "menu.equipmentCenter.productLibrary": "Machineproductenbibliotheek",
  "menu.equipmentCenter.outboundProducts": "Producten uit magazijn naar ondergeschikte agenten",
  "menu.equipmentCenter.viewProductInfo": "Bekijk productinformatie",
  "menu.equipmentCenter.productEdit": "Redactie-informatie",
  "menu.equipmentCenter.installedProduct": "Geïnstalleerd product",
  "menu.equipmentCenter.installedProducts": "Geïnstalleerd product",
  "menu.equipmentCenter.flowCard": "Gebonden dataverkeer kaartproduct",
  "menu.equipmentCenter.productDetail": "Productdetails",
  "menu.equipmentCenter.productChangeRecord": "Productwijzigingslogboek",
  "menu.equipmentCenter.product-change-records": "Apparatuur wijzigingslogboek",
  "menu.equipmentCenter.flowCardChangeRecord": "Veranderingsrecord van dataverbruik kaart",
  "menu.equipmentCenter.assignedProduct": "Toegewezen operationeel product",
  "menu.equipmentCenter.unallocatedProduct": "Niet-toegewezen operationele producten",
  "menu.equipmentCenter.antiSmuggling": "Preventie van goederen smokkel risicobeheersing",
  "menu.equipmentCenter.accessories": "Onderdelenbeheer",
  "menu.welcome": "Welkom",
  "menu.more-blocks": "Meer blokken",
  "menu.home": "Startpagina",
  "menu.admin": "Beheerpagina",
  "menu.admin.sub-page": "Secundaire beheerpagina",
  "menu.login": "Inloggen",
  "menu.register": "Registratie",
  "menu.register.result": "Registratieresultaat",
  "menu.dashboard.analysis": "Analysepagina",
  "menu.dashboard.monitor": "Bewakingspagina",
  "menu.dashboard.workplace": "werkbank",
  "menu.exception.403": "403",
  "menu.exception.404": "404",
  "menu.exception.500": "vijfhonderd",
  "menu.form": "Formulierpagina",
  "menu.form.basic-form": "Basisformulier",
  "menu.form.step-form": "Stapsgewijs formulier",
  "menu.form.step-form.info": "Stapsgewijs formulier (invullen van overboekingsinformatie)",
  "menu.form.step-form.confirm": "Stapsgewijs formulier (Bevestiging overboekingsinformatie)",
  "menu.form.step-form.result": "Stapsgewijs formulier (voltooid)",
  "menu.form.advanced-form": "Geavanceerd formulier",
  "menu.list": "Lijstpagina",
  "menu.list.table-list": "Onderzoeksformulier",
  "menu.list.basic-list": "Standaardlijst",
  "menu.list.card-list": "Kaartenlijst",
  "menu.list.search-list": "Zoeklijst",
  "menu.list.search-list.articles": "Zoeklijst (artikelen)",
  "menu.list.search-list.projects": "Zoeklijst (items)",
  "menu.list.search-list.applications": "Zoeklijst (apps)",
  "menu.profile": "Detailpagina",
  "menu.profile.basic": "Basisgegevenspagina",
  "menu.profile.advanced": "Geavanceerde detailpagina",
  "menu.result": "Resultatenpagina",
  "menu.result.success": "Succespagina",
  "menu.result.fail": "Mislukkingspagina",
  "menu.exception": "Uitzonderingspagina",
  "menu.exception.not-permission": "403",
  "menu.exception.not-find": "404",
  "menu.exception.server-error": "vijfhonderd",
  "menu.exception.trigger": "Fout geactiveerd",
  "menu.account.center": "Persoonlijk Centrum",
  "menu.account.settings": "Persoonlijke instellingen",
  "menu.account.trigger": "Er is een fout opgetreden",
  "menu.account.logout": "Uitloggen",
  "menu.editor": "Grafische editor",
  "menu.editor.flow": "Proceseditor",
  "menu.editor.mind": "Mindmap-editor",
  "menu.editor.koni": "Topologie-editor",
  "menu.test": "test",
  "menu.dataCenter.operationAnalysis.oFoodDelivery": "Product Bezorgservice Eettafel Datastatistieken",
  "menu.dataCenter.operationAnalysis.pReturnPlate": "Productterugbiedingsdienst eettafelgegevensstatistieken",
  "menu.dataCenter.operationAnalysis.RCruiseMode": "Productcruisemodus gegevensstatistieken",
  "menu.dataCenter.operationAnalysis.TSolicitCustomersMode": "Producten Acquisitiemodus Datastatistieken",
  "menu.dataCenter.operationAnalysis.SLeadmode": "Productleiderschapsmodel voor gegevensstatistieken",
  "menu.dataCenter.operationAnalysis.UAdPlayMode": "Advertentie afspeelgegevens statistieken",
  "menu.customerCenter.rcagent": "Geassocieerde agenten",
  "menu.customerCenter.equipment": "Eigendomsapparatuur",
  "menu.customerCenter.financialInfo": "Financieringsinstelling details",
  "menu.reportLog.SIMCardLog": "Datapakket",
  "menu.SIMCardMgr": "Dataverkeerkaartbeheer",
  "menu.SIMCardMgr.ActivedCardMgr": "Geactiveerde datakaart",
  "menu.SIMCardMgr.ExpiredCardMgr": "Waarschuwing: de databundelkaart verloopt binnenkort",
  "menu.BusinessDistrictMgr": "Winkelgebiedbeheer",
  "menu.BusinessDistrictMgr.Add": "Nieuw",
  "menu.BusinessDistrictMgr.Edit": "Redacteur",
  "menu.BusinessDistrictMgr.Detail": "Bekijken",
  "menu.dataCenter.dataOverview": "Gegevensoverzicht",
  "menu.dataCenter.storeAnalysis": "Winkelanalyse",
  "menu.dataCenter.robotOperationAnalysis": "Robotbedrijfsanalyse",
  "menu.dataCenter.robotTaskAnalysis": "Robotbezorgingsgegevens",
  "menu.dataCenter.cleanRobotData": "Robots reinigen gegevens",
  "menu.app-center": "Applicatiecentrum",
  "menu.app-center.emoticon-mgmt": "Robotgezichtsuitdrukkingenbeheer",
  "menu.app-center.emoticon-add": "Het maken van een emoticonpakket",
  "menu.app-center.emoticon-edit": "Emoticonpakket bewerken",
  "menu.app-center.voice-mgmt": "Robotstembeheer",
  "menu.app-center.voice-add": "Aangepast spraakpakket maken",
  "menu.app-center.voice-edit": "Aangepast spraakpakket bewerken",
  "menu.app-center.voice-auth": "Stem pakket autorisatie",
  "menu.app-center.open-platform": "Open Platform",
  "menu.app-center.open-platform-detail": "Bekijken",
  "menu.app-center.open-platform-add": "Aanvraag voor applicatie",
  "menu.app-center.open-platform-edit": "Redigeer applicatie",
  "menu.log-center": "Logcentrum",
  "menu.log-center.robot-logs": "Robotdagboek",
  "menu.message-center": "Berichtencentrum",
  "menu.message-center.message-detail": "Nieuwsdetails"
}