export default {
  "exception.monitor": "Abnormale bewaking",
  "key.whitelist": "{key} witte lijst",
  "risk.control.settings": "Risicobeheersingsinstellingen",
  "robot.run.district": "Werkingsgebied",
  "robot.report.time.latest": "Recente rapportagetijd",
  "robot.lock.confirm": "Na het uitvoeren van de vergrendelingsactie zal de robot niet meer te gebruiken zijn, en kan deze niet ontkoppeld of overgezet worden naar een andere winkel.",
  "robot.lock.remark": "Opmerkingen over het vergrendelen van het apparaat",
  "robot.unlock.confirm": "Na het uitvoeren van de ontgrendelingsprocedure zal de robot de waarschuwing opheffen en weer normaal functioneren.",
  "robot.exception.view": "Bekijk details van de uitzondering",
  "robot.info": "Robotinformatie",
  "shop.info": "Winkel informatie",
  "robot.category": "Robottype",
  "robot.smuggling.warning": "Abnormale waarschuwing, er bestaat een risico op goederensmokkel.",
  "robot.run.location": "Bedrijfslocatie",
  "key.remove": "verwijderen",
  "time.add": "Toevoegingstijd",
  "use.instructions": "Gebruiksaanwijzing",
  "confirm.remove": "Na het uitvoeren van de verwijderingsoperatie zal de machine het \"anti-ontduikingsrisicobeheer\" mechanisme activeren.",
  "device.add": "Apparaat toevoegen",
  "use.instruction.reason": "Redenen voor het toevoegen van de machine aan de witte lijst",
  "query.result": "Onderzoeksresultaten",
  "query.byMac": "MAC-adres zoeken",
  "base.version.No": "Basisversienummer",
  "key.auto.lock": "Automatisch slotmechanisme {sleutel}",
  "district.china.mainland.outside": "Hongkong, Macau, Taiwan en het buitenland",
  "district.china.mainland": "China vasteland",
  "key.enable": "In gebruik nemen",
  "edit.risk.control.settings": "Bewerk risicobeheerinstellingen",
  "robot.status.locked": "Vergrendeld toestel",
  "robot.status.unlock": "Ontgrendeld",
  "robot.sn/pid": "Apparaat SN (PID)",
  "key.status": "{key} status",
  "risk.control": "Risicobeheersing",
  "status.risk.control": "Risicobeheerstatus",
  "status.robot": "Robotstatus",
  "status.abnormal.watning": "Abnormale waarschuwing",
  "datatype.nomal": "Normale gegevens",
  "datatype.nomal.tip": "Inclusief: robots op de witte lijst, ontgrendelde robots en robots die nooit risicocontrole op doorverkoop hebben geactiveerd.",
  "datatype.abnomal": "abnormale gegevens",
  "opr.area": "{key} bedrijfsgebied",
  "goto.check": "Ga kijken",
  "risk.control.notify": "Risicobeheer melding",
  "risk.control.warntip": "Robots die in niet-gemachtigde gebieden werken, zullen bij herhaaldelijke activering worden vergrendeld.",
  "abnormal.waning.robots": "Abnormaal waarschuwingsapparaat",
  "etc.": "wachten",
  "robot.lock.switch": "Vergrendelingsschakelaar",
  "robot.lock.auto": "Automatisch slot",
  "robot.lock.manual": "Handmatig vergrendelen",
  "abnormal.lock.robots": "Risicobeheersing vergrendelingsapparaat",
  "robot.lock.tip": "Risicocontrole op doorverkoop van goederen is geactiveerd, het apparaat is momenteel vergrendeld. Neem bij vragen contact op met de service medewerkers van Purdue.",
  "warning.send.email": "Abnormale waarschuwingsherinnering e-mail",
  "input.email.multiple": "Meerdere e-mailadressen invoeren met een nieuwe regel",
  "input.forExample": "Voorbeeld:",
  "email.invalid": "Ongeldig e-mailadres",
  "PuduBot": "Vreugde Levering",
  "BellaBot": "Bella",
  "HolaBot": "Goed dan",
  "Puductor": "Vrolijk Wegspelen",
  "Puductor2": "Vrolijk Verdwenen 2",
  "KettyBot": "kalebas",
  "FlashBot": "Bliksemdoos",
  "PuduCC1": "Uit het stof",
  "SwiftBot": "Slimme Bezorging",
  "PuduBot2": "Vreugde Levering 2",
  "PuduSH1": "leeuwtijger"
}