export default {
  "请输入": "Voer alstublieft in",
  "选择": "keuze",
  "返回": "terugkeer",
  "未绑定": "Niet gebonden",
  "已安装": "Geïnstalleerd",
  "导入时间": "Importtijd",
  "代理名称": "Agentnaam",
  "所属代理": "Behorend tot het agentschap",
  "出库撤回": "Magazijn Terugtrekking",
  "出库撤回说明": "Uitleg over het terugtrekken van goederen uit het magazijn",
  "撤回后下级代理": "Na intrekking zal de ondergeschikte agent niet in staat zijn om de robot te bedienen of te bekijken.",
  "出库撤回失败": "Uitgaande terugtrekking mislukt",
  "该代理已将机器人绑定门店": "Het agentschap heeft de robot al aan de winkel gekoppeld.",
  "出库至下级代理": "Uitgegeven aan de ondergeschikte agent",
  "未选择下级代理商": "Geen ondergeschikte agent geselecteerd",
  "没有出库产品": "Geen producten uitgevoerd",
  "确定出库": "Bevestigde uitgaande goederen",
  "出库说明": "Uitleg bij uitgaan van voorraad",
  "选择未出库产品": "Selecteer producten die niet uit het magazijn zijn",
  "选择下级代理商": "Kies een ondergeschikte agent",
  "代理商帐号": "Agentaccount",
  "注册地址": "Geregistreerd adres",
  "销售区域": "Verkoopgebied",
  "注册时间": "Registratietijd",
  "一级": "Eerste niveau",
  "二级": "tweede niveau",
  "已损坏": "Beschadigd",
  "已锁机": "Vergrendeld toestel",
  "冻结中": "Bevroren",
  "过期": "Fabriekstest is verlopen",
  "未激活": "Niet geactiveerd",
  "激活": "Activeren",
  "已激活": "Geactiveerd",
  "已入库": "Al opgeslagen",
  "厂测中": "Fabriekstest in uitvoering",
  "无记录": "Geen gegevens",
  "全部": "alles",
  "产品信息": "Productinformatie",
  "维保信息": "Onderhoudsinformatie",
  "服务信息": "Dienstinformatie",
  "产品操作记录": "Productbedieningsrecord",
  "换板待验证": "Vervanging in afwachting van verificatie",
  "待验证": "Te verifiëren",
  "所属门店": "Toebehorende winkel",
  "所属代理商": "Behorend tot de agent",
  "激活时间": "Activeringstijd",
  "昵称": "bijnaam",
  "SN": "SN(PID)",
  "MAC": "MAC",
  "软件版本": "Softwareversie",
  "固件版本": "Firmwareversie",
  "现场用途": "Ter plaatse gebruik",
  "机器分组": "Machinegroepering",
  "用机类型": "gebruiksmachinetype",
  "保修时长": "Garantieperiode",
  "实施工程师": "Uitvoerend Ingenieur",
  "运维工程师": "Onderhoudsingenieur",
  "首次导入代理": "Eerste import van een agent:",
  "绑定代理": "Gebonden agent:",
  "的门店": "van de winkel:",
  "从门店": "Vanuit de winkel:",
  "解绑返回代理": "Ontkoppelen, terug naar agent:",
  "代理": "Agent:",
  "出库产品到下级代理": "Producten uit het magazijn naar de ondergeschikte agent:",
  "从下级代理": "Van de ondergeschikte agent:",
  "出库撤回到代理": "Uit magazijn teruggetrokken naar agent:",
  "操作说明": "Bedieningsinstructies:",
  "操作人": "Bedieningspersoon:",
  "机器产品库使用提示": "Productopslag voor machines, bevat producten die zijn teruggestuurd naar het magazijn nadat ze zijn losgekoppeld van winkels van handelaren; producten die al zijn verkocht en gekoppeld aan winkels van handelaren. Tegelijkertijd kun je \"niet-gekoppelde\" producten uit het magazijn halen en naar je ondergeschikte distributeurs sturen.",
  "未綁定状态": "Niet-gebonden status: robots die nog niet aan een winkel van een handelaar zijn gekoppeld en zich nog in het magazijn bevinden.",
  "功能介绍": "Functiebeschrijving:",
  "冻结": "Bevroren",
  "取消冻结": "Opheffen van bevriezing",
  "未绑定状态描述": "Niet gebonden: de status waarbij producten uit het magazijn van het Purdue-bedrijf worden uitgeslagen naar de voorraad van de agent, zonder dat de agent deze heeft verkocht of toegewezen aan een specifieke winkel.",
  "未激活状态描述": "Niet geactiveerd: De toestand waarin de agent de robot verkoopt en koppelt aan een fysieke winkel, maar de robot is niet ingeschakeld en geactiveerd.",
  "已激活状态描述": "Geactiveerd: De status waarin de agent de robot die aan de winkel is gekoppeld opstart en activeert voor gebruik.",
  "已冻结状态描述": "Bevroren: De status van de robot nadat deze door de agent is bevroren; in deze staat kan de robot niet meer worden gebruikt.",
  "换板待验证状态描述": "Wachtend op verificatie na vervanging van het moederbord: de status tijdens het vervangingsproces wanneer het moederbord van de robot beschadigd is.",
  "还剩": "er is nog over",
  "个月": "maand",
  "系统操作": "Systeemoperatie",
  "租赁时长": "Huurperiode",
  "试用时长": "Proefperiode",
  "试用截止时间": "Proefperiode einddatum",
  "门店安装时间": "Winkelinrichtingstijd",
  "备件信息": "Onderdeel Informatie",
  "备件类型": "Onderdeeltype",
  "导出全部": "Exporteer alles",
  "供应商": "Leverancier",
  "型号": "model",
  "上报时间": "Rapportagetijd",
  "电池": "batterij",
  "雷达": "radar",
  "相机": "camera",
  "核心板": "Kernpaneel",
  "屏幕": "scherm",
  "充电器": "oplader",
  "功能板": "Functieversie",
  "上位机": "bovenliggende computer"
}