export default {
  "productListIframe.无记录": "Geen gegevens",
  "productListIframe.厂测中": "Fabriekstest in uitvoering",
  "productListIframe.厂测过期": "Fabriekstest verlopen",
  "productListIframe.已入库": "Al opgeslagen",
  "productListIframe.未绑定": "Niet gebonden",
  "productListIframe.未激活": "Niet geactiveerd",
  "productListIframe.已激活": "Geactiveerd",
  "productListIframe.已冻结": "Bevroren",
  "productListIframe.换板待验证": "Vervanging in afwachting van verificatie",
  "productListIframe.保内": "Binnenbehoud",
  "productListIframe.保外": "buiten de garantie",
  "productListIframe.产品名称": "Productnaam",
  "productListIframe.所属门店": "Toebehorende winkel",
  "productListIframe.所属代理": "Behorend tot het agentschap",
  "productListIframe.产品状态": "Productstatus",
  "productListIframe.首次激活时间": "Eerste activeringstijd",
  "productListIframe.最新安装时间": "Laatste installatietijd",
  "productListIframe.代理维保状态": "Status van vervangend onderhoud",
  "productListIframe.终端维保状态": "Eindstation onderhoudsstatus",
  "productListIframe.设备地址": "Apparaatadres",
  "productListIframe.关闭": "Gesloten",
  "productListIframe.没有更多了": "Er is niet meer.",
  "productListIframe.加载中": "Laden",
  "productListIframe.请选择机器": "Selecteer alstublieft de machine",
  "productListIframe.搜索": "zoeken",
  "productListIframe.清除筛选": "Filters wissen",
  "productListIframe.查看更多": "Bekijk meer",
  "productListIframe.完成": "Voltooid"
}