export default {
  "app.setting.pagestyle": "Algemene stijlinstellingen",
  "app.setting.pagestyle.dark": "Donkere menu-stijl",
  "app.setting.pagestyle.light": "Heldere kleuren menu stijl",
  "app.setting.content-width": "Inhoudsgebied breedte",
  "app.setting.content-width.fixed": "vaste breedte",
  "app.setting.content-width.fluid": "stromend",
  "app.setting.themecolor": "Hoofdkleur",
  "app.setting.themecolor.dust": "Schemering",
  "app.setting.themecolor.volcano": "vulkaan",
  "app.setting.themecolor.sunset": "Avondschemering",
  "app.setting.themecolor.cyan": "Helderblauw",
  "app.setting.themecolor.green": "Noorderlichtgroen",
  "app.setting.themecolor.daybreak": "Dageraadblauw (standaard)",
  "app.setting.themecolor.geekblue": "Geek Blue",
  "app.setting.themecolor.purple": "zo paars",
  "app.setting.navigationmode": "Navigatiemodus",
  "app.setting.sidemenu": "Zijbalkmenu-indeling",
  "app.setting.topmenu": "Bovenste menulay-out",
  "app.setting.fixedheader": "Vaste Header",
  "app.setting.fixedsidebar": "Vast zijmenu",
  "app.setting.fixedsidebar.hint": "Zijbalkmenu-indeling kan worden geconfigureerd",
  "app.setting.hideheader": "Header verbergen bij het naar beneden scrollen",
  "app.setting.hideheader.hint": "Vaste Header kan worden geconfigureerd",
  "app.setting.othersettings": "Andere instellingen",
  "app.setting.weakmode": "Kleurenzwaktemodus",
  "app.setting.copy": "Kopieerinstellingen",
  "app.setting.copyinfo": "Kopie geslaagd, vervang de standaardconfiguratie in src/defaultSettings.js",
  "app.setting.production.hint": "De configuratiebalk wordt alleen gebruikt voor preview in de ontwikkelomgeving en wordt niet weergegeven in de productieomgeving. Gelieve na het kopiëren het configuratiebestand handmatig te wijzigen."
}