export default {
  "app.settings.menuMap.basic": "Basisinstellingen",
  "app.settings.menuMap.security": "Veiligheidsinstellingen",
  "app.settings.menuMap.binding": "Accountkoppeling",
  "app.settings.menuMap.notification": "Nieuw bericht melding",
  "app.settings.basic.avatar": "profielfoto",
  "app.settings.basic.change-avatar": "Profielfoto wijzigen",
  "app.settings.basic.email": "e-mailbox",
  "app.settings.basic.email-message": "Voer alstublieft uw e-mailadres in!",
  "app.settings.basic.nickname": "bijnaam",
  "app.settings.basic.nickname-message": "Voer alstublieft uw bijnaam in!",
  "app.settings.basic.profile": "Persoonlijk profiel",
  "app.settings.basic.profile-message": "Voer alstublieft een persoonlijke introductie in!",
  "app.settings.basic.profile-placeholder": "Persoonlijk profiel",
  "app.settings.basic.country": "Land/regio",
  "app.settings.basic.country-message": "Voer alstublieft uw land of regio in!",
  "app.settings.basic.geographic": "Provincie of stad",
  "app.settings.basic.geographic-message": "Voer alstublieft uw provincie en stad in!",
  "app.settings.basic.address": "Straatadres",
  "app.settings.basic.address-message": "Voer alstublieft uw straatadres in!",
  "app.settings.basic.phone": "Contacttelefoonnummer",
  "app.settings.basic.phone-message": "Voer alstublieft uw telefoonnummer in!",
  "app.settings.basic.update": "Bijwerken van basisinformatie",
  "app.settings.security.strong": "sterk",
  "app.settings.security.medium": "Midden",
  "app.settings.security.weak": "zwak",
  "app.settings.security.password": "Accountwachtwoord",
  "app.settings.security.password-description": "Huidige wachtwoordsterkte",
  "app.settings.security.phone": "Beveiligingstelefoon",
  "app.settings.security.phone-description": "Gekoppeld aan mobiele telefoon",
  "app.settings.security.question": "Beveiligingsvraag",
  "app.settings.security.question-description": "Er is geen beveiligingsvraag ingesteld, een beveiligingsvraag kan effectief de veiligheid van uw account beschermen.",
  "app.settings.security.email": "Reserve e-mailadres",
  "app.settings.security.email-description": "Gekoppeld e-mailadres",
  "app.settings.security.mfa": "MFA-apparaat",
  "app.settings.security.mfa-description": "Niet gekoppeld aan MFA-apparaat, na koppeling kan een tweede bevestiging worden uitgevoerd.",
  "app.settings.security.modify": "Aanpassen",
  "app.settings.security.set": "Instellingen",
  "app.settings.security.bind": "gebonden",
  "app.settings.binding.taobao": "Gekoppeld aan Taobao",
  "app.settings.binding.taobao-description": "Momenteel geen Taobao-account gekoppeld",
  "app.settings.binding.alipay": "Gekoppeld aan Alipay",
  "app.settings.binding.alipay-description": "Momenteel geen Alipay-account gekoppeld",
  "app.settings.binding.dingding": "Gekoppeld aan DingTalk",
  "app.settings.binding.dingding-description": "Momenteel geen DingTalk-account gekoppeld",
  "app.settings.binding.bind": "gebonden",
  "app.settings.notification.password": "Accountwachtwoord",
  "app.settings.notification.password-description": "Berichten van andere gebruikers worden via interne berichten gemeld.",
  "app.settings.notification.messages": "Systeembericht",
  "app.settings.notification.messages-description": "Systeemberichten worden via interne berichten gemeld.",
  "app.settings.notification.todo": "Te doen taken",
  "app.settings.notification.todo-description": "Te verrichten taken zullen via interne berichten worden medegedeeld.",
  "app.settings.open": "open",
  "app.settings.close": "betrekking",
  "robot.check.blacklist": "Het MAC-adres is toegevoegd aan de zwarte lijst, neem contact op met het bedrijf Purdue voor afhandeling."
}