export default {
  "language.select.label": "Kies een taal",
  "voice.add": "Toevoegen van spraak",
  "voice.category": "Stemclassificatie",
  "voice.mp3": "Gesproken audio",
  "voice.mp3.del.confirm": "Na het verwijderen van deze spraakopname, zullen nieuw toegevoegde aangepaste spraakpakketten deze scenario-opname niet meer bevatten.",
  "voice.language": "Taal van de spraak",
  "voice.id.correct.tip": "Vul de juiste robot VoiceID in, anders kan er geen spraakuitzending plaatsvinden.",
  "voice.display.scene.desc": "Scène voor spraakuitzending",
  "voice.display.content": "De inhoud van de tekst voor spraakuitzending",
  "voice.upload.limit": "Ondersteunt het uploaden van MP3-bestanden tot maximaal 1MB",
  "voice.pkg.desc": "Stemmenpakket beschrijving",
  "voice.access": "Geautoriseerde robot",
  "voice.pkg.auth": "Stem pakket autorisatie",
  "key.agent.name": "Agent",
  "key.auth.add": "Toevoegen van autorisatie",
  "key.batch.replace": "Batchvervanging",
  "key.robot.category": "Robottype",
  "key.robot.No": "robotnummers",
  "voice.all": "Alle spraak",
  "voice.merge.submit": "Synthetische spraak genereren en voltooien",
  "voice.merge.submit.failed": "Stemmenpakket bijwerken mislukt",
  "voice.change.mp3": "Vervang audio",
  "voice.validity.period.tip": "Kies een geldigheidsduur",
  "voice.authorized.mac.tip": "Dit audiopakket is geautoriseerd voor de volgende {robot} robot.",
  "voice.authorized.store.tip": "Dit audiopakket is geautoriseerd voor de {robot} robots in de volgende winkels.",
  "voice.authorized.agent.tip": "Dit geluidspakket is geautoriseerd voor alle winkels onder het agentschap voor de {robot} robot.",
  "voice.voiceid.notmatch": "De bestandsnaam komt niet overeen met enige VoiceID.",
  "voice.filesize.exceed": "Het bestandsgrootte overschrijdt de toegestane limiet.",
  "voice.upload.warning1": "De mappen in de map hoeven niet te worden gecomprimeerd.",
  "voice.upload.warning2": "De naam van het audiobestand moet de voiceID zijn die overeenkomt met het type robotproduct.",
  "voice.upload.warning3": "Ondersteunt maximaal 200 mp3-audiobestanden en mag niet meer dan 200MB zijn.",
  "voice.upload.warning4": "Omdat het bestand groot is, mag u tijdens het uploadproces niet afsluiten.",
  "not.your.robot": "Niet de robot in uw voorraad",
  "key.limit.import.count": "Beperk {key} stuks",
  "navBar.lang": "taal"
}